{
  "hash": "9c5fd1a4b567b947c9d0791f809b6af4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"LongBet: Dynamic Treatment Effects in Staggered Rollouts\"\ndescription: \"LongBet extends Bayesian causal forests to panel data, so the effect of a rollout becomes a trajectory over time since launch that can differ from one unit to the next. This chapter fits one on a randomized marketplace rollout and reads the answer three ways: the average, the segments, and every seller.\"\nformat:\n  html:\n    css: longbet.css\n    include-in-header:\n      text: |\n        <script src=\"assets/longbet-legacy-links.js\"></script>\nshare:\n  permalink: \"https://book.martinez.fyi/longbet.html\"\n  description: \"LongBet: dynamic treatment effects in staggered rollouts\"\n  linkedin: true\n  email: true\n  mastodon: true\n---\n\n::: {.callout-note title=\"LongBet chapter sequence\"}\nThis is the first of six chapters on LongBet:\n\n1. **LongBet: Dynamic Treatment Effects in Staggered Rollouts** (this chapter): the model, a randomized rollout, the fit and its checks, the average effect against a design-based benchmark, and heterogeneity down to the individual seller.\n2. **[LongBet: From Effects to Decisions](longbet_decisions.qmd)**: dollar valuations, a ranked rollout under a capacity constraint, and a joint screen over three outcomes at once.\n3. **[LongBet and Modern Difference-in-Differences](longbet_did.qmd)**: the comparison a reviewer will ask for, against two-way fixed effects, Callaway and Sant'Anna, Sun and Abraham, and Borusyak-Jaravel-Spiess.\n4. **[LongBet: Forecasting and Observational Panels](longbet_extensions.qmd)**: projecting past the study window, adoption that was not randomized, where a unit's level comes from, and covariates that move over time.\n5. **[LongBet: Ordinal Outcomes and Customer Experience](longbet_ordinal.qmd)**: ordered ratings and the probability of hitting a customer-experience target.\n6. **[LongBet: Randomized Encouragement and Adoption Timing](longbet_encouragement.qmd)**: when you can only invite people to adopt, and the decision is whom to invite.\n:::\n\n## Why a Trajectory, Not a Number\n\n<img src=\"img/longbet.jpeg\" align=\"right\" height=\"280\" alt=\"Two treatment-effect trajectories separating over time above a row of trees of decreasing size: one climbs and keeps climbing, the other flattens, and past a dotted line both continue as dashed projections inside widening bands\" />\n\nThe models in the previous two chapters answer a question with no time dimension: what is the effect of the treatment on the outcome? In a business, that is rarely the whole question. A feature that lifts revenue by 10% in its first week and fades to nothing by its tenth averages about the same over a ten-week experiment as one that lifts revenue by 5% and holds there. They report the same average treatment effect. They are worth completely different amounts a year later, and they lead to opposite decisions.\n\nThey also rarely land on everyone equally. The same feature can be worth a quarter of a seller's revenue to one account and nothing to another, and the difference is usually predictable from things you already know about them.\n\nLongBet, introduced by @wang2024longbet, extends the Bayesian Causal Forest family, including BCF [@hahn2020bayesian] and XBCF, to panel data, so the treatment effect becomes a function of two things at once: **who** the unit is, and **how long it has been treated**. It was designed for short panels with large cross-sections, the shape of data that e-commerce, subscription, and marketplace businesses generate by default.\n\n## The Model\n\nFor unit $i$ in period $t$:\n\n$$\nY_{it} = \\mu(X_i, t) + \\beta_{S_{it}}\\,\\nu(X_i, t)\\,\\mathbf{1}\\{S_{it} \\ge 1\\} + \\gamma_i + \\epsilon_{it},\n\\qquad \\epsilon_{it} \\sim \\mathcal{N}(0, \\sigma^2)\n$$\n\nwhere\n\n  - $Y_{it}$ is the outcome and $X_i$ are pre-treatment covariates;\n  - $S_{it}$ is unit $i$'s **exposure**, the number of periods since it was treated, and zero before that. Treatment is absorbing: once a unit is treated it stays treated;\n  - $\\mu(\\cdot)$ is the **prognostic** forest, a sum of trees that predicts the untreated outcome;\n  - $\\beta_S$ is **one** Gaussian process over exposure, shared by every unit. It is where the model pools information about the *shape* of the response;\n  - $\\nu(\\cdot)$ is the **treatment** forest, a second sum of trees that scales that shape up or down for each kind of unit, which is where heterogeneity in the *size* of the effect lives;\n  - $\\gamma_i \\sim \\mathcal{N}(0, \\sigma^2_\\gamma)$ is a unit intercept, so each unit's own level is carried by a parameter rather than reconstructed from covariates;\n  - the indicator switches the treatment term on in treated cells only, so an untreated cell has no treatment contribution at all.\n\nThe effect of $S$ periods of exposure for a unit with covariates $X_i$ is the contrast against never being treated,\n\n$$\n\\tau_t(X_i, S) = \\beta_S\\,\\nu(X_i, t).\n$$\n\nOne curve, many sizes. That factorisation is what lets a short panel say something about a trajectory: every treated unit-period in the data, whenever it adopted, contributes to the same $\\beta_S$, while the forest sorts out who responds strongly.\n\n::: {.callout-note title=\"Implementation\"}\nLongBet is implemented in `longbet-jax`: a vectorised Metropolis-Hastings sampler written in JAX on top of `bartz`, with multiple chains, $\\hat R$, and optional GPU execution. It is reached from R with `library(longbet)` and from Python with `from longbet import LongBet`. Every sweep updates both forests with GROW, PRUNE, CHANGE and REGROW proposals, then the trajectory, the unit intercepts and the variances, plus a Metropolis move along the exact scale ridge between $\\beta$ and the treatment leaves. Chains start from the prior, so $\\hat R$ compares chains that could have found different regions.\n:::\n\n## What This Buys in a Randomized Rollout {#sec-longbet-why}\n\nThis chapter applies LongBet to a **randomized** experiment, so it is worth being precise about the division of labour. Random assignment is what identifies the effect. A simple comparison against a holdout is already unbiased. What the model adds is everything else:\n\n  - **Precision.** Weekly revenue per seller varies by orders of magnitude across sellers. A model of $\\mu(X_i, t)$ and $\\gamma_i$ explains that variation away before the effect is read off. This is the non-parametric cousin of ANCOVA and of CUPED [@deng2013cuped], and it is the difference between an experiment that answers your question and one that runs for another quarter.\n  - **Resolution.** The holdout comparison gives one number per period since launch. LongBet gives a posterior for every seller at every exposure, learned in one model rather than in subgroups you had to name in advance.\n  - **Reach.** Experiments end; business cases run for a year. The Gaussian process on $\\beta_S$ extrapolates the trajectory past the last period you observed (@sec-longbet-forecast in the third chapter).\n  - **Decisions.** Posterior draws convert directly into the quantity a business argues about: the probability that a seller is worth the cost (the [second chapter](longbet_decisions.qmd)).\n\n## The Business Problem\n\nYou are the data scientist at an online marketplace. The product team has built an **AI listing optimizer**: it rewrites seller titles and descriptions, suggests attributes, and re-crops photos. Leadership wants to know whether to make it permanent, and finance wants a number for next year's plan.\n\nThere are 400 sellers in the pilot and the optimizer cannot simply be switched on for all of them: each seller needs a supervised catalog migration, and the onboarding team can absorb about 80 sellers a week. The rollout is phased whether you like it or not.\n\nThat constraint is an opportunity. The field team's instinct is to start with the sellers most likely to benefit, which would make the rollout order a function of expected outcomes. Instead you randomize it: sellers are assigned at random, within strata defined by vertical, catalog size and fulfillment status, to one of three weekly launch waves or to a **holdout** that keeps the old experience for the study. The result is a **randomized staggered rollout**.\n\nThree questions have to be answered before the decision can be made. Does the lift last? Who does it help? What is it worth over a year? The economics are simple: the marketplace keeps a **12% take rate** on gross merchandise value (GMV), and running the optimizer costs about **\\$500 per seller per year**. A seller earns their keep only if the lift in their GMV, valued at the take rate, clears that cost.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(longbet)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(tibble)\nlibrary(ggplot2)\nlibrary(purrr)\nlibrary(knitr)\n\nsource(\"R/longbet-common.R\")\nsource(\"R/longbet-sim.R\")\nsource(\"R/longbet-artifacts.R\")\nverify_longbet_environment()\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## Simulating the Rollout\n\nAs elsewhere in this book the data are simulated, so every claim can be checked against a known truth. The outcome is **log weekly GMV**, which keeps a heavy-tailed dollar quantity roughly Gaussian and makes the effect read as an approximate percentage lift.\n\nThe calendar has three parts: weeks 1--4 are a **lookback window** used only to build covariates, weeks 5--20 are the **study panel** the model sees, with everyone untreated through week 8 and the three waves launching in weeks 9, 10 and 11, and weeks 21--24 are simulated but **withheld** so the third chapter can score a forecast.\n\nSellers differ enormously in level: catalog size, fulfillment status, vertical, and a seller-specific component the covariates never record. The treatment response compounds toward a plateau with the **same shape for everyone**, and its **size** is a smooth function of catalog breadth,\n\n$$\n\\tau_i(S) = a(L_i)\\,\\big(1 - e^{-S/4}\\big),\n\\qquad\na(L) = 0.30\\,\\mathrm{logit}^{-1}\\!\\left(\\frac{\\log L - \\log 40}{0.8}\\right).\n$$\n\nA seller with ten listings gains almost nothing; a seller with two hundred gains about a quarter of a log point, a lift of roughly 28% in dollars. Nothing in the model is told where that curve bends, or that catalog size matters at all.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nro <- simulate_rollout()\nlist2env(ro[c(\"n\", \"week_base\", \"week_study\", \"week_future\", \"weeks_all\", \"LAUNCH\", \"Tn\",\n              \"vertical\", \"fulfilled\", \"listings\", \"strata\", \"wave\", \"launch\", \"level_i\",\n              \"a_i\", \"S\", \"Z\", \"mu0_true\", \"y0\", \"tau_true\", \"y\", \"x\", \"base_level\",\n              \"sd_eps\", \"y_train\", \"z_train\", \"z_ext\", \"broad\", \"is_hold\")],\n         environment())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<environment: R_GlobalEnv>\n```\n\n\n:::\n\n```{.r .cell-code}\nS_observed <- max(rowSums(z_train))\ntruth_att  <- event_time_truth(tau_true[, match(week_study, weeks_all)], z_train)\ntable(wave)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwave\nHoldout      W1      W2      W3 \n    160      79      81      80 \n```\n\n\n:::\n:::\n\n\n`x` carries four time-invariant columns: log catalog size, fulfillment status, and the vertical one-hot encoded. The engine treats every column as ordered numeric, so a three-level factor coded 1, 2, 3 would impose a false ordering; one-hot encoding avoids it. The vertical does nothing in this simulation. It is there because a real panel always has covariates that turn out not to matter, and the forest has to discover that.\n\nEffects are on the log scale, so a coefficient $\\tau$ is a proportional lift of $e^{\\tau} - 1$. Every dollar figure in the next chapter goes through that conversion inside each posterior draw.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_rollout(z = z_train, t = week_study, labels = c(`9` = \"W1\", `10` = \"W2\", `11` = \"W3\"),\n             never_treated_label = \"Holdout\",\n             colors = c(`Not yet treated` = \"grey85\", Treated = PAL[[\"LongBet\"]],\n                        `Never treated` = \"grey62\"),\n             title = NULL) +\n  theme(legend.position = \"bottom\", panel.grid = element_blank())\n```\n\n::: {.cell-output-display}\n![The design, drawn from the treatment matrix itself: three randomized launch waves and a holdout over the sixteen study weeks.](longbet_files/figure-html/fig-rollout-1.png){#fig-rollout fig-alt='A tile chart with one row per wave. The holdout row is grey across all sixteen weeks. Wave rows turn blue at weeks nine, ten and eleven respectively and stay blue.' width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(wave = rep(wave, times = Tn), week = rep(weeks_all, each = n), y = as.vector(y)) %>%\n  group_by(wave, week) %>% summarise(y = mean(y), .groups = \"drop\") %>%\n  ggplot(aes(week, y, colour = wave)) +\n  geom_line(linewidth = 0.9) +\n  annotate(\"rect\", xmin = min(week_study) - 0.5, xmax = max(week_study) + 0.5,\n           ymin = -Inf, ymax = Inf, alpha = 0.06) +\n  geom_vline(xintercept = c(8.5, 20.5), linetype = \"dashed\", colour = \"grey40\", linewidth = 0.3) +\n  scale_colour_manual(values = c(W1 = \"#0072B2\", W2 = \"#56B4E9\", W3 = \"#009E73\", Holdout = \"grey45\")) +\n  labs(x = \"Week\", y = \"Mean log weekly GMV\", colour = NULL,\n       subtitle = sprintf(\"Shaded: the study panel. Seller levels have SD %.2f; weekly noise has SD %.2f.\",\n                          sd(level_i), sd_eps)) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Mean log weekly GMV by wave. Each wave steps up at its own launch and keeps climbing; the holdout is flat. Sellers differ from one another far more than any of them moves over time, which is the variation the model has to explain away.](longbet_files/figure-html/fig-raw-1.png){#fig-raw fig-alt='Four lines over twenty-four weeks. The holdout line is flat. The three wave lines are flat until weeks nine, ten and eleven, then rise and level off.' width=768}\n:::\n:::\n\n\n## Fitting the Model {#sec-longbet-fitting}\n\n::: {.callout-note title=\"Sampler settings\"}\nFour chains start from the prior, each discarding 2,000 burn-in sweeps and then running 8,000 sweeps of which every eighth is retained, giving 1,000 draws per chain. The forests are the package defaults: 20 prognostic and 60 treatment trees of depth at most 8. A unit intercept is on. Neither forest splits on calendar time here, because this panel's untreated path has no calendar structure to find; the third chapter shows the switch that turns calendar splits back on when the business has seasonality.\n\nNone of these settings establishes convergence. The diagnostics after the fit do that.\n:::\n\n::: {.panel-tabset}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlb_fit <- lb_core_fit(ro)\n```\n:::\n\n\n## Python\n\n```python\nimport jax\nfrom longbet import LongBet, LongBetConfig\n\nconfig = LongBetConfig(\n    num_chains=4, num_burnin=2000, num_sweeps=1000, n_skip=8,\n    sig_knl=1.0, lambda_knl=2.0,\n    random_intercept=True, split_time_ps=False, split_calendar_trt=False,\n)\nmodel = LongBet(config)\nmodel.fit(y=y_train, x=x, z=z_train, t=week_study, key=jax.random.key(42))\n```\n:::\n\n`lb_core_fit()` is a thin wrapper that fits the model once and caches it, keyed on the engine source, the sampler settings and a digest of the data, so the next two chapters reuse this fit instead of repeating it. A few arguments deserve comment:\n\n  - `x` is the covariate matrix. Omitting `x_trt` lets both forests share one block of columns instead of allocating a duplicate set.\n  - `t` is the calendar index of the panel columns. LongBet infers each unit's exposure $S_{it}$ from `z` and `t`; you never construct it.\n  - The residual variance has a proper inverse-gamma prior, and so does the unit-intercept variance.\n  - `sig_knl` and `lambda_knl` are the standard deviation and lengthscale of the kernel on $\\beta_S$. A longer lengthscale favours a smoother trajectory.\n\nPrediction takes the fitted object, the covariates and a treatment panel. Passing the study weeks means the model and the benchmark below average exactly the same treated cells.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlb_pred <- predict(lb_fit, x = x, z = z_train, t = week_study, random_seed = 1)\nlb_att  <- get_att(lb_pred, alpha = 0.05)\nn_chains <- lb_fit$model_params$num_chains; n_sweeps <- lb_fit$model_params$num_sweeps\n```\n:::\n\n\n### Checking the sampler {#sec-longbet-sampler}\n\nThe checks are part of the analysis, and they are run on the quantities the chapter actually reports: the average effect at every exposure, both segment curves, and later every seller's own effect. The package's thresholds are a rank-normalized $\\hat R$ of at most 1.01 with bulk and tail effective sample sizes of at least 400.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nS_show <- 8\nbind_rows(\n  tibble(sweep = rep(seq_len(n_sweeps), times = n_chains),\n         chain = factor(rep(seq_len(n_chains), each = n_sweeps)),\n         value = as.vector(lb_fit$sigma0_draws) * lb_fit$sdy, series = \"Residual SD\"),\n  tibble(sweep = rep(seq_len(n_sweeps), times = n_chains),\n         chain = factor(rep(seq_len(n_chains), each = n_sweeps)),\n         value = lb_att$att_full[S_show, ], series = \"Average effect at S = 8\")\n) %>%\n  ggplot(aes(sweep, value, colour = chain)) +\n  geom_line(linewidth = 0.3, alpha = 0.8) +\n  facet_wrap(~ series, scales = \"free_y\") +\n  scale_colour_brewer(palette = \"Set1\") +\n  labs(x = \"Retained draw (within chain)\", y = NULL, colour = \"Chain\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Four chains for the residual scale and for the average effect at eight weeks of exposure. Chains that overlap and wander freely are what a well-explored posterior looks like; the table reports the numbers.](longbet_files/figure-html/fig-traces-1.png){#fig-traces fig-alt='Two trace panels, each with four coloured chains that overlap and fluctuate around a common level with no drift.' width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncore_diag <- bind_rows(\n  diagnose_draws(lb_att$att_full, lb_fit, \"Average effect, every exposure\")$summary,\n  diagnose_draws(event_time_draws(lb_pred$tauhats, z_train, broad), lb_fit,\n                 \"Broad-catalog effect (>= 50 listings)\")$summary,\n  diagnose_draws(event_time_draws(lb_pred$tauhats, z_train, !broad), lb_fit,\n                 \"Narrow-catalog effect (< 50 listings)\")$summary,\n  diagnose_draws(rbind(as.vector(lb_fit$sigma0_draws) * lb_fit$sdy), lb_fit, \"Residual SD\")$summary)\nkable(core_diag %>% select(-ok), digits = 3,\n      caption = sprintf(\"Sampling checks on the reported quantities. The gates are a rank-normalized R-hat of at most %.2f and bulk and tail effective sample sizes of at least %d at every target.\", GATE_RHAT, GATE_ESS))\n```\n\n::: {.cell-output-display}\n\n\nTable: Sampling checks on the reported quantities. The gates are a rank-normalized R-hat of at most 1.01 and bulk and tail effective sample sizes of at least 400 at every target.\n\n|Quantity                              | R-hat (max)| Bulk ESS (min)| Tail ESS (min)|Passed   |\n|:-------------------------------------|-----------:|--------------:|--------------:|:--------|\n|Average effect, every exposure        |       1.003|       1818.497|       3430.120|12 of 12 |\n|Broad-catalog effect (>= 50 listings) |       1.003|       1895.448|       3116.794|12 of 12 |\n|Narrow-catalog effect (< 50 listings) |       1.003|       1853.234|       3468.740|12 of 12 |\n|Residual SD                           |       1.001|       3928.084|       3823.269|1 of 1   |\n\n\n:::\n\n```{.r .cell-code}\nchain_tbl <- map_dfr(c(2, S_show), function(s_at) {\n  m <- matrix(lb_att$att_full[s_at, ], nrow = n_chains, byrow = TRUE)\n  tibble(Quantity = paste0(\"Average effect at S = \", s_at), Chain = seq_len(n_chains),\n         `Chain mean` = rowMeans(m), `Within-chain SD` = apply(m, 1, sd),\n         `Lag-1 autocorrelation` = apply(m, 1, function(v) cor(v[-1], v[-length(v)])))\n})\nkable(chain_tbl, digits = c(0, 0, 4, 4, 2),\n      caption = \"Chain by chain. Chains whose means differ by a within-chain standard deviation or more are exploring different regions; here they agree.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Chain by chain. Chains whose means differ by a within-chain standard deviation or more are exploring different regions; here they agree.\n\n|Quantity                | Chain| Chain mean| Within-chain SD| Lag-1 autocorrelation|\n|:-----------------------|-----:|----------:|---------------:|---------------------:|\n|Average effect at S = 2 |     1|     0.0551|          0.0148|                  0.09|\n|Average effect at S = 2 |     2|     0.0535|          0.0142|                  0.11|\n|Average effect at S = 2 |     3|     0.0542|          0.0144|                  0.04|\n|Average effect at S = 2 |     4|     0.0556|          0.0150|                  0.06|\n|Average effect at S = 8 |     1|     0.1139|          0.0135|                  0.03|\n|Average effect at S = 8 |     2|     0.1147|          0.0131|                  0.01|\n|Average effect at S = 8 |     3|     0.1146|          0.0136|                  0.03|\n|Average effect at S = 8 |     4|     0.1144|          0.0135|                  0.05|\n\n\n:::\n:::\n\n\nEvery reported quantity passes: the largest R-hat is 1.003 and the smallest bulk effective sample size is 1818. The intervals below can be read as summaries of this model's posterior.\n\nTwo parameters are deliberately absent from that table. The raw $\\beta_S$ draws are not a reported quantity: the likelihood depends on the product $\\beta_S\\nu$, so flipping the sign of both leaves it unchanged and chains routinely disagree about the sign of $\\beta$ while agreeing about every effect. The unit-intercept variance is a nuisance parameter that no reported number depends on. Diagnose what you report.\n\n## The Average Effect, Against a Design-Based Benchmark {#sec-longbet-att}\n\n\"The average effect\" here means the **event-time average on the treated**,\n\n$$\n\\mathrm{ATT}(S) = \\mathbb{E}\\!\\left[\\tau_i(S) \\mid i \\text{ has reached exposure } S\\right],\n$$\n\naveraged over treated sellers with sample-size weights across the waves that have reached exposure $S$ inside the study. The conditioning set changes with $S$: all three waves contribute at $S = 1$, only the first wave by $S = 12$.\n\nThe benchmark is what a careful analyst reaches for first. For each wave and each period since its launch, take the change in log GMV from the common pre-launch window and subtract the same change among holdout sellers, reweighted to that wave's randomization strata, then pool the waves by sample size. This is the group-time estimator of @callaway2021did specialised to a balanced panel with never-treated controls, which is exactly the design here. Every wave is compared only against the never-treated holdout, so the negative-weighting problem that afflicts two-way fixed effects under staggered adoption [@bacon2021difference; @roth2023trending] never arises. A second version adds a covariate regression fitted on the holdout, the linear cousin of the prognostic forest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npre_weeks <- 5:8\ny_study <- y[, match(week_study, weeks_all)]\ngt_plain <- group_time_did(y_study, launch, week_study, pre_weeks, strata = strata)\nadj <- did_covariate_adjustment(y_study, launch, week_study, pre_weeks,\n                                cbind(base_level = base_level, x))\ngt_adj <- group_time_did(y_study, launch, week_study, pre_weeks, strata = strata, adjust = adj)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\natt_df <- tibble(s = seq_len(S_observed), estimate = lb_att$att,\n                 lower = lb_att$intervals[1, ], upper = lb_att$intervals[2, ], truth = truth_att)\nggplot(att_df, aes(s)) +\n  geom_ribbon(aes(ymin = lower, ymax = upper, fill = \"LongBet\"), alpha = 0.22) +\n  geom_line(aes(y = estimate, colour = \"LongBet\"), linewidth = 0.9) +\n  geom_line(aes(y = truth, colour = \"Truth\"), linewidth = 0.9) +\n  geom_pointrange(data = gt_plain,\n                  aes(x = s, y = estimate, ymin = lower, ymax = upper, colour = \"Group-time DiD\"),\n                  size = 0.28, position = position_nudge(x = 0.14)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", colour = \"grey60\") +\n  scale_colour_manual(values = PAL) + scale_fill_manual(values = PAL, guide = \"none\") +\n  scale_x_continuous(breaks = seq_len(S_observed)) +\n  labs(x = \"Weeks since launch\", y = \"Effect on log weekly GMV\", colour = NULL,\n       subtitle = \"Effect on the treated, aligned on each wave's own launch week\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Event-time effects on log GMV: LongBet's posterior mean and 95% interval, the group-time benchmark with its 95% confidence interval, and the known truth, on identical cells and cohort weights.](longbet_files/figure-html/fig-att-1.png){#fig-att fig-alt='A rising curve from about 0.03 at one week since launch to about 0.13 at twelve weeks. The model\\'s band is narrow and tracks the black truth line; the benchmark\\'s point ranges are centred on the same path but roughly twice as wide.' width=816}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  score_curve(att_df$estimate, att_df$lower, att_df$upper, att_df$truth) %>%\n    mutate(Estimator = \"LongBet\", .before = 1),\n  score_curve(gt_plain$estimate, gt_plain$lower, gt_plain$upper, truth_att) %>%\n    mutate(Estimator = \"Group-time DiD vs holdout\", .before = 1),\n  score_curve(gt_adj$estimate, gt_adj$lower, gt_adj$upper, truth_att) %>%\n    mutate(Estimator = \"Group-time DiD + covariate adjustment\", .before = 1)\n) %>% kable(digits = 4, caption = sprintf(\"Three estimators of the same quantity over the %d observed event times, on one dataset.\", S_observed))\n```\n\n::: {.cell-output-display}\n\n\nTable: Three estimators of the same quantity over the 12 observed event times, on one dataset.\n\n|Estimator                             |   RMSE| Mean error| Interval width|Contained truth |\n|:-------------------------------------|------:|----------:|--------------:|:---------------|\n|LongBet                               | 0.0122|    -0.0039|         0.0596|12 of 12        |\n|Group-time DiD vs holdout             | 0.0153|     0.0007|         0.1037|12 of 12        |\n|Group-time DiD + covariate adjustment | 0.0149|     0.0005|         0.1034|12 of 12        |\n\n\n:::\n\n```{.r .cell-code}\nwidth_ratio <- mean(gt_plain$upper - gt_plain$lower) / mean(att_df$upper - att_df$lower)\n```\n:::\n\n\nThe three agree, which is the first thing to check and the reason to keep a design-based estimator in the report: randomization is what makes the estimate credible, and a material disagreement would be a reason to debug the model rather than to trust it. What differs is precision. The benchmark's intervals are about 1.7 times wider than the model's, because differencing removes each seller's level but leaves the week-to-week noise, while the model also pools the shape of the response across all three waves through $\\beta_S$.\n\n## What the Average Hides {#sec-longbet-heterogeneity}\n\nThe pooled curve averages sellers whose responses differ by an order of magnitude. Because the model returns a posterior for every seller at every event time, the same fit gives subgroup curves without refitting and without having pre-registered the subgroup.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsegments_df <- bind_rows(\n  curve_summary(event_time_draws(lb_pred$tauhats, z_train, broad),\n                event_time_truth(tau_true[, match(week_study, weeks_all)], z_train, broad), \"Broad catalog\"),\n  curve_summary(event_time_draws(lb_pred$tauhats, z_train, !broad),\n                event_time_truth(tau_true[, match(week_study, weeks_all)], z_train, !broad), \"Narrow catalog\"))\nsegments_gt <- bind_rows(\n  group_time_did(y_study, launch, week_study, pre_weeks, keep = broad, strata = strata) %>%\n    mutate(segment = \"Broad catalog\"),\n  group_time_did(y_study, launch, week_study, pre_weeks, keep = !broad, strata = strata) %>%\n    mutate(segment = \"Narrow catalog\"))\nggplot(segments_df, aes(s, colour = segment, fill = segment)) +\n  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.18, colour = NA) +\n  geom_pointrange(data = segments_gt, aes(y = estimate, ymin = lower, ymax = upper),\n                  size = 0.18, alpha = 0.55, linewidth = 0.4,\n                  position = position_dodge(0.45), show.legend = FALSE) +\n  geom_line(aes(y = estimate), linewidth = 0.9) +\n  geom_line(aes(y = truth), linewidth = 0.7, linetype = \"22\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", colour = \"grey60\") +\n  scale_colour_manual(values = PAL) + scale_fill_manual(values = PAL, guide = \"none\") +\n  scale_x_continuous(breaks = seq_len(S_observed)) +\n  labs(x = \"Weeks since launch\", y = \"Effect on log weekly GMV\", colour = NULL) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Effects by catalog breadth. Solid lines and bands: LongBet. Dashed: the known subgroup truth. Point ranges: the same group-time benchmark run inside each segment.](longbet_files/figure-html/fig-segments-1.png){#fig-segments fig-alt='Two pairs of curves. The broad-catalog curve rises to about 0.21 by twelve weeks; the narrow-catalog curve levels off near 0.10. Both model curves track their dashed truths, with bands roughly half the width of the benchmark\\'s point ranges.' width=816}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninner_join(segments_df %>% group_by(segment) %>% summarise(LongBet = mean(upper - lower), .groups = \"drop\"),\n           segments_gt %>% group_by(segment) %>% summarise(`Group-time DiD` = mean(upper - lower), .groups = \"drop\"),\n           by = \"segment\") %>%\n  mutate(Ratio = `Group-time DiD` / LongBet) %>% rename(Segment = segment) %>%\n  kable(digits = c(0, 4, 4, 1),\n        caption = \"Mean interval width by segment. The benchmark has to be told where to split; the forest learns the dependence on catalog size while fitting.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Mean interval width by segment. The benchmark has to be told where to split; the forest learns the dependence on catalog size while fitting.\n\n|Segment        | LongBet| Group-time DiD| Ratio|\n|:--------------|-------:|--------------:|-----:|\n|Broad catalog  |  0.0903|         0.1695|   1.9|\n|Narrow catalog |  0.0526|         0.1301|   2.5|\n\n\n:::\n:::\n\n\nNext, the effect of twelve weeks of exposure for **every** seller, holdout included, from a counterfactual panel in which everyone launches in week 9. Only the first wave actually reached that exposure, so the answer for the rest uses the model's pooling across covariates. This is the resolution a design-based estimator cannot produce without being told in advance where to look.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_all <- matrix(as.integer(week_study >= 9), n, length(week_study), byrow = TRUE)\nS_target <- sum(week_study >= 9)\npred_all <- predict(lb_fit, x = x, z = z_all, t = week_study, random_seed = 1)\ntau_hat_draws <- pred_all$tauhats[, ncol(z_all), ]\ntau_hat   <- rowMeans(tau_hat_draws)\ntau_truth <- a_i * h_shape(S_target)\nseller_diag <- diagnose_draws(tau_hat_draws, lb_fit,\n                              sprintf(\"Effect at S = %d for each of %d sellers\", S_target, n))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(listings = listings, estimate = tau_hat, truth = tau_truth) %>%\n  ggplot(aes(listings)) +\n  geom_point(aes(y = estimate, colour = \"LongBet\"), alpha = 0.35, size = 1) +\n  geom_line(aes(y = truth, colour = \"Truth\"), linewidth = 1) +\n  scale_x_log10(breaks = c(5, 10, 25, 50, 100, 250, 500)) +\n  scale_colour_manual(values = PAL) +\n  labs(x = \"Active listings (log scale)\", y = sprintf(\"Effect on log weekly GMV at S = %d\", S_target),\n       colour = NULL) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Estimated and known effects after twelve weeks of exposure for all 400 sellers, against catalog breadth.](longbet_files/figure-html/fig-sellers-1.png){#fig-sellers fig-alt='A scatter of posterior means rising with catalog size along a smooth black truth curve, from near zero below ten listings to about 0.25 above two hundred.' width=816}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(seller_diag$summary %>% select(-ok), digits = 3,\n      caption = \"Sampling checks across all 400 seller-level effects.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Sampling checks across all 400 seller-level effects.\n\n|Quantity                                 | R-hat (max)| Bulk ESS (min)| Tail ESS (min)|Passed     |\n|:----------------------------------------|-----------:|--------------:|--------------:|:----------|\n|Effect at S = 12 for each of 400 sellers |       1.003|       1119.374|       2435.865|400 of 400 |\n\n\n:::\n\n```{.r .cell-code}\ntibble(Quantity = c(\"Correlation with truth\", \"RMSE\", \"Mean absolute error\"),\n       Value = c(cor(tau_hat, tau_truth), sqrt(mean((tau_hat - tau_truth)^2)),\n                 mean(abs(tau_hat - tau_truth)))) %>%\n  kable(digits = 3, caption = sprintf(\"Quality of the seller-level effect estimates after %d weeks of exposure.\", S_target))\n```\n\n::: {.cell-output-display}\n\n\nTable: Quality of the seller-level effect estimates after 12 weeks of exposure.\n\n|Quantity               | Value|\n|:----------------------|-----:|\n|Correlation with truth | 0.932|\n|RMSE                   | 0.024|\n|Mean absolute error    | 0.019|\n\n\n:::\n:::\n\n\nRead the last figure carefully: it is a posterior for the *conditional* effect at a seller's covariates, not for that seller's own unobservable effect. Two sellers with identical covariates get identical posteriors, however differently the treatment would actually have landed on them. That is the right object for a targeting decision, which is where the [next chapter](longbet_decisions.qmd) goes.\n\n## It Does Not Distort a Simple Panel {#sec-longbet-additive}\n\nA flexible model is worth having only if it behaves when flexibility is not needed. Here is the same machinery on a panel built for the classical estimator: 300 units, eight periods, additive unit effects, staggered adoption in periods 3, 5 and 7 or never, and an effect that grows linearly with exposure and is **identical for every unit**. Nothing here needs a forest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nad <- simulate_additive()\nad_max_s <- max(ad$s[ad$z == 1])\nad_truth <- vapply(seq_len(ad_max_s), function(ss) mean(ad$tau[ad$s == ss]), numeric(1))\nad_adopt <- ifelse(is.finite(ad$adopt), ad$adopt, Inf)\nad_fit <- lb_artifact(\"additive_fit\",\n                      lb_key(\"additive\", lb_budget(4), LB_MODEL, digest::digest(ad[c(\"y\", \"x\", \"z\")])),\n                      export = \"ad\",\n                      builder = function() {\n                        f <- do.call(longbet::longbet,\n                                     c(list(y = ad$y, x = ad$x, z = ad$z, t = ad$tg, random_seed = 101L),\n                                       LB_MODEL, lb_budget(4)))\n                        p <- predict(f, x = ad$x, z = ad$z, t = ad$tg, summary_only = TRUE, random_seed = 1)\n                        list(att = get_att(p, alpha = 0.05),\n                             layout = chain_layout(f$model_params$num_chains, f$model_params$num_sweeps))\n                      })\nad_gt <- group_time_did(ad$y, ad_adopt, ad$tg, pre_periods = 1:2)\nkable(diagnose_draws(ad_fit$att$att_full, ad_fit$layout, \"Average effect, every exposure\")$summary %>% select(-ok),\n      digits = 3, caption = \"Sampling checks for the fit on the additive panel.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Sampling checks for the fit on the additive panel.\n\n|Quantity                       | R-hat (max)| Bulk ESS (min)| Tail ESS (min)|Passed |\n|:------------------------------|-----------:|--------------:|--------------:|:------|\n|Average effect, every exposure |       1.003|       3481.472|       3478.142|6 of 6 |\n\n\n:::\n\n```{.r .cell-code}\nbind_rows(\n  score_curve(ad_fit$att$att[seq_len(ad_max_s)], ad_fit$att$intervals[1, seq_len(ad_max_s)],\n              ad_fit$att$intervals[2, seq_len(ad_max_s)], ad_truth) %>% mutate(Estimator = \"LongBet\", .before = 1),\n  score_curve(ad_gt$estimate, ad_gt$lower, ad_gt$upper, ad_truth) %>%\n    mutate(Estimator = \"Group-time DiD\", .before = 1)\n) %>% kable(digits = 3, caption = \"On a purely additive panel the two estimators agree, and the model's regularisation costs nothing measurable here.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: On a purely additive panel the two estimators agree, and the model's regularisation costs nothing measurable here.\n\n|Estimator      |  RMSE| Mean error| Interval width|Contained truth |\n|:--------------|-----:|----------:|--------------:|:---------------|\n|LongBet        | 0.038|     -0.029|          0.219|6 of 6          |\n|Group-time DiD | 0.095|     -0.085|          0.384|6 of 6          |\n\n\n:::\n:::\n\n\nThe model was not told that the world was additive, that the effect was homogeneous, or that the trajectory was linear. It recovers the same curve as the estimator built for exactly this case, with intervals no wider. That is the reassurance worth having before using it where the classical estimator cannot go.\n\n## Conclusion\n\nA randomized staggered rollout identifies the average effect at every exposure, and a design-based comparison estimates it without any model at all. What the panel model adds is precision, and resolution: the same fit that reproduces the benchmark's average also delivers a trajectory per segment and a posterior per seller, without pre-registering a single subgroup.\n\nNone of that is a decision yet. In **[LongBet: From Effects to Decisions](longbet_decisions.qmd)** these trajectories become dollars, a ranked list of sellers under a capacity constraint, and a joint screen across three outcomes at once.\n\n::: {.callout-tip}\n## Learn more\n  - @wang2024longbet LongBet: heterogeneous treatment effect estimation in panel data.\n  - @longbetpkg The `longbet` package.\n  - @hahn2020bayesian Bayesian regression tree models for causal inference, the cross-sectional model LongBet extends.\n  - @callaway2021did and @bacon2021difference for the staggered-adoption literature the benchmark comes from.\n  - @deng2013cuped for the variance-reduction idea that $\\mu(X_i, t)$ generalises.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}