{
  "hash": "0f3d79653aeab8f0063ebf759bd7c864",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"LongBet: Randomized Encouragement and Adoption Timing\"\ndescription: \"When you cannot switch a feature on for a customer, only invite them to adopt it, the decision is whom to invite. The adoption-clock model composes an outcome equation on the adoption clock with an adoption hazard on the offer clock, and returns the effect of the offer account by account and week by week.\"\nformat:\n  html:\n    css: longbet.css\nshare:\n  permalink: \"https://book.martinez.fyi/longbet_encouragement.html\"\n  description: \"LongBet: randomized encouragement and adoption timing\"\n  linkedin: true\n  email: true\n  mastodon: true\n---\n\n::: {.callout-note title=\"Builds on the LongBet sequence\"}\nThis chapter uses the panel model of **[LongBet: Dynamic Treatment Effects in Staggered Rollouts](longbet.qmd)** and the decision framing of **[LongBet: From Effects to Decisions](longbet_decisions.qmd)**. It extends the [randomized encouragement design](iv.qmd) of the earlier instrumental-variables chapter to a panel, where adoption happens at different times and the benefit depends on how long the feature has been in use.\n:::\n\n## The Decision: Who Should Be Encouraged?\n\nA company cannot force enterprise accounts to adopt a workflow automation feature, but it can offer high-touch concierge onboarding to a random subset and watch what happens. That is a randomized encouragement design, and in a panel it acquires a time dimension: accounts adopt in different weeks, and the benefit compounds with the weeks the feature has been in use.\n\nA platform runs an onboarding pilot on 300 accounts over eight weeks. At week 4, a random half is offered concierge onboarding; the rest get standard documentation. Accounts choose whether and when to activate, and activation is permanent. The pilot is over, and the decision is forward-looking:\n\n> For the next cohort of 500 accounts, concierge onboarding costs \\$20 per account in specialist hours. The onboarding team can handle at most 80 accounts and the budget is \\$1,600. Which accounts should get the offer?\n\n### Target the effect of the offer, not the effect of adoption\n\nThe intervention being allocated is the **offer**, so the quantity the decision needs is the conditional effect of being offered onboarding on the outcome,\n\n$$\n\\mathrm{CITT}_Y(X, t) = \\mathbb{E}\\left[Y_{it}(Z_i = 1) - Y_{it}(Z_i = 0) \\mid X_i = X\\right],\n$$\n\nsummed over the weeks that matter and compared with the cost. The complier average causal effect, the ratio of the outcome effect to the adoption effect, answers a different question: what adoption does for the accounts it moves. It is the right quantity for pricing the feature and the wrong one for allocating the offer, for three reasons. The specialist hours are spent whenever the offer goes out, whether or not the account adopts. A segment can have a large complier effect and almost no compliance, so its expected lift per offer is small. And a ratio with a small denominator is heavy-tailed, so ranking on it puts the least compliant, least informative accounts at the top.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(longbet)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(tibble)\nlibrary(ggplot2)\nlibrary(purrr)\nlibrary(knitr)\n\nsource(\"R/longbet-common.R\")\nsource(\"R/longbet-sim.R\")\nsource(\"R/longbet-artifacts.R\")\nverify_longbet_environment()\ntheme_set(theme_minimal(base_size = 12))\n\ncost <- 20; capacity <- 80; budget <- 1600\nenc_budget <- c(lb_budget(12), list(random_seed = 123L))\n```\n:::\n\n\n## How the Model Works\n\n`longbet_encourage()` fits two LongBet equations and composes them. The exclusion restriction is written into the structure: the offer enters the outcome only through adoption.\n\n**The outcome, on the adoption clock.** With $S^D_{it}$ the weeks since account $i$ activated,\n\n$$\nY_{it} = \\mu_Y(X_i, t) + \\beta^{Y}_{S^D_{it}}\\, \\nu_Y(X_i, t)\\, \\mathbf{1}\\{S^D_{it} \\ge 1\\} + \\gamma^{Y}_i + \\epsilon^{Y}_{it}.\n$$\n\nThis is the model of the first chapter with **adoption** as the treatment, so the equation contains the jump that activation causes and how the benefit grows with exposure. Accounts in both arms contribute activation events, because control accounts adopt organically too.\n\n**Adoption, as a hazard on the offer clock.** With $S^Z_{it}$ the weeks since the offer, the probability of activating this week given that the account has not yet activated is\n\n$$\n\\lambda_{it} = \\Phi\\!\\Big(\\mu_D(X_i, t) + \\beta^{D}_{S^Z_{it}}\\, \\nu_D(X_i, t)\\, \\mathbf{1}\\{S^Z_{it} \\ge 1\\} + \\eta_i\\Big),\n$$\n\na binary LongBet on the first-activation indicator with cells after activation masked out. The account-level term $\\eta_i$ is a frailty: it carries unobserved differences in the propensity to adopt.\n\n**Composition.** Under an offer schedule, the hazard gives the probability of activating first in week $a$ and of having activated by week $t$. The offer's effects follow:\n\n$$\n\\mathrm{CITT}_Y(X_i, t) = \\sum_{a \\le t} \\big[\\pi_a(X_i, 1) - \\pi_a(X_i, 0)\\big]\\, \\tau_t(X_i, t - a + 1),\n\\qquad\n\\mathrm{CITT}_D(X_i, t) = P_t(X_i, 1) - P_t(X_i, 0),\n$$\n\nevaluated draw by draw, with the frailty integrated outside the survival product by Gauss-Hermite quadrature. That composition is what handles the awkward case a snapshot cannot: an account that would have adopted organically in week 7 and adopts in week 4 because of the offer has the same adoption status by week 8 in both arms, and four extra weeks of exposure. The adoption contrast at week 8 misses it entirely; the outcome effect does not.\n\n`predict_conditional()` returns, for any covariate profile and every week, posterior draws of both effects, the principal strata under monotonicity, the complier effect as a draw-wise ratio, the cumulative lift, the probability that the cumulative lift beats a cost, and a knapsack allocation under capacity and budget constraints.\n\n## A Pilot With a Known Answer\n\nThe simulation is built so the **expected** effect of the offer is available in closed form for every account and week, which is the right benchmark for an estimator of a conditional expectation.\n\nEach account has a weekly adoption hazard. Under control it is organic, and higher for accounts in a latent operational distress state that also lowers their baseline productivity, which is the confounder that makes naive regressions fail. Once offered, the hazard rises smoothly with technical readiness. The productivity benefit compounds with exposure, $\\tau_i(S) = \\tau_i\\log(1+S)$, and only accounts with **both** technical readiness and adequate team scale get a large coefficient. Accounts that are ready but small comply eagerly and gain little: they are the segment a compliance-driven ranking gets wrong.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data <- generate_encouragement_data(n = 300, seed = 2026)\ntest_data  <- generate_encouragement_data(n = 500, seed = 9999)\ntt <- train_data$tt; t_enc <- train_data$t_enc; t_grid <- seq_len(tt)\npost_weeks <- t_enc:tt; H <- length(post_weeks)\nstopifnot(all(train_data$d1 >= train_data$d0),\n          all(train_data$true_citt_y[, seq_len(t_enc - 1)] == 0))\nsegment_of <- function(dat) factor(\n  ifelse(dat$qualifying, \"Ready and scaled\",\n         ifelse(dat$x[, \"x1\"] > 0, \"Ready, small team\", \"Not ready\")),\n  levels = c(\"Ready and scaled\", \"Ready, small team\", \"Not ready\"))\ntest_segment <- segment_of(test_data)\ntrue_cum_test <- rowSums(test_data$true_citt_y[, post_weeks])\ntibble(Segment = test_segment, lift = true_cum_test,\n       comp = test_data$true_citt_d[, tt], prof = true_cum_test > cost) %>%\n  group_by(Segment) %>%\n  summarise(Accounts = n(), `Week-8 compliance` = mean(comp),\n            `Expected cumulative lift` = mean(lift), `Share worth encouraging` = mean(prof)) %>%\n  kable(digits = c(0, 0, 2, 1, 2),\n        caption = \"The future cohort. Compliance is the expected adoption contrast at week 8; an account is worth encouraging when its expected cumulative lift over weeks 4 to 8 exceeds the $20 cost.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: The future cohort. Compliance is the expected adoption contrast at week 8; an account is worth encouraging when its expected cumulative lift over weeks 4 to 8 exceeds the $20 cost.\n\n|Segment           | Accounts| Week-8 compliance| Expected cumulative lift| Share worth encouraging|\n|:-----------------|--------:|-----------------:|------------------------:|-----------------------:|\n|Ready and scaled  |      132|              0.41|                     24.1|                    0.96|\n|Ready, small team |       97|              0.41|                      3.6|                    0.00|\n|Not ready         |      271|              0.29|                      1.8|                    0.00|\n\n\n:::\n:::\n\n\nOnly the ready-and-scaled segment is worth encouraging at this cost, and the ready-but-small segment complies just as eagerly. With 127 profitable accounts and capacity for 80, the constraint binds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_encouragement(train_data$z, train_data$d, t_grid) + labs(title = NULL, x = \"Week\")\n```\n\n::: {.cell-output-display}\n![Adoption by assigned arm in the pilot. The offered arm jumps at week 4; the control arm keeps adopting organically, so the gap stops growing after week 5 while exposure keeps accumulating.](longbet_encouragement_files/figure-html/fig-adoption-1.png){#fig-adoption fig-alt='Two rising curves over eight weeks with a shaded gap between them that opens at week four and then holds roughly constant.' width=768}\n:::\n:::\n\n\n## Start With What Randomization Alone Identifies\n\nBefore any model, the package computes the assigned-arm contrasts: the outcome and adoption effects at each week with their standard errors. This needs no model and is the inference of record for the population effects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nref <- encouragement_effects(train_data$y, train_data$d, train_data$z, t_grid)\ntruth_train <- tibble(period = post_weeks,\n                      true_itt_y = colMeans(train_data$true_citt_y[, post_weeks]),\n                      true_itt_d = colMeans(train_data$true_citt_d[, post_weeks]))\n```\n:::\n\n\n## Fitting the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenc_run <- lb_artifact(\n  \"encouragement_fit\",\n  lb_key(\"encouragement\", enc_budget, digest::digest(list(train_data[c(\"y\", \"d\", \"z\", \"x\")], test_data$x))),\n  export = c(\"train_data\", \"test_data\", \"t_grid\", \"enc_budget\", \"cost\", \"capacity\", \"budget\", \"tt\", \"t_enc\"),\n  builder = function() {\n    fit <- longbet_encourage(y = train_data$y, d = train_data$d, z = train_data$z,\n                             x = train_data$x, t = t_grid, config = enc_budget)\n    pop <- predict(fit, min_ess = 400, max_rhat = 1.01)\n    cond_train <- predict_conditional(fit)\n    cond_test <- predict_conditional(fit, new_x = test_data$x, cost = cost,\n                                     capacity = capacity, budget = budget)\n    grid_seq <- seq(-2, 2, length.out = 25)\n    grid_x <- as.matrix(expand.grid(x1 = grid_seq, x2 = grid_seq, x3 = 0))\n    list(effects = pop$effects, diagnostics = pop$diagnostics, reference = pop$reference,\n         itt_draws = pop$draws$itt_y, strata = principal_strata(cond_train),\n         citt_y = cond_test$citt_y$mean, citt_d = cond_test$citt_d$mean,\n         cumulative = cond_test$cumulative_lift$mean, decision = cond_test$decision,\n         hurdle = knapsack_policy(cond_test, cost = cost, capacity = capacity,\n                                  budget = budget, hurdle = 0.8),\n         certainty = knapsack_policy(cond_test, cost = cost, capacity = capacity,\n                                     budget = budget, ranking_metric = \"certainty_adjusted\"),\n         grid_x = grid_x,\n         grid_effect = predict_conditional(fit, new_x = grid_x)$citt_y$mean[, tt - t_enc + 1])\n  })\n```\n:::\n\n\nThe fit uses four chains, 2,000 burn-in sweeps and 12,000 further sweeps per chain with every twelfth retained, for both equations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiag_tbl <- enc_run$diagnostics %>% filter(group == \"all\") %>%\n  mutate(Quantity = recode(quantity, itt_y = \"Effect on the outcome\", itt_d = \"Effect on adoption\",\n                           wald = \"Complier effect\")) %>%\n  select(Week = period, Quantity, `Bulk ESS` = ess_bulk, `Tail ESS` = ess_tail,\n         `Rank R-hat` = rhat, Passed = diagnostics_passed) %>%\n  arrange(Quantity, Week)\nkable(diag_tbl, digits = c(0, 0, 0, 0, 3, 0),\n      caption = \"Convergence diagnostics for exactly the quantities reported below.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Convergence diagnostics for exactly the quantities reported below.\n\n| Week|Quantity              | Bulk ESS| Tail ESS| Rank R-hat|Passed |\n|----:|:---------------------|--------:|--------:|----------:|:------|\n|    4|Complier effect       |     1600|     2920|      1.003|TRUE   |\n|    5|Complier effect       |     1403|     3202|      1.002|TRUE   |\n|    6|Complier effect       |     1809|     3378|      1.004|TRUE   |\n|    7|Complier effect       |     1682|     3188|      1.002|TRUE   |\n|    8|Complier effect       |     1666|     2983|      1.001|TRUE   |\n|    4|Effect on adoption    |     3344|     3286|      1.000|TRUE   |\n|    5|Effect on adoption    |     3184|     3895|      1.000|TRUE   |\n|    6|Effect on adoption    |     2850|     3884|      1.000|TRUE   |\n|    7|Effect on adoption    |     2813|     3643|      1.000|TRUE   |\n|    8|Effect on adoption    |     2866|     3701|      1.000|TRUE   |\n|    4|Effect on the outcome |     2246|     3507|      1.005|TRUE   |\n|    5|Effect on the outcome |     1585|     3226|      1.002|TRUE   |\n|    6|Effect on the outcome |     1957|     3698|      1.002|TRUE   |\n|    7|Effect on the outcome |     1993|     3486|      1.002|TRUE   |\n|    8|Effect on the outcome |     2182|     3328|      1.002|TRUE   |\n\n\n:::\n:::\n\n\n15 of 15 reported quantities pass both thresholds; the smallest bulk effective sample size is 1403 and the largest R-hat is 1.005.\n\nTwo features of this panel make it comfortable for the sampler, and they are worth recognising in your own data. The outcome equation sees the activation jump it is built to represent, so its residual is close to the noise the model assumes. And the adoption equation is a probit on the at-risk set with a few hundred events, which is a small, well-conditioned problem.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neff <- enc_run$effects %>% filter(group == \"all\", quantity %in% c(\"itt_y\", \"itt_d\")) %>%\n  select(period, quantity, posterior_mean, posterior_lower, posterior_upper)\nref_long <- ref %>% select(period, itt_y, itt_d, itt_y_se, itt_d_se) %>%\n  pivot_longer(c(itt_y, itt_d), names_to = \"quantity\", values_to = \"reference\") %>%\n  mutate(reference_se = ifelse(quantity == \"itt_y\", itt_y_se, itt_d_se)) %>%\n  select(period, quantity, reference, reference_se)\ntruth_long <- truth_train %>% transmute(period, itt_y = true_itt_y, itt_d = true_itt_d) %>%\n  pivot_longer(c(itt_y, itt_d), names_to = \"quantity\", values_to = \"truth\")\neff %>% left_join(ref_long, by = c(\"period\", \"quantity\")) %>%\n  left_join(truth_long, by = c(\"period\", \"quantity\")) %>%\n  mutate(quantity = factor(quantity, levels = c(\"itt_y\", \"itt_d\"),\n                           labels = c(\"Effect on the outcome\", \"Effect on adoption\"))) %>%\n  arrange(quantity, period) %>%\n  transmute(Quantity = quantity, Week = period, `Expected truth` = sprintf(\"%.3f\", truth),\n            `Design-based reference (SE)` = sprintf(\"%.3f (%.3f)\", reference, reference_se),\n            `Posterior mean` = sprintf(\"%.3f\", posterior_mean),\n            `95% interval` = sprintf(\"[%.3f, %.3f]\", posterior_lower, posterior_upper)) %>%\n  kable(caption = \"Population effects standardized over all pilot accounts: the model's posterior against the design-based reference and the expected truth.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Population effects standardized over all pilot accounts: the model's posterior against the design-based reference and the expected truth.\n\n|Quantity              | Week|Expected truth |Design-based reference (SE) |Posterior mean |95% interval   |\n|:---------------------|----:|:--------------|:---------------------------|:--------------|:--------------|\n|Effect on the outcome |    4|0.956          |1.479 (0.498)               |1.001          |[0.790, 1.220] |\n|Effect on the outcome |    5|1.671          |2.138 (0.553)               |1.676          |[1.375, 1.990] |\n|Effect on the outcome |    6|2.138          |2.165 (0.642)               |2.082          |[1.703, 2.465] |\n|Effect on the outcome |    7|2.436          |2.663 (0.688)               |2.322          |[1.892, 2.759] |\n|Effect on the outcome |    8|2.624          |2.842 (0.737)               |2.453          |[1.972, 2.956] |\n|Effect on adoption    |    4|0.291          |0.386 (0.054)               |0.338          |[0.277, 0.400] |\n|Effect on adoption    |    5|0.362          |0.444 (0.051)               |0.393          |[0.330, 0.457] |\n|Effect on adoption    |    6|0.374          |0.438 (0.048)               |0.402          |[0.334, 0.467] |\n|Effect on adoption    |    7|0.367          |0.455 (0.047)               |0.400          |[0.331, 0.467] |\n|Effect on adoption    |    8|0.353          |0.435 (0.046)               |0.388          |[0.319, 0.458] |\n\n\n:::\n:::\n\n\nThe posterior means track the reference, as they should, since both target the same finite population and randomization identifies both. Agreement here is the check that licenses everything below it, because what the model adds is not identification but resolution: the account-level surfaces the reference cannot produce.\n\n## Principal Strata Over Time\n\nIn a cross-section the compliance types are fixed. In a panel they drift: every week some control accounts adopt organically, so the always-taker share grows and the never-taker share shrinks, while the complier share rises as offered accounts activate and then erodes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntruth_strata <- tibble(\n  period = rep(post_weeks, each = 3),\n  stratum = rep(c(\"complier\", \"always_taker\", \"never_taker\"), H),\n  true_count = as.vector(rbind(colSums(train_data$d1[, post_weeks] - train_data$d0[, post_weeks]),\n                               colSums(train_data$d0[, post_weeks]),\n                               colSums(1 - train_data$d1[, post_weeks]))))\ncomp_df <- enc_run$strata %>% inner_join(truth_strata, by = c(\"period\", \"stratum\")) %>%\n  mutate(covered = true_count >= count_lower & true_count <= count_upper,\n         stratum_label = factor(stratum, levels = c(\"complier\", \"always_taker\", \"never_taker\"),\n                                labels = c(\"Complier\", \"Always-taker\", \"Never-taker\")))\nggplot(comp_df, aes(x = period)) +\n  geom_ribbon(aes(ymin = count_lower, ymax = count_upper, fill = stratum_label), alpha = 0.25) +\n  geom_line(aes(y = count_mean, color = stratum_label, linetype = \"Posterior mean\"), linewidth = 1.1) +\n  geom_line(aes(y = true_count, color = stratum_label, linetype = \"Realized truth\"), linewidth = 1.1) +\n  facet_wrap(~ stratum_label, scales = \"free_y\") +\n  scale_color_manual(values = c(\"Complier\" = \"#2166ac\", \"Always-taker\" = \"#4daf4a\", \"Never-taker\" = \"#b2182b\")) +\n  scale_fill_manual(values = c(\"Complier\" = \"#2166ac\", \"Always-taker\" = \"#4daf4a\", \"Never-taker\" = \"#b2182b\")) +\n  scale_linetype_manual(values = c(\"Posterior mean\" = \"solid\", \"Realized truth\" = \"dashed\")) +\n  labs(x = \"Week\", y = \"Accounts (of 300)\", color = \"Stratum\", fill = \"Stratum\", linetype = NULL) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Principal strata over the post-encouragement weeks: posterior means with 95% intervals against the pilot's realized counts.](longbet_encouragement_files/figure-html/fig-strata-1.png){#fig-strata fig-alt='Three panels for compliers, always-takers and never-takers. Always-takers rise across weeks four to eight, never-takers fall, compliers stay roughly flat, and the posterior bands cover the realized counts.' width=960}\n:::\n:::\n\n\n15 of 15 realized counts fall inside the 95% posterior intervals. These counts rest on monotonicity, that the offer never delays adoption, and on the hazard model; they are model-based quantities, unlike the population effects above.\n\n## Why a Single Coefficient on Adoption Misleads\n\nAnalysts often skip the instrument and regress the outcome on adoption status. In this panel that goes wrong twice over.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npanel_df <- tibble(unit = rep(seq_len(train_data$n), each = tt), time = rep(t_grid, train_data$n),\n                   y = as.vector(t(train_data$y)), d = as.vector(t(train_data$d)),\n                   x1 = rep(train_data$x[, \"x1\"], each = tt), x2 = rep(train_data$x[, \"x2\"], each = tt))\nadopter_cells <- train_data$d == 1\ntibble(Quantity = c(\"Pooled OLS coefficient on adoption\",\n                    \"Two-way fixed effects coefficient on adoption\",\n                    \"Average realized effect in adopter-weeks\",\n                    \"Average realized effect in adopter-weeks, ready and scaled\"),\n       Value = c(coef(lm(y ~ d + x1 + x2 + factor(time), data = panel_df))[\"d\"],\n                 coef(lm(y ~ d + factor(unit) + factor(time), data = panel_df))[\"d\"],\n                 mean((train_data$tau_base * log1p(train_data$s))[adopter_cells]),\n                 mean((train_data$tau_base * log1p(train_data$s))[adopter_cells & train_data$qualifying]))) %>%\n  kable(digits = 2, caption = \"Regression coefficients on adoption status against the effect actually experienced in adopter-weeks.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Regression coefficients on adoption status against the effect actually experienced in adopter-weeks.\n\n|Quantity                                                   | Value|\n|:----------------------------------------------------------|-----:|\n|Pooled OLS coefficient on adoption                         |  3.09|\n|Two-way fixed effects coefficient on adoption              |  3.53|\n|Average realized effect in adopter-weeks                   |  5.34|\n|Average realized effect in adopter-weeks, ready and scaled | 11.28|\n\n\n:::\n:::\n\n\nThe first regression is confounded: distressed accounts adopt organically at four times the rate of healthy ones and have lower baseline productivity, so part of that gap is charged to adoption. The second removes the confounding with unit fixed effects and still answers the wrong question, because a single coefficient stands in for an effect that depends on how long the feature has been in use and on which segment the account is in.\n\nThe adoption-clock model's outcome equation is the flexible version of the second regression: unit intercepts, an exposure trajectory instead of one coefficient, and a forest for heterogeneity. What turns it into a statement about the **offer** is the adoption equation, which randomization identifies, and the composition of the two.\n\n## The Horse Race\n\nEvery method below is trained on the pilot and asked for the effect of the offer on each of the 500 future accounts, at each post-encouragement week. Two routes reach that target: estimate the effect of the offer on the outcome directly, or estimate a complier effect and multiply it by an estimated adoption contrast. Both are represented, and the generalized random forests of @athey2019grf are the strongest general-purpose competitors available.\n\n| Estimator | Route | Uses the panel structure? |\n|---|---|---|\n| **LongBet adoption-clock model** | Composition: outcome on the adoption clock, adoption hazard on the offer clock | Yes: unit intercepts, exposure trajectory |\n| **Instrumental forest x first-stage causal forest**, pooled with account clusters | Complier effect times adoption contrast | Partly: clustered, no unit intercepts |\n| **Causal forest on the offer**, pooled with a week covariate and account clusters | Direct | Partly |\n| **Causal forest on the offer**, one forest per week | Direct | No |\n| **Two-stage least squares**, per week, with covariate interactions in both stages | Complier effect times adoption contrast | No |\n| **Linear regression of the outcome on the offer**, per week | Direct | No |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(grf)\ngrf_trees <- 2000; grf_threads <- 4L\nlong_post <- function(dat) {\n  idx <- expand.grid(t = post_weeks, i = seq_len(dat$n))\n  cells <- cbind(idx$i, idx$t)\n  data.frame(i = idx$i, t = idx$t, y = dat$y[cells], d = dat$d[cells],\n             z = dat$z_u[idx$i], dat$x[idx$i, , drop = FALSE])\n}\ntr_long <- long_post(train_data); te_long <- long_post(test_data)\nX_tr <- as.matrix(cbind(tr_long[, c(\"x1\", \"x2\", \"x3\")], week = tr_long$t))\nX_te <- as.matrix(cbind(te_long[, c(\"x1\", \"x2\", \"x3\")], week = te_long$t))\nto_matrix <- function(v) matrix(v, test_data$n, H, byrow = TRUE)\n\n# Per-week linear baselines: the intent-to-treat regression and two-stage least squares.\npred_ols <- pred_2sls <- pred_2sls_d <- matrix(0, test_data$n, H); lin_fits <- vector(\"list\", H)\nfor (h in seq_len(H)) {\n  t_h <- post_weeks[h]\n  df <- data.frame(y = train_data$y[, t_h], d = train_data$d[, t_h], z = train_data$z_u, train_data$x)\n  m_itt <- lm(y ~ z * (x1 + x2 + x3), data = df)\n  pred_ols[, h] <- predict(m_itt, data.frame(z = 1, test_data$x)) -\n    predict(m_itt, data.frame(z = 0, test_data$x))\n  s1 <- lm(d ~ z * (x1 + x2 + x3), data = df); df$d_hat <- fitted(s1)\n  s2 <- lm(y ~ d_hat * (x1 + x2 + x3), data = df)\n  dh1 <- predict(s1, data.frame(z = 1, test_data$x)); dh0 <- predict(s1, data.frame(z = 0, test_data$x))\n  pred_2sls_d[, h] <- dh1 - dh0\n  pred_2sls[, h] <- predict(s2, data.frame(d_hat = dh1, test_data$x)) -\n    predict(s2, data.frame(d_hat = dh0, test_data$x))\n  lin_fits[[h]] <- list(s1 = s1, s2 = s2)\n}\n\n# Causal forest on the randomized offer, one forest per week.\npred_cf_week <- matrix(0, test_data$n, H)\nfor (h in seq_len(H)) {\n  cf <- causal_forest(train_data$x, train_data$y[, post_weeks[h]], W = train_data$z_u,\n                      W.hat = rep(0.5, train_data$n), num.trees = grf_trees, seed = 1,\n                      num.threads = grf_threads)\n  pred_cf_week[, h] <- predict(cf, test_data$x)$predictions\n}\n# Causal forest pooled over weeks, with a week covariate and account clusters.\ncf_pool <- causal_forest(X_tr, tr_long$y, W = tr_long$z, W.hat = rep(0.5, nrow(X_tr)),\n                         clusters = tr_long$i, num.trees = grf_trees, seed = 1, num.threads = grf_threads)\npred_cf_pool <- to_matrix(predict(cf_pool, X_te)$predictions)\n# Instrumental forest for the complier effect, times a first-stage causal forest on adoption.\nivf_pool <- instrumental_forest(X_tr, tr_long$y, W = tr_long$d, Z = tr_long$z,\n                                Z.hat = rep(0.5, nrow(X_tr)), clusters = tr_long$i,\n                                num.trees = grf_trees, seed = 1, num.threads = grf_threads)\ncf_d_pool <- causal_forest(X_tr, tr_long$d, W = tr_long$z, W.hat = rep(0.5, nrow(X_tr)),\n                           clusters = tr_long$i, num.trees = grf_trees, seed = 1, num.threads = grf_threads)\npred_grf_d <- pmax(0, to_matrix(predict(cf_d_pool, X_te)$predictions))\npred_ivf <- to_matrix(predict(ivf_pool, X_te)$predictions) * pred_grf_d\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntruth_y <- test_data$true_citt_y[, post_weeks]\ntruth_d <- test_data$true_citt_d[, post_weeks]\nrmse <- function(a, b) sqrt(mean((a - b)^2))\nroughness <- function(p) mean((p[, 3:H] - 2 * p[, 2:(H - 1)] + p[, 1:(H - 2)])^2)\nestimators <- list(\n  \"LongBet adoption-clock model\" = list(y = enc_run$citt_y, d = enc_run$citt_d, route = \"Composition\"),\n  \"Instrumental forest x first stage\" = list(y = pred_ivf, d = pred_grf_d, route = \"Ratio x first stage\"),\n  \"Causal forest, pooled\" = list(y = pred_cf_pool, d = NULL, route = \"Direct\"),\n  \"Causal forest, per week\" = list(y = pred_cf_week, d = NULL, route = \"Direct\"),\n  \"Two-stage least squares, per week\" = list(y = pred_2sls, d = pred_2sls_d, route = \"Ratio x first stage\"),\n  \"Linear regression on the offer, per week\" = list(y = pred_ols, d = NULL, route = \"Direct\"))\nperf_table <- imap_dfr(estimators, function(e, nm)\n  tibble(Estimator = nm, Route = e$route, `RMSE, weekly effect` = rmse(e$y, truth_y),\n         `RMSE, cumulative lift` = rmse(rowSums(e$y), rowSums(truth_y)),\n         `RMSE, adoption contrast` = if (is.null(e$d)) NA_real_ else rmse(e$d, truth_d),\n         Roughness = roughness(e$y))) %>% arrange(`RMSE, weekly effect`)\nkable(perf_table, digits = c(0, 0, 3, 2, 3, 3),\n      caption = \"Out-of-sample accuracy on the 500 future accounts against the expected truth. Roughness is the mean squared second difference of each account's predicted weekly trajectory: a jagged trajectory is one the model is inventing week by week.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Out-of-sample accuracy on the 500 future accounts against the expected truth. Roughness is the mean squared second difference of each account's predicted weekly trajectory: a jagged trajectory is one the model is inventing week by week.\n\n|Estimator                                |Route               | RMSE, weekly effect| RMSE, cumulative lift| RMSE, adoption contrast| Roughness|\n|:----------------------------------------|:-------------------|-------------------:|---------------------:|-----------------------:|---------:|\n|LongBet adoption-clock model             |Composition         |               0.301|                  1.36|                   0.084|     0.065|\n|Instrumental forest x first stage        |Ratio x first stage |               1.207|                  5.15|                   0.152|     0.003|\n|Causal forest, per week                  |Direct              |               1.299|                  5.98|                      NA|     0.577|\n|Causal forest, pooled                    |Direct              |               1.300|                  5.49|                      NA|     0.002|\n|Linear regression on the offer, per week |Direct              |               1.574|                  7.30|                      NA|     1.459|\n|Two-stage least squares, per week        |Ratio x first stage |               1.703|                  7.81|                   0.121|     1.518|\n\n\n:::\n:::\n\n\nThree patterns matter more than the ranking.\n\n**Linear models cannot represent this target.** The true surface is a step in two covariates, so a plane through it overstates the ready-but-small segment and understates the ready-and-scaled one, which is precisely where the money is.\n\n**Modelling the adoption jump is what the panel structure buys.** The forests see each account-week as an observation with covariates; the adoption-clock model knows that an account's outcome jumped when it activated and has been compounding since. That is why it is the only estimator that follows the compounding trajectory in the ready-and-scaled segment. The roughness column shows the other half of the story: anything fitted week by week has to rediscover the shape from noise at every horizon, while the pooled forests are smooth only because they barely move across weeks at all.\n\n**The ratio route pays for a noisy denominator.** The instrumental forest's complier effect times its first stage lands close to the direct route, but dividing by a small adoption contrast is what makes a ratio heavy-tailed, which is the statistical version of the argument at the top of this chapter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntraj_df <- bind_rows(\n  tibble(Estimator = \"Expected truth\", Segment = test_segment, as.data.frame(truth_y)) %>%\n    pivot_longer(-c(Estimator, Segment), names_to = \"h\", values_to = \"effect\"),\n  imap_dfr(estimators, function(e, nm) {\n    m <- e$y; colnames(m) <- colnames(as.data.frame(truth_y))\n    tibble(Estimator = nm, Segment = test_segment, as.data.frame(m)) %>%\n      pivot_longer(-c(Estimator, Segment), names_to = \"h\", values_to = \"effect\")\n  })) %>%\n  mutate(Week = post_weeks[as.integer(factor(h, levels = unique(h)))]) %>%\n  group_by(Estimator, Segment, Week) %>% summarise(effect = mean(effect), .groups = \"drop\")\nggplot(traj_df, aes(x = Week, y = effect, color = Estimator,\n                    linetype = Estimator == \"Expected truth\")) +\n  geom_line(aes(linewidth = Estimator == \"Expected truth\")) +\n  facet_wrap(~ Segment) +\n  scale_linetype_manual(values = c(`TRUE` = \"solid\", `FALSE` = \"longdash\"), guide = \"none\") +\n  scale_linewidth_manual(values = c(`TRUE` = 1.6, `FALSE` = 0.8), guide = \"none\") +\n  labs(y = \"Mean effect of the offer\", x = \"Week\") +\n  theme(legend.position = \"bottom\") + guides(color = guide_legend(nrow = 3))\n```\n\n::: {.cell-output-display}\n![Average predicted effect of the offer by week and true segment. Only the ready-and-scaled segment has a large compounding effect; the ready-but-small segment complies eagerly and gains little.](longbet_encouragement_files/figure-html/fig-trajectories-1.png){#fig-trajectories fig-alt='Three panels, one per segment. In the ready-and-scaled panel the truth rises steeply and only the adoption-clock model follows it; every other estimator flattens out well below. In the other two panels the truth stays near zero, the adoption-clock model tracks it, and the rest sit above it.' width=1056}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid_x <- enc_run$grid_x\ngrid_truth <- onboarding_structure(grid_x, tt, t_enc)$truth$citt_y[, tt]\ns1_T <- lin_fits[[H]]$s1; s2_T <- lin_fits[[H]]$s2\ngrid_df <- as.data.frame(grid_x)\ndh1 <- predict(s1_T, data.frame(z = 1, grid_df)); dh0 <- predict(s1_T, data.frame(z = 0, grid_df))\ngrid_lin <- predict(s2_T, data.frame(d_hat = dh1, grid_df)) -\n  predict(s2_T, data.frame(d_hat = dh0, grid_df))\ngrid_cf <- predict(cf_pool, cbind(grid_x, week = tt))$predictions\nbind_rows(tibble(grid_df, effect = grid_truth, Source = \"1. Expected truth\"),\n          tibble(grid_df, effect = grid_lin, Source = \"2. Two-stage least squares\"),\n          tibble(grid_df, effect = grid_cf, Source = \"3. Causal forest, pooled\"),\n          tibble(grid_df, effect = enc_run$grid_effect, Source = \"4. LongBet adoption-clock model\")) %>%\n  ggplot(aes(x = x1, y = x2, fill = effect)) +\n  geom_tile() +\n  scale_fill_viridis_c(option = \"magma\") +\n  facet_wrap(~ Source, nrow = 1) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"white\", alpha = 0.7) +\n  geom_hline(yintercept = -0.2, linetype = \"dashed\", color = \"white\", alpha = 0.7) +\n  labs(x = \"Technical readiness\", y = \"Team scale\", fill = \"Week-8 effect\")\n```\n\n::: {.cell-output-display}\n![Week-8 effect of the offer over technical readiness and team scale, with the third covariate at zero: the expected truth, the linear plane, the pooled causal forest, and the adoption-clock model. Dashed lines mark the true thresholds.](longbet_encouragement_files/figure-html/fig-surface-1.png){#fig-surface fig-alt='Four heat maps. The truth is a bright rectangle in the upper right quadrant. The linear panel is a diagonal gradient. The two flexible panels reproduce the rectangle, the forest with softer edges.' width=1056}\n:::\n:::\n\n\nThe linear plane tilts toward readiness, because compliance and benefit both rise with it, and cannot express that the benefit also needs scale. Both flexible estimators find the region; the forest's edges are softer, and its uncertainty comes as confidence intervals per account rather than as draws of the whole trajectory, which is what the allocation below consumes.\n\n## From Posteriors to an Allocation\n\nThe decision is a knapsack: at most 80 accounts, a budget of \\$1,600, and \\$20 per offer. `predict_conditional()` was called with those constraints, so the allocation is already in the fitted object. Two variants use the posterior more aggressively: require a breakeven probability of at least 0.8 before an account is eligible, or rank by expected net value divided by its posterior standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrue_margin <- true_cum_test - cost\nselect_top <- function(score, k = capacity) {\n  sel <- rep(FALSE, length(score)); n_pos <- sum(score > 0)\n  if (n_pos > 0) sel[order(score, decreasing = TRUE)[seq_len(min(k, n_pos))]] <- TRUE\n  sel\n}\npolicies <- list(\n  \"Oracle: knows the expected lift\" = select_top(true_margin),\n  \"LongBet: expected net value\" = enc_run$decision,\n  \"LongBet: breakeven probability >= 0.8\" = enc_run$hurdle,\n  \"LongBet: certainty-adjusted ranking\" = enc_run$certainty,\n  \"Instrumental forest x first stage\" = select_top(rowSums(pred_ivf) - cost),\n  \"Causal forest, pooled\" = select_top(rowSums(pred_cf_pool) - cost),\n  \"Two-stage least squares, per week\" = select_top(rowSums(pred_2sls) - cost),\n  \"Blanket: first 80 accounts in the file\" = seq_len(test_data$n) <= capacity)\noracle_profit <- sum(true_margin[policies[[1]]])\npolicy_table <- imap_dfr(policies, function(sel, nm)\n  tibble(Policy = nm, Encouraged = sum(sel), Profit = sum(true_margin[sel]),\n         Capture = 100 * sum(true_margin[sel]) / oracle_profit,\n         Precision = if (sum(sel) > 0) 100 * mean(true_margin[sel] > 0) else NA_real_))\nkable(policy_table, digits = c(0, 0, 0, 1, 1),\n      col.names = c(\"Policy\", \"Accounts encouraged\", \"Expected net profit ($)\",\n                    \"Oracle capture (%)\", \"Selections that are profitable (%)\"),\n      caption = \"Allocation value on the future cohort under the capacity and budget constraints, scored against the expected truth.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Allocation value on the future cohort under the capacity and budget constraints, scored against the expected truth.\n\n|Policy                                 | Accounts encouraged| Expected net profit ($)| Oracle capture (%)| Selections that are profitable (%)|\n|:--------------------------------------|-------------------:|-----------------------:|------------------:|----------------------------------:|\n|Oracle: knows the expected lift        |                  80|                     448|              100.0|                              100.0|\n|LongBet: expected net value            |                  80|                     420|               93.7|                              100.0|\n|LongBet: breakeven probability >= 0.8  |                  41|                     219|               48.8|                              100.0|\n|LongBet: certainty-adjusted ranking    |                  80|                     409|               91.2|                              100.0|\n|Instrumental forest x first stage      |                  49|                     317|               70.8|                              100.0|\n|Causal forest, pooled                  |                  52|                     329|               73.5|                              100.0|\n|Two-stage least squares, per week      |                  64|                     204|               45.4|                               87.5|\n|Blanket: first 80 accounts in the file |                  80|                    -959|             -214.2|                               25.0|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_dfr(seq(10, 50, by = 5), function(c_val) {\n  margin <- true_cum_test - c_val\n  scores <- list(\"Oracle\" = margin, \"LongBet adoption-clock model\" = enc_run$cumulative - c_val,\n                 \"Causal forest, pooled\" = rowSums(pred_cf_pool) - c_val,\n                 \"Two-stage least squares, per week\" = rowSums(pred_2sls) - c_val)\n  bind_rows(imap_dfr(scores, function(sc, nm) tibble(Policy = nm, Profit = sum(margin[select_top(sc)]))),\n            tibble(Policy = \"Blanket: first 80 accounts\",\n                   Profit = sum(margin[seq_len(test_data$n) <= capacity]))) %>%\n    mutate(Cost = c_val)\n}) %>%\n  ggplot(aes(x = Cost, y = Profit, color = Policy)) +\n  geom_line(linewidth = 1.1) + geom_point(size = 2) +\n  geom_hline(yintercept = 0, color = \"grey50\", linetype = \"dotted\") +\n  labs(x = \"Cost per encouraged account ($)\", y = \"Expected net profit ($)\") +\n  theme(legend.position = \"bottom\") + guides(color = guide_legend(nrow = 2))\n```\n\n::: {.cell-output-display}\n![Expected net profit of each rule as the per-offer cost varies, with capacity fixed. Every rule re-optimizes at each cost.](longbet_encouragement_files/figure-html/fig-cost-curves-1.png){#fig-cost-curves fig-alt='Lines declining with cost. The oracle is highest, the model tracks it closely, the linear rule sits lower, and the blanket rule is negative throughout.' width=864}\n:::\n:::\n\n\n## When the Nudge Can Hurt\n\nThe pilot above had a non-negative effect everywhere, so the only risk was a wasted offer. Product nudges are often riskier. Consider a capability that helps users with the right workflow and hurts everyone else: an automated rebalancing tool, or an auto-merge engine. The team decides whom to nudge; users decide whether to adopt.\n\nTwo features make snapshots dangerous here. For the first two weeks after adoption the effect is near zero for everyone, because users are still configuring. From the third week it grows in opposite directions depending on workflow fit. And compliance is unrelated to fit, so the most compliant users include many who would be harmed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_nudge <- generate_nudge_data(n = 300, seed = 2026)\ntest_nudge  <- generate_nudge_data(n = 500, seed = 9999)\nt_nudge <- train_nudge$t_nudge; post_nudge <- t_nudge:tt; H2 <- length(post_nudge)\nnudge_cost <- 10; nudge_capacity <- 40\ntibble(Stratum = c(\"Compliers at week 8\", \"  of which benefit\", \"  of which are harmed if they adopt\",\n                   \"Always-takers at week 8\", \"Never-takers at week 8\"),\n       Accounts = c(sum(train_nudge$complier_T),\n                    sum(train_nudge$complier_T & train_nudge$beneficiary),\n                    sum(train_nudge$complier_T & !train_nudge$beneficiary),\n                    sum(train_nudge$always_T), sum(train_nudge$never_T))) %>%\n  mutate(Share = sprintf(\"%.1f%%\", 100 * Accounts / train_nudge$n)) %>%\n  kable(caption = \"Realized principal strata at week 8 in the nudge pilot.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Realized principal strata at week 8 in the nudge pilot.\n\n|Stratum                           | Accounts|Share |\n|:---------------------------------|--------:|:-----|\n|Compliers at week 8               |      189|63.0% |\n|of which benefit                  |       55|18.3% |\n|of which are harmed if they adopt |      134|44.7% |\n|Always-takers at week 8           |       95|31.7% |\n|Never-takers at week 8            |       16|5.3%  |\n\n\n:::\n:::\n\n\nMost compliers are **not** beneficiaries: nudging them would work, in the sense that they adopt, and harm them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnudge_run <- lb_artifact(\n  \"nudge_fit\",\n  lb_key(\"nudge\", enc_budget, digest::digest(list(train_nudge[c(\"y\", \"d\", \"z\", \"x\")], test_nudge$x))),\n  export = c(\"train_nudge\", \"test_nudge\", \"t_grid\", \"enc_budget\", \"nudge_cost\", \"nudge_capacity\", \"H2\"),\n  builder = function() {\n    fit <- longbet_encourage(y = train_nudge$y, d = train_nudge$d, z = train_nudge$z,\n                             x = train_nudge$x, t = t_grid, config = enc_budget)\n    pop <- predict(fit, min_ess = 400, max_rhat = 1.01)\n    cond <- predict_conditional(fit, new_x = test_nudge$x, cost = nudge_cost, capacity = nudge_capacity)\n    list(diagnostics = pop$diagnostics, citt_y = cond$citt_y$mean,\n         cumulative = cond$cumulative_lift$mean, decision = cond$decision,\n         prob_regret = rowMeans(cond$citt_y$draws[, H2, ] < 0))\n  })\ndiag_nudge <- nudge_run$diagnostics %>% filter(group == \"all\")\nprob_regret <- nudge_run$prob_regret\ntruth_nudge <- test_nudge$true_citt_y[, post_nudge]\n```\n:::\n\n\nThe **regret probability** is the line that matters: for each user, the posterior probability that the week-8 effect of the nudge is negative. It is one line on the draws, and it is the input to a policy that a point estimate cannot support.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrue_cum_nudge <- rowSums(test_nudge$true_citt_y[, post_nudge])\nmargin_nudge <- true_cum_nudge - nudge_cost\nselect_top_nudge <- function(score, k = nudge_capacity) {\n  sel <- rep(FALSE, length(score)); n_pos <- sum(score > 0)\n  if (n_pos > 0) sel[order(score, decreasing = TRUE)[seq_len(min(k, n_pos))]] <- TRUE\n  sel\n}\ntr2 <- with(train_nudge, {\n  idx <- expand.grid(t = post_nudge, i = seq_len(n)); cells <- cbind(idx$i, idx$t)\n  data.frame(i = idx$i, t = idx$t, y = y[cells], z = z_u[idx$i], x[idx$i, ])\n})\nte2 <- with(test_nudge, {\n  idx <- expand.grid(t = post_nudge, i = seq_len(n)); data.frame(i = idx$i, t = idx$t, x[idx$i, ])\n})\ncf_nudge <- causal_forest(as.matrix(cbind(tr2[, c(\"x1\", \"x2\", \"x3\")], week = tr2$t)), tr2$y,\n                          W = tr2$z, W.hat = rep(0.5, nrow(tr2)), clusters = tr2$i,\n                          num.trees = grf_trees, seed = 1, num.threads = grf_threads)\npred_cf_nudge <- matrix(predict(cf_nudge, as.matrix(cbind(te2[, c(\"x1\", \"x2\", \"x3\")], week = te2$t)))$predictions,\n                        test_nudge$n, H2, byrow = TRUE)\npred_2sls_nudge <- matrix(0, test_nudge$n, H2)\nfor (h in seq_len(H2)) {\n  t_h <- post_nudge[h]\n  df <- data.frame(y = train_nudge$y[, t_h], d = train_nudge$d[, t_h], z = train_nudge$z_u, train_nudge$x)\n  s1 <- lm(d ~ z * (x1 + x2 + x3), data = df); df$d_hat <- fitted(s1)\n  s2 <- lm(y ~ d_hat * (x1 + x2 + x3), data = df)\n  dh1 <- predict(s1, data.frame(z = 1, test_nudge$x)); dh0 <- predict(s1, data.frame(z = 0, test_nudge$x))\n  pred_2sls_nudge[, h] <- predict(s2, data.frame(d_hat = dh1, test_nudge$x)) -\n    predict(s2, data.frame(d_hat = dh0, test_nudge$x))\n}\nprotected_score <- (nudge_run$cumulative - nudge_cost) * (prob_regret <= 0.2)\nnudge_policies <- list(\n  \"Oracle: knows the expected lift\" = select_top_nudge(margin_nudge),\n  \"LongBet: risk-neutral\" = nudge_run$decision,\n  \"LongBet: regret-protected\" = select_top_nudge(protected_score),\n  \"Causal forest, pooled\" = select_top_nudge(rowSums(pred_cf_nudge) - nudge_cost),\n  \"Two-stage least squares, all weeks\" = select_top_nudge(rowSums(pred_2sls_nudge) - nudge_cost),\n  \"End-line snapshot 2SLS (week 8)\" = select_top_nudge(H2 * pred_2sls_nudge[, H2] - nudge_cost),\n  \"Early-window snapshot 2SLS (week 4)\" = select_top_nudge(H2 * pred_2sls_nudge[, 4 - t_nudge + 1] - nudge_cost),\n  \"Blanket: first 40 users in the file\" = seq_len(test_nudge$n) <= nudge_capacity)\nnudge_oracle <- sum(margin_nudge[nudge_policies[[1]]])\nnudge_table <- imap_dfr(nudge_policies, function(sel, nm) {\n  regret <- sum(sel & test_nudge$complier_T & !test_nudge$beneficiary)\n  tibble(Policy = nm, Nudged = sum(sel), Profit = sum(margin_nudge[sel]),\n         Capture = 100 * sum(margin_nudge[sel]) / nudge_oracle,\n         Beneficiaries = sum(sel & test_nudge$beneficiary), Regret = regret,\n         Wasted = sum(sel & (test_nudge$always_T | test_nudge$never_T)))\n})\nkable(nudge_table, digits = c(0, 0, 0, 1, 0, 0, 0),\n      col.names = c(\"Policy\", \"Nudged\", \"Expected net profit ($)\", \"Oracle capture (%)\",\n                    \"Beneficiaries\", \"Regret cases\", \"Wasted nudges\"),\n      caption = \"Nudge allocation on the future cohort: value, targeting, and customer harm by policy. A regret case is a user who adopts because of the nudge and is harmed by it.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Nudge allocation on the future cohort: value, targeting, and customer harm by policy. A regret case is a user who adopts because of the nudge and is harmed by it.\n\n|Policy                              | Nudged| Expected net profit ($)| Oracle capture (%)| Beneficiaries| Regret cases| Wasted nudges|\n|:-----------------------------------|------:|-----------------------:|------------------:|-------------:|------------:|-------------:|\n|Oracle: knows the expected lift     |     40|                     667|              100.0|            40|            0|            11|\n|LongBet: risk-neutral               |     40|                     646|               96.8|            40|            0|            13|\n|LongBet: regret-protected           |     40|                     646|               96.8|            40|            0|            13|\n|Causal forest, pooled               |     40|                     425|               63.7|            40|            0|            26|\n|Two-stage least squares, all weeks  |     40|                     150|               22.4|            36|            3|            26|\n|End-line snapshot 2SLS (week 8)     |     40|                     196|               29.3|            37|            2|            25|\n|Early-window snapshot 2SLS (week 4) |      0|                       0|                0.0|             0|            0|             0|\n|Blanket: first 40 users in the file |     40|                    -689|             -103.3|             9|           18|            20|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbene <- test_nudge$complier_T & test_nudge$beneficiary\nharm <- test_nudge$complier_T & !test_nudge$beneficiary\np_left <- bind_rows(\n  tibble(Week = post_nudge, Source = \"Expected truth\", Segment = \"Benefits\", effect = colMeans(truth_nudge[bene, ])),\n  tibble(Week = post_nudge, Source = \"Expected truth\", Segment = \"Harmed\", effect = colMeans(truth_nudge[harm, ])),\n  tibble(Week = post_nudge, Source = \"Posterior mean\", Segment = \"Benefits\", effect = colMeans(nudge_run$citt_y[bene, ])),\n  tibble(Week = post_nudge, Source = \"Posterior mean\", Segment = \"Harmed\", effect = colMeans(nudge_run$citt_y[harm, ]))) %>%\n  ggplot(aes(x = Week, y = effect, color = Segment, linetype = Source)) +\n  geom_hline(yintercept = 0, color = \"grey50\", linetype = \"dotted\") +\n  geom_line(linewidth = 1.2) + geom_point(size = 2.3) +\n  scale_color_manual(values = c(\"Benefits\" = \"#2166ac\", \"Harmed\" = \"#b2182b\")) +\n  scale_linetype_manual(values = c(\"Expected truth\" = \"dashed\", \"Posterior mean\" = \"solid\")) +\n  labs(y = \"Effect of the nudge\", x = \"Week\", linetype = NULL) + theme(legend.position = \"bottom\")\np_right <- tibble(prob = prob_regret,\n                  Group = ifelse(test_nudge$beneficiary, \"Benefits\", \"Harmed if adopting\")) %>%\n  ggplot(aes(x = prob, fill = Group)) +\n  geom_histogram(bins = 25, position = \"identity\", alpha = 0.6) +\n  geom_vline(xintercept = 0.2, linetype = \"dashed\") +\n  scale_fill_manual(values = c(\"Benefits\" = \"#2166ac\", \"Harmed if adopting\" = \"#b2182b\")) +\n  labs(x = \"Posterior probability that the week-8 effect is negative\", y = \"Users\", fill = NULL) +\n  theme(legend.position = \"bottom\")\npatchwork::wrap_plots(p_left, p_right, nrow = 1)\n```\n\n::: {.cell-output-display}\n![Left: expected effect of the nudge by week for compliers who benefit and compliers who are harmed, truth against posterior mean. Right: the posterior probability that the week-8 effect is negative, by true group, with the regret filter's threshold.](longbet_encouragement_files/figure-html/fig-nudge-1.png){#fig-nudge fig-alt='Two panels. On the left, two pairs of lines diverge after week four, one upward and one downward, with posterior means following the dashed truths. On the right, two histograms separate near zero and one, with a dashed line at 0.2.' width=1056}\n:::\n:::\n\n\nThree lessons come out of this example, and they generalise well beyond the simulation.\n\n- **Snapshots fail in opposite directions.** The early window sees nothing, because the effect has not started, and would have shelved the feature. The end-line snapshot sees the largest gap and, extrapolated over the horizon, overstates it. The trajectory is the object to model.\n- **Compliance is not benefit.** Ranking on the first stage, or on a constant complier effect times the first stage, sends nudges to the most compliant users, many of whom are harmed. The effect of the offer on the outcome is what protects them.\n- **A posterior can price harm.** The regret filter is one line on the draws. Here it changes nothing, because the model is confident about the sign for every user it would select; it binds on cohorts the model is unsure about, which is where a point estimate would have sent the nudge anyway.\n\n## A Practitioner's Checklist\n\n1. **Decide what the decision needs.** Allocating an offer needs the cumulative effect of the offer against its cost. Pricing the feature needs the complier effect. Never rank accounts on a ratio.\n2. **Start with the reference.** `encouragement_effects()` gives the adoption curves, the first stage at each horizon, and the assigned-arm contrasts with no model at all.\n3. **Fit with enough chains and draws,** then report `predict(fit)$diagnostics` for exactly the quantities you will use.\n4. **Compare the population effects with the reference.** `predict(fit)` returns both on the same accounts; agreement is what licenses the account-level surfaces.\n5. **Predict for the population you will act on.** `predict_conditional(new_x = ...)` describes new accounts under the offer schedule you would deploy.\n6. **Use the draws.** Breakeven probabilities, certainty-adjusted rankings and regret filters are one line each, and `knapsack_policy()` respects capacity and budget.\n\n## Conclusion\n\nWhen adoption is a choice, the effect of an offer is a composition: what the offer does to when people adopt, and what adopting does over the weeks that follow. Modelling those two pieces separately and composing them keeps the activation jump where it belongs, delivers the effect of the offer account by account, and turns a pilot into a ranked list of whom to invite next, with the uncertainty attached.\n",
    "supporting": [
      "longbet_encouragement_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}