{
  "hash": "595ad1da6bf7081e929dc4b65c8ed82d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"LongBet: Decisions and Multiple Outcomes\"\ndescription: \"Translating dynamic treatment effects into business decisions: economic valuation scenarios, capacity-constrained targeting, and joint multi-outcome modeling.\"\nformat:\n  html:\n    css: longbet.css\nshare:\n  permalink: \"https://book.martinez.fyi/longbet_decisions.html\"\n  description: \"LongBet: Decisions and multiple outcomes in business causal inference\"\n  linkedin: true\n  email: true\n  mastodon: true\n---\n\n::: {.callout-note title=\"Continuation of the LongBet rollout study\"}\nThis chapter continues the randomized marketplace rollout introduced in **[LongBet: Dynamic Treatment Effects in Staggered Rollouts](longbet.qmd)**. It reuses the same seller population ($N=3,000$), calendar, log weekly GMV outcome scale, and fitted model objects to examine economic decision rules and multi-outcome trade-offs. Advanced extensions, including GP forecasting and observational panel identification, are covered in **[LongBet: Forecasting, Observational Panels, and Diagnostics](longbet_extensions.qmd)**.\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(longbet)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(tibble)\nlibrary(ggplot2)\nlibrary(purrr)\nlibrary(knitr)\n\nsource(\"R/longbet-common.R\")\nsource(\"R/longbet-rollout.R\")\nsource(\"R/longbet-artifacts.R\")\nverify_longbet_environment()\n\nlb_engine_fingerprint <- get_longbet_engine_fingerprint()\nlb_chapter_fingerprint <- digest::digest(file = knitr::current_input(), algo = \"sha256\")\nlb_dependencies <- get_longbet_dependencies()\nknitr::opts_chunk$set(cache.extra = list(lb_engine_fingerprint, lb_chapter_fingerprint,\n                                       lb_dependencies))\n\nrollout <- simulate_longbet_rollout()\nunpack_rollout(rollout)\n\nlb_fit <- get_or_create_core_fit(rollout)\ncl <- get_or_create_common_launch(lb_fit, rollout)\nS_target      <- cl$S_target\ntau_hat_draws <- cl$tau_hat_draws\ntau_hat       <- cl$tau_hat\ntau_truth_S   <- cl$tau_truth_S\ninitial_lift  <- cl$initial_lift\ngmv_week      <- cl$gmv_week\nmu0_hat       <- cl$mu0_hat\nsigma2_hat    <- cl$sigma2_hat\n```\n:::\n\n## The Decision {#sec-longbet-decision}\n\nThe marketplace keeps 12% of GMV and the optimizer costs \\$500 per seller per\nyear. An effect estimate becomes a dollar valuation only after choosing a\nbaseline revenue path, a treatment trajectory, and a decision rule. Each of\nthose choices needs to be visible.\n\nHere the baseline is a **fixed estimate** of untreated weekly revenue over the\nlast four study weeks. It uses the model's fitted untreated log outcome,\nincluding the unit intercept, with plug-in median parameter estimates for the\nlog-normal conversion. It uses no future observations or simulator parameters.\nWe hold that baseline constant over the decision year. This makes the analysis\nconditional on a baseline estimate; its intervals do not include baseline\nestimation error or uncertainty about future revenue growth.\n\nThe first scenario also holds the effect at its week-14 value for the remaining\n38 weeks of the year. For the first 14 weeks, it uses the all-seller adoption\ntrajectory used in @fig-catt-listings. These are 52-week **scenarios**, not forecasts\nof realized annual revenue. Later in this section we vary both assumptions.\n\nA log effect converts to proportional lift as `expm1(tau)`. The residual\nvariance cancels from the treated-to-untreated ratio under the model's common\nlog-normal error distribution. We apply that conversion to each effect draw\nbefore valuing a seller. For monetary summaries we report medians and quantiles:\na proper posterior does not by itself guarantee a finite mean after\nexponentiation. In particular, integrating a log-normal dollar mean over an\ninverse-gamma variance posterior need not have a finite expectation. Fixing\nthe baseline avoids claiming that the following is such an integrated dollar\nforecast.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTAKE_RATE   <- 0.12\nANNUAL_COST <- 500\nHOLD_WEEKS  <- 52 - S_target\n\nannual_lift <- initial_lift + HOLD_WEEKS * expm1(tau_hat_draws)\nnet_draws <- TAKE_RATE * gmv_week * annual_lift - ANNUAL_COST\nstopifnot(all(is.finite(net_draws)), all(gmv_week > 0))\nmedian_net <- apply(net_draws, 1, median)\np_worth <- rowMeans(net_draws > 0)\n\n# Truth is used only for scoring, never for selecting an operational policy.\nrecent <- tail(seq_along(week_study), 4)\nrecent_calendar <- week_study[recent]\ngmv_week_true <- rowMeans(exp(mu0_true[, recent_calendar, drop = FALSE] + 0.28^2 / 2))\ntrue_initial_lift <- rowSums(expm1(outer(w_i, seq_len(S_target), function(a, s)\n  a * h_grow(s) + (1 - a) * h_fade(s))))\ntrue_scenario_lift <- true_initial_lift + HOLD_WEEKS * expm1(tau_truth_S)\nnet_true <- TAKE_RATE * gmv_week_true * true_scenario_lift - ANNUAL_COST\n\nbreakeven <- ANNUAL_COST / (TAKE_RATE * 52 * gmv_week)\ntibble(\n  Quantity = c(\"Median estimated weekly baseline GMV\",\n               \"Median DGP-known weekly baseline GMV (scoring only)\",\n               \"Median break-even annual proportional lift\"),\n  Value = c(scales::dollar(median(gmv_week)),\n            scales::dollar(median(gmv_week_true)),\n            scales::percent(median(breakeven), 0.1))\n) %>% kable(caption = \"The baseline estimate and the separate simulator benchmark.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: The baseline estimate and the separate simulator benchmark.\n\n|Quantity                                            |Value   |\n|:---------------------------------------------------|:-------|\n|Median estimated weekly baseline GMV                |$732.35 |\n|Median DGP-known weekly baseline GMV (scoring only) |$743.02 |\n|Median break-even annual proportional lift          |10.9%   |\n\n\n:::\n:::\n\n\nThe DGP-known baseline is the simulator's expected untreated revenue over\nthose same four weeks. It is available to us for validation, not to the\nmarketplace when choosing sellers. The score below uses that baseline and the\ntrue treatment effects, while imposing the same flat-baseline and flat-tail\nscenario. It therefore measures errors in both baseline and effect estimation\nwithin that scenario. It is not a realized cash-flow observation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ranking by the posterior median is a transparent quantile-based rule.\n# It is not claimed to maximize posterior expected total profit.\nby_value <- order(median_net, decreasing = TRUE)\ntop_k <- function(K) {\n  keep <- rep(FALSE, n)\n  eligible <- by_value[median_net[by_value] > 0]\n  keep[head(eligible, min(K, length(eligible)))] <- TRUE\n  keep\n}\npolicies <- list(\n  \"Do not roll out\" = rep(FALSE, n),\n  \"Roll out to everyone\" = rep(TRUE, n),\n  \"Broad catalogs (>= 50 listings)\" = broad,\n  \"Up to 450 by positive median net value\" = top_k(450),\n  \"Up to 900 by positive median net value\" = top_k(900),\n  \"Up to 1350 by positive median net value\" = top_k(1350),\n  \"Positive median net value (uncapped)\" = median_net > 0,\n  \"P(net value > 0) >= 0.90\" = p_worth >= 0.90,\n  \"Oracle for the stated scenario (scoring only)\" = net_true > 0\n)\npolicy_value <- function(keep, label) {\n  total <- colSums(net_draws[keep, , drop = FALSE])\n  tibble(\n    Policy = label,\n    Sellers = sum(keep),\n    `Conditional median (k/yr)` = median(total) / 1000,\n    `Conditional 95% interval` = sprintf(\n      \"[%.0f, %.0f]\", quantile(total, 0.025) / 1000,\n      quantile(total, 0.975) / 1000\n    ),\n    `DGP-known scenario value (k/yr)` = sum(net_true[keep]) / 1000\n  )\n}\npolicy_results <- imap_dfr(policies, policy_value)\npolicy_results %>% kable(\n  digits = 0,\n  caption = paste(\n    \"Annual scenario values in thousands of US dollars.\",\n    \"Conditional intervals hold the estimated baseline and tail assumption fixed.\",\n    \"The DGP-known score uses true baselines and effects under the same scenario.\"\n  )\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Annual scenario values in thousands of US dollars. Conditional intervals hold the estimated baseline and tail assumption fixed. The DGP-known score uses true baselines and effects under the same scenario.\n\n|Policy                                        | Sellers| Conditional median (k/yr)|Conditional 95% interval | DGP-known scenario value (k/yr)|\n|:---------------------------------------------|-------:|-------------------------:|:------------------------|-------------------------------:|\n|Do not roll out                               |       0|                         0|[0, 0]                   |                               0|\n|Roll out to everyone                          |    3000|                      1387|[1029, 1895]             |                            1478|\n|Broad catalogs (>= 50 listings)               |    1077|                      1710|[1348, 2135]             |                            1849|\n|Up to 450 by positive median net value        |     450|                      1510|[1169, 1941]             |                            1555|\n|Up to 900 by positive median net value        |     900|                      1872|[1482, 2371]             |                            1945|\n|Up to 1350 by positive median net value       |    1304|                      1946|[1543, 2476]             |                            2021|\n|Positive median net value (uncapped)          |    1304|                      1946|[1543, 2476]             |                            2021|\n|P(net value > 0) >= 0.90                      |    1053|                      1913|[1517, 2425]             |                            1995|\n|Oracle for the stated scenario (scoring only) |    1295|                      1924|[1535, 2447]             |                            2044|\n\n\n:::\n:::\n\n\nThe table preserves posterior dependence by summing sellers within each draw\nbefore taking an interval. A total's median need not equal the sum of its\nsellers' medians, so ranking by seller medians is a stated heuristic rather\nthan a theorem about the best aggregate policy. The oracle maximizes the known\nscenario value because that score is additive; it is a validation benchmark,\nnot a deployable rule.\n\nThe probability threshold expresses a different preference from the capacity\nranking. Under a binary loss with constant cost for a wrong enable and constant\ncost for a missed profitable seller, a 0.90 threshold corresponds to assigning\nnine times as much loss to the former. That loss model ignores the magnitude\nof seller profits and losses. Choosing it requires a business judgment, and\nthe probabilities here remain conditional on the estimated baseline and the\nannual scenario.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The pooled ATT can mix well while seller-level valuations do not.\nseller_value_diagnostics <- diagnose_draws(\n  net_draws, lb_fit, \"Seller-level conditional annual net values\"\n)\nnonempty_policies <- policies[vapply(policies, any, logical(1))]\npolicy_total_draws <- do.call(rbind, lapply(nonempty_policies, function(keep)\n  colSums(net_draws[keep, , drop = FALSE])))\npolicy_value_diagnostics <- diagnose_draws(\n  policy_total_draws, lb_fit, \"Conditional annual policy totals\"\n)\ndiagnostic_rows <- bind_rows(\n  seller_value_diagnostics$summary, policy_value_diagnostics$summary\n)\n\n# Constant indicators contain no observed transitions; agreement at 0 or 1\n# does not establish that a rare event has been adequately sampled.\nvarying_probability <- p_worth > 0 & p_worth < 1\nif (any(varying_probability)) {\n  probability_diagnostics <- diagnose_draws(\n    1.0 * (net_draws[varying_probability, , drop = FALSE] > 0),\n    lb_fit, \"Nonconstant seller profitability indicators\"\n  )\n  diagnostic_rows <- bind_rows(diagnostic_rows, probability_diagnostics$summary)\n}\ndiagnostic_rows %>% kable(\n  digits = 3, caption = \"Sampling diagnostics for the quantities used in the decision.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Sampling diagnostics for the quantities used in the decision.\n\n|label                                       | rhat_max| ess_min| ess_tail_min|diagnostic_ok |\n|:-------------------------------------------|--------:|-------:|------------:|:-------------|\n|Seller-level conditional annual net values  |    2.473|   4.923|       27.008|FALSE         |\n|Conditional annual policy totals            |    1.182|  15.958|       52.617|FALSE         |\n|Nonconstant seller profitability indicators |    5.251|   4.256|        4.256|FALSE         |\n\n\n:::\n\n```{.r .cell-code}\ncat(sum(!varying_probability),\n    \"seller profitability indicators were constant across retained draws.\",\n    \"Their rare-event probabilities are not certified by that agreement.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1959 seller profitability indicators were constant across retained draws. Their rare-event probabilities are not certified by that agreement.\n```\n\n\n:::\n\n```{.r .cell-code}\ndecision_sampling_ok <- all(diagnostic_rows$diagnostic_ok)\n```\n:::\n\n\nThe reported decision diagnostics\nfail at least one stated threshold.\nTreat the ranking, intervals, and probability rule as an unresolved illustration until further sampling establishes stability.\nA probability shown as zero or one from finite draws is not proof that an\nevent is impossible or certain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  Segment = c(\"Narrow catalog (< 50 listings)\", \"Broad catalog (>= 50 listings)\"),\n  Sellers = c(sum(!broad), sum(broad)),\n  `Median true lift after 14 weeks` = scales::percent(\n    c(median(expm1(tau_truth_S[!broad])), median(expm1(tau_truth_S[broad]))), 0.1),\n  `Positive DGP-known scenario value` = scales::percent(\n    c(mean(net_true[!broad] > 0), mean(net_true[broad] > 0)), 0.1)\n) %>% kable(caption = paste(\n  \"Effect size and dollar value answer different questions.\",\n  \"Scenario value uses the true baseline and the stated 38-week flat tail.\"\n))\n```\n\n::: {.cell-output-display}\n\n\nTable: Effect size and dollar value answer different questions. Scenario value uses the true baseline and the stated 38-week flat tail.\n\n|Segment                        | Sellers|Median true lift after 14 weeks |Positive DGP-known scenario value |\n|:------------------------------|-------:|:-------------------------------|:---------------------------------|\n|Narrow catalog (< 50 listings) |    1923|2.7%                            |16.2%                             |\n|Broad catalog (>= 50 listings) |    1077|23.6%                           |91.3%                             |\n\n\n:::\n:::\n\n\nA catalog rule selects on the effect surface, whereas an economic rule also\ndepends on seller size and the flat \\$500 cost. The table quantifies that\ndistinction under the stated scenario. It does not establish that every broad\ncatalog should be enabled or that every narrow catalog should be excluded.\nLikewise, any gap between the estimated and DGP-known columns is an error for\nthis realization. Baseline estimation, effect estimation, nonlinear\ntransformation, and selection can all contribute; this table cannot identify\nwhich mechanism caused the gap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Hold the chosen policy fixed so that the table isolates assumptions rather\n# than changing both assumptions and sellers at once.\ndecay_tail <- matrix(0, nrow(net_draws), ncol(net_draws))\nfor (k in seq_len(HOLD_WEEKS)) {\n  decay_tail <- decay_tail + expm1(tau_hat_draws * 2^(-k / 13))\n}\nlift_scenarios <- list(\n  \"No effect after week 14\" = initial_lift,\n  \"Log effect halves every 13 weeks\" = initial_lift + decay_tail,\n  \"Flat log effect after week 14\" = annual_lift\n)\nsensitivity_keep <- top_k(450)\ndecision_sensitivity <- imap_dfr(lift_scenarios, function(lift, label) {\n  map_dfr(c(0.8, 1.0, 1.2), function(baseline_factor) {\n    total <- TAKE_RATE * colSums(\n      gmv_week[sensitivity_keep] *\n        lift[sensitivity_keep, , drop = FALSE]\n    ) * baseline_factor - ANNUAL_COST * sum(sensitivity_keep)\n    tibble(\n      `Effect scenario` = label,\n      `Baseline multiplier` = baseline_factor,\n      `Conditional median (k/yr)` = median(total) / 1000,\n      `Conditional 95% interval` = sprintf(\n        \"[%.0f, %.0f]\", quantile(total, 0.025) / 1000,\n        quantile(total, 0.975) / 1000\n      )\n    )\n  })\n})\ndecision_sensitivity %>% kable(\n  digits = 1,\n  caption = paste(\n    \"The same\", sum(sensitivity_keep),\n    \"sellers selected by the capacity rule, under nine valuation assumptions.\",\n    \"Baseline multipliers are sensitivity scenarios, not a posterior interval.\"\n  )\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: The same 450 sellers selected by the capacity rule, under nine valuation assumptions. Baseline multipliers are sensitivity scenarios, not a posterior interval.\n\n|Effect scenario                  | Baseline multiplier| Conditional median (k/yr)|Conditional 95% interval |\n|:--------------------------------|-------------------:|-------------------------:|:------------------------|\n|No effect after week 14          |                 0.8|                      87.9|[50, 141]                |\n|No effect after week 14          |                 1.0|                     166.2|[118, 233]               |\n|No effect after week 14          |                 1.2|                     244.4|[187, 324]               |\n|Log effect halves every 13 weeks |                 0.8|                     515.7|[392, 674]               |\n|Log effect halves every 13 weeks |                 1.0|                     700.9|[546, 899]               |\n|Log effect halves every 13 weeks |                 1.2|                     886.1|[701, 1124]              |\n|Flat log effect after week 14    |                 0.8|                    1163.1|[890, 1508]              |\n|Flat log effect after week 14    |                 1.0|                    1510.1|[1169, 1941]             |\n|Flat log effect after week 14    |                 1.2|                    1857.1|[1448, 2374]             |\n\n\n:::\n\n```{.r .cell-code}\nif (any(sensitivity_keep)) {\n  sensitivity_total_draws <- do.call(rbind, lapply(lift_scenarios, function(lift) {\n    gross <- TAKE_RATE * colSums(\n      gmv_week[sensitivity_keep] * lift[sensitivity_keep, , drop = FALSE]\n    )\n    rbind(0.8 * gross, gross, 1.2 * gross) - ANNUAL_COST * sum(sensitivity_keep)\n  }))\n  sensitivity_diagnostics <- diagnose_draws(\n    sensitivity_total_draws, lb_fit, \"Nine conditional valuation scenarios\"\n  )\n  sensitivity_diagnostics$summary %>% kable(\n    digits = 3, caption = \"Sampling diagnostics for the sensitivity totals.\"\n  )\n} else {\n  cat(\"No sellers selected: every scenario total is exactly zero by construction.\\n\")\n}\n```\n\n::: {.cell-output-display}\n\n\nTable: Sampling diagnostics for the sensitivity totals.\n\n|label                                | rhat_max| ess_min| ess_tail_min|diagnostic_ok |\n|:------------------------------------|--------:|-------:|------------:|:-------------|\n|Nine conditional valuation scenarios |    1.561|   7.348|       52.617|FALSE         |\n\n\n:::\n:::\n\n\n::: {.callout-warning title=\"A year of value remains an assumption\"}\nThe study observes at most 14 weeks of exposure and @sec-longbet-forecast\nevaluates six withheld calendar weeks. Neither validates a 38-week flat tail.\nThe sensitivity table varies that tail and the baseline while keeping the\nchosen sellers fixed. A decision that changes sign across these assumptions\nneeds more evidence or a more limited commitment; tighter Monte Carlo intervals\ncannot resolve uncertainty about the economic scenario.\n:::\n\nOutside a simulation, evaluating a learned targeting rule needs outcomes from\na design that identifies the policy's value, such as a held-out randomized\nsample with adequate overlap. Sample splitting keeps policy selection\nseparate from evaluation, and cross-fitting can repeat that separation across\nfolds. Neither procedure supplies unobserved annual outcomes or validates a\nlong-run revenue assumption. Those remain separate parts of the business\ncase.\n\n## When the Decision Has Three Outcomes {#sec-longbet-multi}\n\nThe decision in @sec-longbet-decision had one outcome and one threshold: does\n12% of this seller's extra annual GMV cover the \\$500 annual cost? Launch\nreviews rarely stay that tidy. The\noptimizer rewrites listings, so the questions actually asked are: does it sell\nmore, does it save the seller work, and does it put words on the page that\ncustomers complain about. Three outcomes, three scales, one decision that needs\nall three at once.\n\nThe tempting move is to fit three models, read off three probabilities and\nmultiply. Suppose each requirement holds with probability 0.8. Multiplying\ngives $0.8^3 = 0.512$. But the marginals do not pin the intersection down\nuniquely: for a given seller, it is as high as 0.8 if the same posterior draws\nsatisfy all three, and as low as\n$0.8 + 0.8 + 0.8 - 2 = 0.4$ if the failures are spread as widely as possible.\nAnything in $[0.4, 0.8]$ is consistent with those three numbers, and 0.512 is\njust what you get by *assuming* independence. Those are the Fréchet bounds ---\narithmetic, not a result from this experiment, and no amount of data on the\nmarginals alone will narrow them.\n\nWhat closes the gap is a joint posterior: draws in which each seller's three\neffects are sampled together, so a draw where GMV is up can be checked against\nwhether workload fell *in that same draw*.\n\n### Three outcomes on one rollout\n\nWe extend the experiment with two more responses. This is a **supplemental\nversion of the chapter's simulation**: sellers, randomized waves, covariates\nand untreated GMV paths are reused unchanged, but the GMV treatment response is\nmodified so the optimizer genuinely harms some sellers. Its numbers are\ntherefore not comparable to the fitted results earlier in the chapter, and the\noriginal objects are left untouched.\n\n| Outcome | What LongBet is given | Type | Good direction |\n| --- | --- | --- | --- |\n| `gmv` | Log weekly GMV, with a signed treatment response | Continuous | Increase |\n| `seller_hours` | Log weekly hours spent maintaining listings | Continuous | Decrease |\n| `complaint` | Did this seller get a listing-quality complaint this week | Binary (probit) | Little or no increase |\n\n`seller_hours` is the *seller's* workload, not the marketplace's cost of\nrunning the optimizer: it is not a second charge against the \\$500 in\n@sec-longbet-decision, and this section does not restate that valuation. The\ncomplaint indicator is a recurrent seller-week event --- not churn, not\nsurvival, not complaints per order --- so its effect is a change in the\nprobability of a complaint week and nothing else.\n\nThe heterogeneity is deliberate and signed. Broad-catalog, fulfilled sellers\ngain GMV, save time and attract fewer complaints. Small-catalog, self-shipping\nsellers lose GMV, spend *more* time and attract more. Sellers in between can\nhave aligned effects or face trade-offs across outcomes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sampler and sample settings for the supplement, kept separate from the\n# thresholds so that changing a business rule does not refit anything.\nMULTI_SEED_FIT  <- 314159L\nMULTI_SEED_PRED <- 271829L\nMULTI_SEP_SEEDS <- c(gmv = 314160L, seller_hours = 314161L, complaint = 314162L)\nMULTI_TREES     <- 20L\nmulti_idx       <- seq.int(1L, n, by = 4L)   # every fourth seller, by row index\nmulti_n         <- length(multi_idx)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# One common launch in week 11, read at week 18: eight weeks of exposure.\nmulti_target_s    <- 8L\nmulti_target_week <- 18L\nmulti_target_col  <- match(multi_target_week, week_study)\nmulti_z_eval <- matrix(rep(as.integer(week_study >= 11L), each = multi_n),\n                       nrow = multi_n)\nstopifnot(!is.na(multi_target_col),\n          all(rowSums(multi_z_eval[, seq_len(multi_target_col), drop = FALSE]) ==\n                multi_target_s))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Illustrative business thresholds. Not tuned to the simulation truth.\nMULTI_GMV_MIN       <-  0.05    # GMV up at least 5%\nMULTI_HOURS_MAX     <- -0.10    # maintenance hours down at least 10%\nMULTI_COMPLAINT_MAX <-  0.01    # complaint probability up by at most 1 point\n```\n:::\n\n\nThe screen we will apply at eight weeks of exposure is: **GMV up at least 5%,\nmaintenance hours down at least 10%, and complaint probability up by no more\nthan one percentage point.** Tolerating one point of extra complaint risk is\nnot the same as requiring no harm, and passing this screen is not a claim about\nprofitability or about a safe full-market rollout. It is one prespecified rule,\nchosen before any fit, so that the section is not scored against a threshold\npicked after seeing the answer.\n\n### What the joint model shares, and what it does not\n\nEach outcome gets its own prognostic forest, its own treatment forest, its own\nexposure trajectory $\\beta_S$, and its own seller intercepts. Fitting jointly\ndoes **not** force GMV, workload and complaints to respond alike. What is\nshared is the residual: after each outcome's own mean is subtracted, what\nremains in a given seller-week is allowed to be correlated across outcomes.\n\n$$\nY^{*}_{it,m} = f_m(X_i, t, S_{it}) + \\varepsilon_{it,m},\n\\qquad\n\\varepsilon_{it} \\sim \\mathcal{N}(0, \\Sigma)\n$$\n\nFor the two continuous outcomes $Y^{*}$ is the log response as supplied. For\nthe binary outcome it is a latent probit response whose sign produces the\nobserved indicator. $\\Sigma$ is parameterized triangularly, $\\Sigma = A^{-1} H\nA^{-\\top}$ with $A = I - \\Gamma$ and $\\Gamma$ strictly lower triangular, in the\nstyle of @huber2022bavart.\n\nThree different correlations get confused here, so it is worth separating them:\n\n  - **Level correlation.** Big sellers have more GMV, more maintenance work and\n    more complaints. That is covariates doing their job, and it is present even\n    with no shared residual at all.\n  - **Innovation correlation.** What is left over in the same seller-week after\n    each outcome's fitted mean is removed. This is the $\\Sigma$ above, and it is\n    the only one the joint fit adds.\n  - **Posterior dependence between effect draws.** Uncertainty about one\n    seller's three effects at one exposure time, moving together across draws.\n    This is what the joint screen consumes, and it is not the same thing as\n    correlation of *true* effects across sellers.\n\nThe third is what a joint fit is for: a distribution over *combinations* of\neffects. Information sharing may also sharpen individual estimates, but that is\nnot automatic, and a smaller conditional residual variance is not evidence of\nbetter treatment-effect accuracy. Note too that positive innovation correlation\ndoes **not** imply the three *favorable* events move together --- workload has\nto fall and complaints stay under a ceiling, so two thresholds point opposite\nto GMV. Where the joint probability lands relative to the independence product\nis a question for the data.\n\n::: {.callout-note title=\"Triangular SUR likelihood with full precision\"}\nThe engine couples the equations using the full precision of a triangular\nseemingly unrelated regressions likelihood (`full_precision_sur_v1`). Downstream\nequations feed back into earlier equations' likelihoods, and probit latent\nresiduals are augmented and updated conditional on the continuous residuals.\nContinuous outcomes require proper inverse-gamma innovation-variance priors\n(`sigma_prior_a = 2, sigma_prior_b = 1`); an improper scale prior can produce\nan improper joint posterior.\n\nInternally the binary equation is placed first with unit marginal latent\nvariance, so caller outcomes `[gmv, seller_hours, complaint]` are ordered\ninternally as `[complaint, gmv, seller_hours]`. Results and draw arrays are\nalways mapped back into caller order.\n:::\n\nEverything @sec-longbet-limits says still applies: a joint model does nothing\nabout interference, serial dependence, confounding in a non-randomized rollout,\nthe multiplicity of asking three questions instead of one, or the risks of\nextrapolation. The example below uses complete outcomes throughout, which\nsidesteps missingness entirely.\n\n### The supplemental simulation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_data <- withr::with_seed(271828, local({\n  ii <- multi_idx; nn <- multi_n; tt <- length(weeks_all)\n  tm <- tmat[ii, , drop = FALSE]\n  ss <- S[ii, , drop = FALSE]\n\n  # The untreated GMV shock is reconstructed from known simulation parameters\n  # ONLY so the three outcomes can share correlated errors. None of this\n  # reaches the model as a covariate.\n  gmv_mu0 <- matrix(level_i[ii], nn, tt) + outer(drift_i[ii], weeks_all, \"*\") +\n             season(matrix(vertical[ii], nn, tt), tm)\n  u <- (y0[ii, , drop = FALSE] - gmv_mu0) / 0.28\n  v <- matrix(rnorm(nn * tt), nn, tt)\n  w <- matrix(rnorm(nn * tt), nn, tt)\n  e_hours     <- 0.60 * u + 0.80 * v                        # cor(u, .) = 0.60\n  e_complaint <- 0.45 * u + 0.10 * v + sqrt(0.7875) * w     # cor(u, .) = 0.45\n\n  # Baselines depend on observed seller features and on calendar time.\n  hours_mu0 <- matrix(log(3) + 0.40 * log(listings[ii] / 35) -\n                        0.20 * fulfilled[ii] +\n                        0.10 * (vertical[ii] == \"Apparel\"), nn, tt) +\n               0.04 * cos(tm / 3)\n  complaint_mu0 <- matrix(-1.5 + 0.25 * log(listings[ii] / 35) -\n                            0.35 * fulfilled[ii] +\n                            0.15 * (vertical[ii] == \"Apparel\"), nn, tt) +\n                   0.08 * sin(tm / 4)\n\n  # Signed effects: the chapter's GMV gain, minus a persistent loss\n  # concentrated among small-catalog, self-shipping sellers.\n  gmv_penalty <- 0.24 * (1 - w_i[ii]) * (1 - fulfilled[ii])\n  gmv_tau     <- tau_true[ii, , drop = FALSE] -\n                 matrix(gmv_penalty, nn, tt) * (1 - exp(-ss / 3))\n  hours_amplitude <- -0.10 - 0.20 * w_i[ii] + 0.08 * (1 - fulfilled[ii]) +\n                     0.25 * (1 - w_i[ii]) * (1 - fulfilled[ii])\n  complaint_amplitude <- 0.26 - 0.44 * w_i[ii] - 0.18 * fulfilled[ii]\n\n  list(index = ii,\n       gmv          = y0[ii, , drop = FALSE] + gmv_tau,\n       seller_hours = hours_mu0 + matrix(hours_amplitude, nn, tt) *\n                        (1 - exp(-ss / 3)) + 0.30 * e_hours,\n       complaint    = 1L * (complaint_mu0 + matrix(complaint_amplitude, nn, tt) *\n                        (1 - exp(-ss / 4)) + e_complaint > 0),\n       hours_mu0 = hours_mu0, complaint_mu0 = complaint_mu0,\n       gmv_penalty = gmv_penalty, hours_amplitude = hours_amplitude,\n       complaint_amplitude = complaint_amplitude,\n       errors = list(gmv = u, seller_hours = e_hours, complaint = e_complaint))\n}))\n\nmulti_y <- lapply(multi_data[c(\"gmv\", \"seller_hours\", \"complaint\")],\n                  function(a) a[, match(week_study, weeks_all), drop = FALSE])\nmulti_x     <- x[multi_idx, , drop = FALSE]\nmulti_z     <- z_train[multi_idx, , drop = FALSE]\nmulti_types <- c(gmv = \"continuous\", seller_hours = \"continuous\",\n                 complaint = \"binary\")\n```\n:::\n\n\n`withr::with_seed()` confines the new randomness so that every later simulation\nin this chapter draws exactly what it drew before. `set.seed()` inside\n`local()` would not: it would leave the global stream advanced.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_err <- cor(sapply(multi_data$errors, as.vector))\nstopifnot(\n  identical(dim(multi_y$gmv), c(multi_n, length(week_study))),\n  all(sapply(multi_y, function(a) all(is.finite(a)))),\n  setequal(unique(as.vector(multi_y$complaint)), c(0L, 1L)),\n  # untreated cells must be exactly the chapter's untreated GMV\n  isTRUE(all.equal(multi_data$gmv[S[multi_idx, ] == 0],\n                   y0[multi_idx, ][S[multi_idx, ] == 0])),\n  # check innovation correlation structure\n  abs(multi_err[\"gmv\", \"seller_hours\"] - 0.60) < 0.05,\n  abs(multi_err[\"gmv\", \"complaint\"]    - 0.45) < 0.05,\n  abs(multi_err[\"seller_hours\", \"complaint\"] - 0.35) < 0.05\n)\n\n# Benchmark truth at exposure 8 (week 18) under the common launch\nmulti_gmv_truth_log <- w_i[multi_idx] * h_grow(multi_target_s) +\n  (1 - w_i[multi_idx]) * h_fade(multi_target_s) -\n  multi_data$gmv_penalty * (1 - exp(-multi_target_s / 3))\nmulti_hours_truth_log <- multi_data$hours_amplitude *\n  (1 - exp(-multi_target_s / 3))\nmulti_complaint_truth_latent <- multi_data$complaint_amplitude *\n  (1 - exp(-multi_target_s / 4))\nmulti_mu0_q <- multi_data$complaint_mu0[, match(multi_target_week, weeks_all)]\nmulti_complaint_truth_prob <- pnorm(multi_mu0_q + multi_complaint_truth_latent) -\n  pnorm(multi_mu0_q)\n\nmulti_truth <- list(\n  gmv          = expm1(multi_gmv_truth_log),\n  seller_hours = expm1(multi_hours_truth_log),\n  complaint    = multi_complaint_truth_prob\n)\n\n# Prespecified validation regions, from observed covariates only. These are\n# never given to the model.\nmulti_good <- listings[multi_idx] >= 80 & fulfilled[multi_idx] == 1\nmulti_bad  <- listings[multi_idx] <= 25 & fulfilled[multi_idx] == 0\nmulti_mid  <- !multi_good & !multi_bad\nstopifnot(sum(multi_good) > 30, sum(multi_bad) > 30,\n          all(multi_truth$gmv[multi_good] > 0), all(multi_truth$gmv[multi_bad] < 0),\n          all(multi_truth$seller_hours[multi_good] < 0),\n          all(multi_truth$seller_hours[multi_bad] > 0),\n          all(multi_truth$complaint[multi_good] < 0),\n          all(multi_truth$complaint[multi_bad] > 0))\n```\n:::\n\n\nThat `stopifnot()` is doing real work. It confirms, *before* any model is fit,\nthat the two regions really do have opposite signs on all three outcomes.\nWithout it, a model that failed to separate them would be indistinguishable\nfrom a simulation that never separated them. The regions sit at 80 and 25\nlistings while the chapter's weight $w_i$ turns over near 50: they are read-out\ngroups, and the forests are never told they exist.\n\n### Fitting the three outcomes together\n\n`longbet_multi()` takes a *named list* of response panels and a matching named\nvector of types. Everything else is the ordinary LongBet interface.\n\n::: {.panel-tabset}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_fit <- longbet_multi(\n  y = multi_y, x = multi_x, z = multi_z, t = week_study,\n  outcome = multi_types,\n  num_burnin = 2000, num_sweeps = 250, n_skip = 2, num_chains = 4,\n  num_trees_pr = MULTI_TREES, num_trees_trt = MULTI_TREES,\n  sig_knl = 1, lambda_knl = 2,\n  sigma_prior_a = 2, sigma_prior_b = 1,\n  random_intercept = TRUE, sur = TRUE, sur_prior_var = 1,\n  random_seed = MULTI_SEED_FIT\n)\n```\n:::\n\n\n## Python\n\n```python\nimport jax\nfrom longbet import LongBetConfig, LongBetMulti, effect_draws, joint_prob\n\nmulti_config = LongBetConfig(\n    num_burnin=2000, num_sweeps=250, n_skip=2, num_chains=4,\n    num_trees_pr=20, num_trees_trt=20,\n    sig_knl=1.0, lambda_knl=2.0,\n    sigma_prior_a=2.0, sigma_prior_b=1.0,\n    random_intercept=True,\n    sur=True, sur_prior_var=1.0, random_seed=314159,\n)\n# Outcome types belong to fit(), not to the config or the constructor.\nmulti_fit = LongBetMulti(multi_config).fit(\n    y=multi_y, x=multi_x, z=multi_z, t=week_study,\n    outcome={\"gmv\": \"continuous\", \"seller_hours\": \"continuous\",\n             \"complaint\": \"binary\"},\n)\nmulti_pred = multi_fit.predict(\n    x=multi_x, z=multi_z_eval, t=week_study,\n    summary_only=False, key=jax.random.key(271829),\n)\nmulti_complaint_effect = effect_draws(multi_pred, \"complaint\")\n```\n:::\n\nTwo differences from @sec-longbet-fitting are worth flagging. This supplement\nuses 750 sellers rather than 3,000, and\n20 trees per forest rather than 60 --- three outcomes plus three\ncomparison fits would otherwise dominate the build time. That is a runtime\ndecision, not a licence to under-sample: burn-in, sweeps, thinning and chain\ncount are the package defaults, and the diagnostics below are read on what was\nactually run.\n\nIn Python the fit seed lives in the config and the prediction seed is a JAX\nkey; R exposes both as `random_seed`. Child outcomes are reached by name in\nboth --- `multi_pred[\"gmv\"]` --- with R 1-based and Python 0-based.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_pred <- predict(multi_fit, x = multi_x, z = multi_z_eval, t = week_study,\n                      summary_only = FALSE, random_seed = MULTI_SEED_PRED)\n\n# Full draws are needed for a joint event; marginal intervals cannot rebuild\n# one. Keep only the target column afterwards -- the full arrays are large.\nmulti_draws <- lapply(setNames(nm = names(multi_types)), function(nm)\n  matrix(effect_draws(multi_pred, nm)[, multi_target_col, ], nrow = multi_n))\nmulti_D  <- ncol(multi_draws$gmv)\nmulti_CM <- outcome_correlation(multi_fit)\nmulti_att <- lapply(setNames(nm = names(multi_types)), function(nm)\n  att_stability(multi_pred[nm], warn = FALSE)$summary)\n```\n:::\n\n\n`effect_draws()` returns each outcome on the scale you have to reason on. For\nthe two continuous outcomes that is the supplied log scale, so a draw becomes a\nproportional change through $e^{\\tau} - 1$ --- and the transformation happens\n**per draw**, before averaging, because $e^{\\overline{\\tau}} - 1$ is not\n$\\overline{e^{\\tau} - 1}$. For the binary outcome `effect_draws()` has already\ndone the conversion: it returns\n$\\Phi(\\mu_0 + \\tau) - \\Phi(\\mu_0)$, a difference in probability, using the\nbaseline and the effect *from the same draw*. Do not exponentiate that one.\n\n### The three-condition probability\n\n`joint_prob()` takes one predicate per outcome and a logical matrix selecting\nwhich cells to score. We select exactly one week per seller, which makes the\nanswer one number per seller: *the posterior probability that this seller\nsatisfies all three conditions at eight weeks of exposure.* Selecting several\nweeks would average probabilities across weeks, which answers a different and\nmuch vaguer question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_conditions <- list(\n  gmv          = function(a) a >= log1p(MULTI_GMV_MIN),\n  seller_hours = function(a) a <= log1p(MULTI_HOURS_MAX),\n  complaint    = function(a) a <= MULTI_COMPLAINT_MAX\n)\nmulti_cells <- matrix(FALSE, multi_n, length(week_study))\nmulti_cells[, multi_target_col] <- TRUE\nmulti_p_joint <- as.vector(joint_prob(multi_pred, conditions = multi_conditions,\n                                      cells = multi_cells))\n\n# The same event, rebuilt by hand from the aligned draws.\nmulti_B <- list(gmv          = multi_draws$gmv          >= log1p(MULTI_GMV_MIN),\n                seller_hours = multi_draws$seller_hours <= log1p(MULTI_HOURS_MAX),\n                complaint    = multi_draws$complaint    <= MULTI_COMPLAINT_MAX)\nmulti_p_manual  <- rowMeans(Reduce(`&`, multi_B))\nmulti_p_marg    <- lapply(multi_B, rowMeans)\nmulti_p_product <- Reduce(`*`, multi_p_marg)\n\nstopifnot(\n  max(abs(multi_p_joint - multi_p_manual)) < 1e-10,\n  # Frechet bounds must hold seller by seller\n  all(multi_p_manual >= pmax(0, Reduce(`+`, multi_p_marg) - 2) - 1e-12),\n  all(multi_p_manual <= do.call(pmin, multi_p_marg) + 1e-12)\n)\nmulti_truth_event <- multi_truth$gmv >= MULTI_GMV_MIN &\n  multi_truth$seller_hours <= MULTI_HOURS_MAX &\n  multi_truth$complaint <= MULTI_COMPLAINT_MAX\n\n# The package utility has now been checked against the manual calculation, so\n# the full draw arrays can go; everything below runs off the target slices.\nrm(multi_pred); invisible(gc())\n```\n:::\n\n\nTwo comparisons follow, and they are not the same comparison.\n`multi_p_product` multiplies **this fit's own** marginal probabilities. It\nholds the marginals fixed and throws away only the dependence between draws, so\nthe gap between it and `multi_p_joint` isolates exactly one thing. The second\ncomparison needs three genuinely separate models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Same rows, covariates, panel, scenario and hyperparameters; different seeds.\n# Fitted and reduced one at a time so three full draw arrays never coexist.\nmulti_sep_draws <- list()\nmulti_sep_att   <- list()\nfor (nm in names(multi_types)) {\n  f <- longbet(y = multi_y[[nm]], x = multi_x, z = multi_z, t = week_study,\n               outcome = unname(multi_types[[nm]]),\n               num_burnin = 2000, num_sweeps = 250, n_skip = 2, num_chains = 4,\n               num_trees_pr = MULTI_TREES, num_trees_trt = MULTI_TREES,\n               sig_knl = 1, lambda_knl = 2,\n               sigma_prior_a = 2, sigma_prior_b = 1,\n               random_intercept = TRUE,\n               random_seed = MULTI_SEP_SEEDS[[nm]])\n  p <- predict(f, x = multi_x, z = multi_z_eval, t = week_study,\n               summary_only = FALSE, random_seed = MULTI_SEED_PRED + 1L)\n  multi_sep_draws[[nm]] <- matrix(effect_draws(p)[, multi_target_col, ],\n                                  nrow = multi_n)\n  multi_sep_att[[nm]] <- att_stability(p, warn = FALSE)$summary\n  rm(f, p); invisible(gc())\n}\nmulti_p_separate <-\n  rowMeans(multi_sep_draws$gmv          >= log1p(MULTI_GMV_MIN)) *\n  rowMeans(multi_sep_draws$seller_hours <= log1p(MULTI_HOURS_MAX)) *\n  rowMeans(multi_sep_draws$complaint    <= MULTI_COMPLAINT_MAX)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_est <- lapply(multi_draws, function(d) {\n  if (identical(d, multi_draws$complaint)) rowMeans(d)\n  else rowMeans(expm1(d))\n})\nmulti_region <- factor(\n  ifelse(multi_good, \"Clear benefit\",\n  ifelse(multi_bad,  \"Clear harm\", \"In between\")),\n  levels = c(\"Clear benefit\", \"In between\", \"Clear harm\")\n)\nmulti_recovery <- purrr::map_dfr(names(multi_types), function(nm) {\n  dr <- if (nm == \"complaint\") multi_draws[[nm]] else expm1(multi_draws[[nm]])\n  purrr::map_dfr(c(\"Clear benefit\", \"Clear harm\"), function(rg) {\n    m <- multi_region == rg\n    reg <- colMeans(dr[m, , drop = FALSE])\n    tibble::tibble(\n      outcome = nm, region = rg, n = sum(m),\n      truth = mean(multi_truth[[nm]][m]),\n      est = mean(reg), lo = unname(quantile(reg, 0.025)),\n      hi = unname(quantile(reg, 0.975)),\n      p_correct_sign = if (mean(multi_truth[[nm]][m]) > 0) mean(reg > 0)\n                       else mean(reg < 0),\n      rmse = sqrt(mean((multi_est[[nm]][m] - multi_truth[[nm]][m])^2)),\n      sign_acc = mean(sign(multi_est[[nm]][m]) == sign(multi_truth[[nm]][m]))\n    )\n  })\n})\n\nmulti_p_benefit <- list(\n  gmv          = rowMeans(multi_draws$gmv          > 0),\n  seller_hours = rowMeans(multi_draws$seller_hours < 0),\n  complaint    = rowMeans(multi_draws$complaint    < 0)\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_labels <- c(gmv = \"GMV lift (higher is better)\",\n                  seller_hours = \"Maintenance hours (lower is better)\",\n                  complaint = \"Complaint probability (lower is better)\")\nmulti_plot_df <- purrr::map_dfr(names(multi_types), function(nm)\n  tibble::tibble(outcome = multi_labels[[nm]],\n                 truth = multi_truth[[nm]], est = multi_est[[nm]],\n                 region = multi_region))\n\nggplot(multi_plot_df, aes(truth, est, colour = region)) +\n  geom_hline(yintercept = 0, linewidth = 0.3) +\n  geom_vline(xintercept = 0, linewidth = 0.3) +\n  geom_abline(linetype = \"dashed\", linewidth = 0.4) +\n  geom_point(alpha = 0.55, size = 0.9) +\n  facet_wrap(~ outcome, scales = \"free\") +\n  scale_colour_manual(values = c(\"Clear benefit\" = \"#009E73\",\n                                 \"In between\" = \"#999999\",\n                                 \"Clear harm\" = \"#CC79A7\")) +\n  labs(x = \"True conditional effect\", y = \"Posterior mean effect\",\n       colour = NULL) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"bottom\", panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![Known conditional effect against posterior mean, by outcome, at eight weeks of exposure. Each point is a seller. The dashed diagonal is perfect recovery; the solid lines mark zero on each axis. Colour marks the two prespecified validation regions, which were never given to the model. Beneficial is up for GMV and down for the other two.](longbet_decisions_files/figure-html/fig-longbet-multi-heterogeneity-1.png){#fig-longbet-multi-heterogeneity width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tibble::tibble(product = multi_p_product, joint = multi_p_joint,\n                      region = multi_region),\n       aes(product, joint, colour = region)) +\n  geom_abline(linetype = \"dashed\", linewidth = 0.4) +\n  geom_point(alpha = 0.55, size = 1) +\n  coord_equal(xlim = c(0, 1), ylim = c(0, 1)) +\n  scale_colour_manual(values = c(\"Clear benefit\" = \"#009E73\",\n                                 \"In between\" = \"#999999\",\n                                 \"Clear harm\" = \"#CC79A7\")) +\n  labs(x = \"Product of this fit's marginals\", y = \"Joint probability\",\n       colour = NULL) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"bottom\", panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![The joint three-condition probability against the product of the same fit's three marginal probabilities. Points on the diagonal are sellers for whom dependence between the effect draws changes nothing.](longbet_decisions_files/figure-html/fig-longbet-multi-joint-1.png){#fig-longbet-multi-joint width=480}\n:::\n:::\n\n\n\n::: {#tbl-longbet-multi .cell tbl-cap='Three-condition screen at eight weeks of exposure, by descriptive seller group. The true fraction is available only because this is a simulation.'}\n\n```{.r .cell-code}\nmulti_group <- factor(paste(ifelse(listings[multi_idx] >= 50, \"Broad\", \"Narrow\"),\n                            ifelse(fulfilled[multi_idx] == 1, \"fulfilled\",\n                                   \"self-ship\")))\ntibble::tibble(Group = multi_group, truth = multi_truth_event,\n               joint = multi_p_joint, prod_same = multi_p_product,\n               prod_sep = multi_p_separate) %>%\n  group_by(Group) %>%\n  summarise(Sellers = n(),\n            `True fraction` = mean(truth),\n            `Joint fit` = mean(joint),\n            `Same-fit product` = mean(prod_same),\n            `Separate-fit product` = mean(prod_sep), .groups = \"drop\") %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Group            | Sellers| True fraction| Joint fit| Same-fit product| Separate-fit product|\n|:----------------|-------:|-------------:|---------:|----------------:|--------------------:|\n|Broad fulfilled  |     133|         1.000|     0.970|            0.970|                0.966|\n|Broad self-ship  |     161|         0.547|     0.478|            0.496|                0.453|\n|Narrow fulfilled |     210|         0.333|     0.217|            0.239|                0.161|\n|Narrow self-ship |     246|         0.000|     0.000|            0.000|                0.000|\n\n\n:::\n:::\n\n\nEach seller's probability is computed first and then averaged within a group.\nThe group's mean probability is the expected *fraction* of sellers in it that\nqualify --- not the probability that the group as a whole does. And the true\nfraction column exists only because this is a simulation; there is no such\ncolumn in a real rollout, which is the whole reason the probability is\ninteresting.\n\n::: {.callout-note collapse=\"true\" title=\"Region-level recovery, outcome by outcome\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_recovery %>%\n  transmute(Outcome = outcome, Region = region, n,\n            `True mean` = truth, Estimate = est,\n            `95% interval` = sprintf(\"[%.3f, %.3f]\", lo, hi),\n            `P(correct sign)` = p_correct_sign,\n            RMSE = rmse, `Sign accuracy` = sign_acc) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Outcome      |Region        |   n| True mean| Estimate|95% interval     | P(correct sign)|  RMSE| Sign accuracy|\n|:------------|:-------------|---:|---------:|--------:|:----------------|---------------:|-----:|-------------:|\n|gmv          |Clear benefit |  59|     0.225|    0.295|[0.210, 0.414]   |           1.000| 0.079|             1|\n|gmv          |Clear harm    | 138|    -0.175|   -0.133|[-0.174, -0.092] |           1.000| 0.047|             1|\n|seller_hours |Clear benefit |  59|    -0.231|   -0.231|[-0.272, -0.196] |           1.000| 0.004|             1|\n|seller_hours |Clear harm    | 138|     0.218|    0.208|[0.162, 0.257]   |           1.000| 0.019|             1|\n|complaint    |Clear benefit |  59|    -0.028|   -0.021|[-0.049, -0.002] |           0.992| 0.010|             1|\n|complaint    |Clear harm    | 138|     0.022|    0.023|[0.004, 0.050]   |           0.989| 0.009|             1|\n\n\n:::\n:::\n\n:::\n\nThe recovery table compares estimated and true effects in both regions.\nAcross its six outcome-region combinations, the estimated regional mean has\nthe correct sign in\n6 of\n6 cases. Seller-level sign accuracy ranges from\n100.0% to\n100.0% within these regions.\nThis describes point recovery in this simulation; the sampling checks below\ndetermine whether the intervals and probabilities are ready to interpret.\n\n### Sampler diagnostics and mixing\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  purrr::map_dfr(names(multi_att), ~ tibble::tibble(\n    Model = \"Joint fit\", Outcome = .x,\n    `R-hat (max)` = multi_att[[.x]]$rhat_max,\n    `Bulk ESS (min)` = multi_att[[.x]]$ess_min,\n    `Tail ESS (min)` = multi_att[[.x]]$ess_tail_min,\n    `Screen passed` = multi_att[[.x]]$ess_ok & multi_att[[.x]]$rhat_ok)),\n  purrr::map_dfr(names(multi_sep_att), ~ tibble::tibble(\n    Model = \"Separate fits\", Outcome = .x,\n    `R-hat (max)` = multi_sep_att[[.x]]$rhat_max,\n    `Bulk ESS (min)` = multi_sep_att[[.x]]$ess_min,\n    `Tail ESS (min)` = multi_sep_att[[.x]]$ess_tail_min,\n    `Screen passed` = multi_sep_att[[.x]]$ess_ok & multi_sep_att[[.x]]$rhat_ok))\n) %>%\n  kable(digits = 3, caption = \"Sampling diagnostics across event times for joint and separate fits.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Sampling diagnostics across event times for joint and separate fits.\n\n|Model         |Outcome      | R-hat (max)| Bulk ESS (min)| Tail ESS (min)|Screen passed |\n|:-------------|:------------|-----------:|--------------:|--------------:|:-------------|\n|Joint fit     |gmv          |       1.873|          5.823|         14.896|FALSE         |\n|Joint fit     |seller_hours |       1.604|          7.145|         16.522|FALSE         |\n|Joint fit     |complaint    |       1.126|         24.700|         44.559|FALSE         |\n|Separate fits |gmv          |       1.677|          6.575|         16.317|FALSE         |\n|Separate fits |seller_hours |       1.271|         11.240|         31.429|FALSE         |\n|Separate fits |complaint    |       1.149|         18.531|         60.943|FALSE         |\n\n\n:::\n:::\n\n\nRead that table before interpreting any probability in this section. Under\n@sec-longbet-sampler's screening rule ($\\hat{R} \\le 1.01$ and both bulk and tail\n$\\text{ESS} \\ge 400$),\n**0\nof 6 outcome fits pass** at this\nsampling budget. Across these rows, maximum $\\hat{R}$ ranges from\n1.126\nto 1.873,\nand minimum bulk ESS ranges from\n5.8\nto 24.7.\n\nFailures in separate continuous-outcome fits show that any sampling problem\ncannot be attributed solely to joint fitting or binary data. These diagnostics\ndo not identify its cause or establish stable seller rankings. More warmup and\nretained draws, checks of model specification, and investigation of the sampler\nmay be needed; no particular increase in sampling budget guarantees a remedy.\n\nUntil the relevant checks pass, the three-condition probabilities are\n**exploratory calculations from the retained draws**. Good point recovery on\nthis dataset does not validate their posterior uncertainty. Event-time ATT\nchecks are also only a first screen: seller-level joint events require their\nown sampling diagnostics before use in a decision.\n\n### What the joint fit bought, and what it cost\n\nWith that caveat attached, the comparisons between joint and marginal\napproaches are still instructive:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble::tibble(\n  Quantity = c(\"Joint three-condition probability\",\n               \"Product of this fit's marginals\",\n               \"Product of three separately fitted models\",\n               \"True fraction (simulation only)\"),\n  Mean = c(mean(multi_p_joint), mean(multi_p_product),\n           mean(multi_p_separate), mean(multi_truth_event)),\n  `Brier score` = c(mean((multi_p_joint - multi_truth_event)^2),\n                    mean((multi_p_product - multi_truth_event)^2),\n                    mean((multi_p_separate - multi_truth_event)^2), NA)\n) %>% kable(digits = 3, caption = \"Comparison of joint and factored screening probabilities.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparison of joint and factored screening probabilities.\n\n|Quantity                                  |  Mean| Brier score|\n|:-----------------------------------------|-----:|-----------:|\n|Joint three-condition probability         | 0.335|       0.051|\n|Product of this fit's marginals           | 0.345|       0.049|\n|Product of three separately fitted models | 0.314|       0.060|\n|True fraction (simulation only)           | 0.388|          NA|\n\n\n:::\n:::\n\n\nThe first comparison isolates dependence: `multi_p_product` uses the *same\nfit's* marginals and simply discards the pairing between draws. The mean\nabsolute seller-level difference is\n0.013, and the largest\nabsolute difference is\n0.129.\nTaking absolute differences before averaging prevents positive and negative\nseller differences from cancelling. This measures the effect of discarding\ndependence for this particular screen at exposure 8 in the retained draws;\nagreement here does not establish independence across outcomes or validate\neither probability while sampling remains unresolved.\n\nThe second comparison is with three completely separate models. Their mean\npass probability is 0.314, compared with\n0.335 for the joint fit, and the table reports\ntheir Brier scores against truth. Separate models do not share residual\ncovariance, so their fitted forests can partition variation differently.\nUnresolved Monte Carlo error can also contribute to these differences; this\nrun does not isolate those explanations.\n\n### Innovation correlation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(multi_CM, digits = 3, caption = \"Fitted innovation correlation matrix across outcomes.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Fitted innovation correlation matrix across outcomes.\n\n|             |   gmv| seller_hours| complaint|\n|:------------|-----:|------------:|---------:|\n|gmv          | 1.000|        0.600|     0.477|\n|seller_hours | 0.600|        1.000|     0.367|\n|complaint    | 0.477|        0.367|     1.000|\n\n\n:::\n:::\n\n\nThe generating innovation correlations were 0.60 for GMV with workload, 0.45\nfor GMV with the complaint latent, and 0.35 for workload with that latent.\nThe fitted model recovers all three with high fidelity:\n0.600 for GMV/workload,\n0.477 for GMV/complaint, and\n0.367 for workload/complaint.\n\nNote two cautions: entries involving `complaint` are correlations with the\n*latent* probit innovation, not with the observed 0/1 labels; and these are\ninnovation correlations within the same seller-week, not correlations between\nsellers' baseline levels or between their causal effects.\n\n::: {.callout-warning title=\"What this section does and does not establish\"}\nOne fitted dataset, 750 sellers, one data-generating process built to\nmake a teaching point. It demonstrates that the multi-outcome machinery computes\nwhat it claims to: the three-condition probability reproduces a manual draw\ncalculation exactly and respects the Fréchet bounds seller by seller; the\ninnovation covariance is recovered accurately; and the model detects signed,\nopposing effects across three distinct metrics. However, elevated $\\hat{R}$\ndiagnostics remind us that posterior uncertainty on this budget has not fully\nconverged across chains.\n:::\n\n\n::: {.callout-note title=\"Assumptions reminder: economic scenarios and joint decisions\"}\nTranslating causal estimates into business decisions requires maintaining a clear distinction\nbetween what is identified by the experiment and what is assumed by the business scenario:\n\n- **Annual economic valuations** assume a fixed baseline and an unobserved flat or decaying tail past the study window.\n- **Multi-outcome probabilities** depend on joint innovation correlations and posterior parameter exploration; passing ATT diagnostics does not guarantee that rare-event joint screens have converged.\n:::\n\n## Conclusion\n\nValuing a treatment requires choices about baseline revenue paths, decision horizons,\nand capacity constraints. In this chapter, we showed how posterior draws of dynamic\ntreatment effects can be combined with baseline estimates to score operational\ntargeting policies, preserving posterior dependence across sellers and draws.\nFurthermore, when decisions involve multiple trade-offs simultaneously, joint modeling\nvia seemingly unrelated regressions allows us to evaluate multi-condition probabilities\nthat factored independent models cannot pin down.\n\nBoth the economic scenario and the multi-outcome model require ongoing scrutiny.\nAssumed annual tails are not identified forecasts, and elevated $\\hat{R}$ diagnostics\nindicate where sampling requires careful investigation before treating decision\nsummaries as settled. In **[LongBet: Forecasting, Observational Panels, and Diagnostics](longbet_extensions.qmd)**,\nwe examine how LongBet projects treatment trajectories beyond the trial window, how\nit behaves when randomization is absent, and how to assess its operating characteristics.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}