{
  "hash": "e96ec8ca04b6d0218e9f0c783caee851",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Ordinal Regression with BART and the Cloglog Link\"\nshare:\n  permalink: \"https://book.martinez.fyi/phobart.html\"\n  description: >-\n    Ordinal regression with Bayesian Additive Regression Trees (BART) using\n    the complementary log-log link to model non-linearities, interactions,\n    and avoid cutpoint constraints.\n  linkedin: true\n  email: true\n  mastodon: true\nauthor:\n  - name: Entejar Alam \n  - name: Ignacio Martinez  \n---\n\n## Ordinal Outcomes in Business\n\nMany of the outcomes we care about most in industry are ordered, but not\nnumeric. Customer satisfaction is measured on a five-point Likert scale (one\nto five stars), Net Promoter Score (NPS) responses fall into detractor,\npassive, and promoter buckets, credit files are graded, and support tickets are\ntriaged into severity tiers. While practitioners often treat these ratings as\ncontinuous numbers by averaging them, doing so imposes an unverifiable cardinal\nscale that assumes equal distances between categories and can produce severe\ndistortions (@liddell2018analyzing). Rather than modeling raw scores with linear\nregression, standard Bayesian models for ordinal data rely on ordered probit\nand ordered logit (cumulative-link) models. These are a good starting point,\nbut they carry two assumptions that are easy to overlook and frequently wrong:\n\n1.  **Linearity and additivity.** Predictors are assumed to impact a latent\n    scale linearly, with no interactions unless we hand-specify them. For\n    example, if a product change delights power users but frustrates newcomers,\n    a linear model averages these out, reporting a misleading effect that\n    describes neither group.\n2.  **Ordered cutpoints in Gibbs sampling.** Cumulative-link models rely on\n    estimating thresholds ($c_1 < \\dots < c_{K-1}$) that must remain strictly\n    ordered. While Hamiltonian Monte Carlo (e.g., in Stan) handles ordered\n    cutpoints in parametric models via monotonic transformations, Gibbs\n    samplers—the standard engine for tree ensembles like BART—struggle with\n    strong posterior dependencies among constrained cutpoints, which\n    significantly degrades MCMC mixing and slows down convergence (@cowles1996).\n\nIn previous chapters, we saw how BART (@chipman2010bart) relaxes the first\nassumption for continuous outcomes, discovering non-linearities and\ninteractions on its own. This chapter extends that flexibility to ordinal\noutcomes, utilizing the framework from @alam2025unified to eliminate the second\nassumption as well.\n\n\n## The Cloglog Link and PHOBART\n\nThe fix starts with the link function. Instead of probit or logit, we use the\ncomplementary log-log (cloglog) link,\n$$\ng(p) = \\log\\{-\\log(1 - p)\\}.\n$$\nIt is the only link under which the two standard formulations of ordinal\nregression, cumulative-link and continuation-ratio, coincide\n(@laara1985equivalence). For an outcome with $K$ ordered categories\n$Y_i \\in \\{1, \\dots, K\\}$, @alam2025unified write the model in cumulative form:\n$$\n\\text{cloglog}(\\Pr(Y_i \\le k \\mid X_i = x)) = c_k + \\lambda(x),\n$$\nor equivalently in discrete proportional-hazards form,\n$$\n\\Pr(Y_i > k \\mid X_i = x) = \\{S_0(k)\\}^{e^{-\\lambda(x)}},\n$$\nwhere $\\lambda(x)$ is assigned a BART sum-of-trees prior. This yields a\n**proportional hazards ordinal BART** model (**PHOBART**).\n\nUnlike the symmetric probit and logit links, the cloglog link is asymmetric:\nthe cumulative probability approaches 0 and 1 at different rates on the latent\nscale. This asymmetry is advantageous when extreme rating categories behave\nasymmetrically in probability space, while BART's tree ensemble is responsible\nfor discovering non-linear threshold effects and interactions across covariates\n$X$.\n\nPHOBART also elegantly resolves the cutpoint constraint issue. The strictly\nordered cutpoints $c_k$ are reparameterized through unconstrained parameters\n$\\gamma_j \\in \\mathbb{R}$ via:\n$$\nc_k = \\log \\sum_{j \\le k} e^{\\gamma_j}, \\qquad k = 1, \\dots, K-1.\n$$\nBecause the exponential is strictly positive, the ordering\n$c_1 < c_2 < \\dots < c_{K-1}$ holds by construction. Furthermore, because the\ninverse cloglog link is the CDF of an exponential distribution, augmenting each\nobservation with a truncated-exponential latent variable allows the sampler to\nupdate the unconstrained parameters and the tree ensemble using standard\nconjugate and Gibbs updates. While the sampler works on the unconstrained\nscale, the package returns the transformed cutpoints $c_k$.\n\nUnder suitable Hölder smoothness and sparsity conditions on the latent\nregression function $\\lambda(x)$, @alam2025unified prove that PHOBART achieves\nminimax-optimal posterior contraction rates (up to logarithmic factors),\nguaranteeing that the posterior concentrates around the true data-generating\nprocess at the optimal statistical rate.\n\nThe same latent-exponential machinery unifies ordinal, survival, and density\nregression under one framework. In the practical example below, our code targets\n`stochtree` version `0.5.x`. \n\n\n## A Business Example: A Feature Change and Customer Satisfaction\n\nSuppose we roll out a product change and measure its effect on a one-to-five\nsatisfaction rating. Our concern is heterogeneity: we suspect the change helps\nsome customers and hurts others depending on how engaged they were to begin\nwith. If we are right, a linear ordered probit will average those opposing\neffects into something misleading, and we could ship (or kill) the feature for\nthe wrong reason.\n\nTo see this cleanly, we simulate data where we know the truth. Let `x1` be a\ncentered engagement score and `t` the feature flag. The latent satisfaction `z`\nis defined as\n$$\nz = 1.5 \\sin\\!\\left(\\frac{\\pi\\, x_1}{2}\\right) + \\tau(x_1)\\, t + \\epsilon,\n\\qquad \\epsilon \\sim \\mathcal{N}(0, 0.8^2),\n$$\nwhere the feature's effect $\\tau(x_1)$ is $+1.5$ for engaged customers\n($x_1 > 0$) and $-1.0$ for less-engaged ones ($x_1 \\le 0$). This construction\ninduces both a non-linear baseline effect through the sine function and\nheterogeneous treatment effects whose sign depends on $x_1$. \n\nThe observed ordinal outcome is generated by discretizing $z$ into a\nfive-point Likert scale using fixed thresholds. Because treatment $t$ is\nassigned completely at random ($t \\sim \\text{Bernoulli}(0.5)$) independent of\n$x_1$, causal identification (unconfoundedness and overlap) holds by design.\nThis isolates the comparison entirely to the functional form: whether each\nmodel can accurately discover the non-linear response surface and subgroup\nheterogeneity. The latent noise is Gaussian, which favors the probit benchmark\nin terms of link specification.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(stochtree)\nlibrary(brms)\nlibrary(coda)\nlibrary(knitr)\n\nset.seed(1982)\nN <- 2500\n\nfake_data <- tibble(\n  x1 = runif(N, -2, 2),\n  t  = sample(c(0, 1), N, replace = TRUE)\n) %>%\n  mutate(\n    f_x    = 1.5 * sin(pi * x1 / 2),\n    tau_x  = ifelse(x1 > 0, 1.5, -1.0),\n    z_true = f_x + tau_x * t + rnorm(N, 0, 0.8),\n    y = case_when(\n      z_true <  -1.5 ~ 1,\n      z_true <  -0.5 ~ 2,\n      z_true <   0.5 ~ 3,\n      z_true <   1.5 ~ 4,\n      TRUE           ~ 5\n    )\n  )\n\n# Verify all five rating categories are well-populated\ntable(fake_data$y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   3   4   5 \n622 459 373 355 691 \n```\n\n\n:::\n:::\n\n\nWe then compute the *true* population effect of the feature on each rating\nlevel by integrating over the counterfactuals (feature off vs. feature on) for\nevery customer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntruth_ate <- fake_data %>%\n  mutate(z0 = f_x, z1 = f_x + tau_x) %>%\n  mutate(\n    p0_1 = pnorm(-1.5, z0, 0.8),\n    p0_2 = pnorm(-0.5, z0, 0.8) - pnorm(-1.5, z0, 0.8),\n    p0_3 = pnorm( 0.5, z0, 0.8) - pnorm(-0.5, z0, 0.8),\n    p0_4 = pnorm( 1.5, z0, 0.8) - pnorm( 0.5, z0, 0.8),\n    p0_5 = 1 - pnorm(1.5, z0, 0.8),\n    p1_1 = pnorm(-1.5, z1, 0.8),\n    p1_2 = pnorm(-0.5, z1, 0.8) - pnorm(-1.5, z1, 0.8),\n    p1_3 = pnorm( 0.5, z1, 0.8) - pnorm(-0.5, z1, 0.8),\n    p1_4 = pnorm( 1.5, z1, 0.8) - pnorm( 0.5, z1, 0.8),\n    p1_5 = 1 - pnorm(1.5, z1, 0.8)\n  ) %>%\n  summarise(across(starts_with(\"p0_\") | starts_with(\"p1_\"), mean)) %>%\n  pivot_longer(everything(), names_to = c(\"group\", \"y\"), names_sep = \"_\") %>%\n  pivot_wider(names_from = group, values_from = value) %>%\n  mutate(y = as.integer(y), tau = p1 - p0)\n\nkable(\n  truth_ate,\n  digits = 3,\n  col.names = c(\"Rating (y)\", \"P(Y=y | t=0)\", \"P(Y=y | t=1)\", \"True ATE (tau)\")\n)\n```\n\n::: {.cell-output-display}\n\n\n| Rating (y)| P(Y=y &#124; t=0)| P(Y=y &#124; t=1)| True ATE (tau)|\n|----------:|-----------------:|-----------------:|--------------:|\n|          1|             0.148|             0.357|          0.209|\n|          2|             0.238|             0.129|         -0.109|\n|          3|             0.247|             0.037|         -0.211|\n|          4|             0.226|             0.066|         -0.160|\n|          5|             0.141|             0.412|          0.270|\n\n\n:::\n:::\n\n\n### BART Model Fitting (PHOBART)\n\nWe fit the PHOBART model using `stochtree::bart()` with an `OutcomeModel`\nspecifying `outcome = \"ordinal\"` and `link = \"cloglog\"` inside\n`general_params`. We also configure key hyperparameters:\n\n- `sample_sigma2_global = FALSE`: Ordinal outcomes do not have a free Gaussian\n  residual variance $\\sigma^2$ because scale is fixed by the link function.\n- `random_seed = 2025`: In `stochtree`, MCMC sampling randomness is controlled\n  via `random_seed` inside `general_params` rather than base R's `set.seed()`.\n- `mean_forest_params = list(num_trees = 50, sample_sigma2_leaf = FALSE)`:\n  Configures 50 trees with leaf variance sampling disabled for stronger\n  regularization.\n- `num_gfr = 0`: Runs standard MCMC sampling from initialization.\n\nWe run a single MCMC chain here for brevity and monitor ESS and trace plots; in\nproduction settings, one can set `num_chains` in `stochtree::bart()` to assess\nconvergence diagnostics such as $\\hat{R}$ across multiple independent chains\nalongside ESS.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX_train <- fake_data %>% select(x1, t) %>% as.matrix()\ny_train <- fake_data$y\n\nX0 <- X_train; X0[, \"t\"] <- 0\nX1 <- X_train; X1[, \"t\"] <- 1\n\nphobart <- bart(\n  X_train = X_train,\n  y_train = y_train,\n  X_test  = rbind(X0, X1),\n  num_gfr = 0,\n  num_burnin = 1000,\n  num_mcmc   = 1000,\n  general_params = list(\n    sample_sigma2_global = FALSE,\n    random_seed = 2025,\n    outcome_model = OutcomeModel(outcome = \"ordinal\", link = \"cloglog\")\n  ),\n  mean_forest_params = list(num_trees = 50, sample_sigma2_leaf = FALSE)\n)\n```\n:::\n\n\n### Checking convergence\n\nBefore trusting the estimates, we check that the MCMC sampler has mixed well.\nCutpoint draws are extracted via\n`extractParameter(phobart, \"cloglog_cutpoints\")`, returning a matrix of shape\n$(K-1, S)$ containing draws of $c_k$.\n\nBecause the tree ensemble $\\lambda(x)$ can absorb an arbitrary global shift\n(an implicit intercept), raw cutpoint draws $c_k$ and the forest predictions\nshare a non-identifiable additive constant. If unadjusted, raw cutpoints can\ndrift even in a well-converged chain, yielding a misleadingly low Effective\nSample Size (ESS). To evaluate convergence on a strictly identified quantity,\nwe shift the cutpoints by the per-sample mean of the training predictions,\n$\\bar{\\lambda}_{\\text{train}} = \\frac{1}{N}\\sum_{i=1}^N \\lambda(X_i)$, tracing\n$c_2 + \\bar{\\lambda}_{\\text{train}}$. (Note that this shift automatically\ncancels when computing counterfactual contrast probabilities.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncutpoint_draws <- extractParameter(phobart, \"cloglog_cutpoints\")\nlambda_train   <- predict(\n  phobart, X_train, scale = \"linear\", terms = \"y_hat\", type = \"posterior\"\n)\n\n# Shift cutpoints by the mean training latent prediction\nadj_c2 <- cutpoint_draws[2, ] + colMeans(lambda_train)\n\ntibble(\n  iteration = seq_along(adj_c2),\n  c2_adj    = adj_c2\n) %>%\n  ggplot(aes(iteration, c2_adj)) +\n  geom_line(color = \"blue\", alpha = 0.6) +\n  labs(\n    title = \"Trace plot for the second cutpoint (intercept-adjusted)\",\n    x = \"Iteration\",\n    y = expression(c[2] + bar(lambda)[train])\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](phobart_files/figure-html/traceplot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"ESS for adjusted c_2:\", round(effectiveSize(adj_c2), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nESS for adjusted c_2: 104.6 \n```\n\n\n:::\n:::\n\n\nThe trace looks stationary with no drift or sticking, and the ESS is healthy,\nconfirming adequate posterior exploration. In practice, you would inspect the\nremaining thresholds and tree ensemble predictions similarly.\n\n### Turning the posterior into category probabilities\n\nInstead of manually evaluating the link algebra, `stochtree` provides a direct\naccessor:\n`predict(..., scale = \"probability\", terms = \"y_hat\", type = \"posterior\")`\nreturns an array of dimension\n$(\\text{observations}, \\text{categories}, \\text{samples})$.\nAveraging over observations yields the population-level category probabilities\nfor each posterior draw.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predict category probabilities: returns (observations, categories, samples)\nprobs0 <- predict(\n  phobart, X0, scale = \"probability\", terms = \"y_hat\", type = \"posterior\"\n)\nprobs1 <- predict(\n  phobart, X1, scale = \"probability\", terms = \"y_hat\", type = \"posterior\"\n)\n\n# Average over observations to get population category probabilities per sample\npop0_phobart <- t(apply(probs0, c(2, 3), mean)) # samples x categories\npop1_phobart <- t(apply(probs1, c(2, 3), mean))\n\ntau_phobart <- as_tibble(\n  pop1_phobart - pop0_phobart,\n  .name_repair = ~ paste0(\"V\", seq_along(.x))\n) %>%\n  mutate(draw = row_number()) %>%\n  pivot_longer(-draw, names_to = \"y\", values_to = \"tau\") %>%\n  mutate(y = as.integer(sub(\"V\", \"\", y)))\n```\n:::\n\n\n### Benchmark: linear ordered probit\n\nTo benchmark our approach, we fit a Bayesian linear ordered probit model with\n`brms`, to see how it performs when the true relationship is non-linear and\nincludes interactions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\"cache\", showWarnings = FALSE)\n\nprobit_lm <- brm(\n  y ~ x1 + t,\n  data    = fake_data %>% mutate(y = ordered(y)),\n  family  = cumulative(\"probit\"),\n  chains  = 4, cores = 4, iter = 2000, refresh = 0,\n  seed    = 2025,\n  file    = \"cache/probit_lm\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# posterior_epred returns draws x observations x categories for ordinal families\nep0 <- posterior_epred(\n  probit_lm,\n  newdata = fake_data %>% mutate(t = 0, y = ordered(y))\n)\nep1 <- posterior_epred(\n  probit_lm,\n  newdata = fake_data %>% mutate(t = 1, y = ordered(y))\n)\n\npop0_probit <- apply(ep0, c(1, 3), mean)   # draws x categories\npop1_probit <- apply(ep1, c(1, 3), mean)\n\ntau_probit <- as_tibble(\n  pop1_probit - pop0_probit,\n  .name_repair = ~ paste0(\"V\", seq_along(.x))\n) %>%\n  mutate(draw = row_number()) %>%\n  pivot_longer(-draw, names_to = \"y\", values_to = \"tau\") %>%\n  mutate(y = as.integer(sub(\"V\", \"\", y)))\n```\n:::\n\n\n### Comparison of Average Treatment Effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsumm <- function(df, model) {\n  df %>% group_by(y) %>%\n    summarise(val  = median(tau),\n              low  = quantile(tau, 0.025),\n              high = quantile(tau, 0.975), .groups = \"drop\") %>%\n    mutate(Model = model)\n}\n\nbind_rows(summ(tau_phobart, \"PHOBART\"), summ(tau_probit, \"Linear Probit\")) %>%\n  ggplot(aes(factor(y), val, color = Model)) +\n  geom_linerange(aes(ymin = low, ymax = high), linewidth = 1,\n                 position = position_dodge(0.5)) +\n  geom_point(size = 3, position = position_dodge(0.5)) +\n  geom_point(data = truth_ate, aes(factor(y), tau, color = \"Truth\"),\n             size = 4, shape = 4, stroke = 1.5, inherit.aes = FALSE) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", alpha = 0.5) +\n  scale_color_manual(\n    values = c(\n      \"PHOBART\"       = \"#0072B2\",\n      \"Linear Probit\" = \"#D55E00\",\n      \"Truth\"         = \"#000000\"\n    )\n  ) +\n  labs(\n    title = \"Effect of the feature on each rating level\",\n    subtitle = paste0(\n      \"The linear model averages away the sign-flipping heterogeneity\"\n    ),\n    x = \"Rating (1–5)\",\n    y = \"Change in probability\"\n  ) +\n  theme_bw() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Comparison of average treatment effect estimates across models against the ground truth.](phobart_files/figure-html/fig-ate-comparison-1.png){#fig-ate-comparison width=960}\n:::\n:::\n\n\n- **Rating 1 (1 Star):** The linear probit estimates a small decrease in 1-star\n  ratings. The true latent shift averages to $0.5(1.5) + 0.5(-1.0) = 0.25$, so\n  the linear model estimates a slightly positive treatment coefficient\n  ($\\hat{\\beta}_t \\approx 0.24$), forcing the modeled probability of the lowest\n  category to fall. In reality, the harmed subgroup ($x_1 \\le 0$) is pushed\n  below the $-1.5$ threshold, causing 1-star reviews to *increase*. The linear\n  model commits a dangerous **sign error** on the company's most dissatisfied\n  customers.\n- **Ratings 2, 3, and 4:** Under the true data-generating process, probability\n  mass drains out of the middle ratings as customers polarize toward the\n  extremes. The linear probit predicts negligible changes across these tiers,\n  missing the hollowed-out middle.\n- **Rating 5 (5 Stars):** Both models detect an increase in 5-star ratings, but\n  PHOBART accurately quantifies the large positive surge driven by delighted\n  power users ($x_1 > 0$).\n- **Overall:** PHOBART flexibly recovers the full U-shaped polarization across\n  all five categories, tracking the ground truth closely.\n\n## Why These Results Matter\n\nIn this data-generating process, the treatment effect is heterogeneous: it is\npositive for individuals with $x_1 > 0$ and negative for those with\n$x_1 \\le 0$. A linear ordinal probit model is forced to represent this\nstructure using a single treatment coefficient, which leads to biased\npopulation-level estimates when effects cancel out across subgroups.\n\nThe linear model's failure here is not subtle: it tells leadership that angry\nreviews are dropping when they are actually spiking. The PHOBART model correctly\nidentifies both the non-linear baseline relationship between $x_1$ and the\noutcome and the interaction between $x_1$ and treatment. By combining the\nflexibility of BART with the computational advantages of the cloglog link, it\naccurately recovers the true average treatment effects across all ordinal\ncategories. This is the practical payoff: when an intervention helps some\ncustomers and hurts others, only the flexible model tells you so.\n\n### Decision-Making Under Polarization: What to Do Monday Morning\n\nThe core business dynamic demonstrated here is **customer polarization**: the\nfeature simultaneously manufactures both promoters (4–5 stars) and detractors\n(1 star). In customer experience management and Net Promoter Score (NPS)\nframeworks, a release that polarizes the user base can leave headline summary\nmetrics—such as mean star ratings or net scores—looking modestly positive or\nunmoved, while masking severe customer churn among vulnerable cohorts.\n\nBecause Bayesian models produce posterior draws across the full probability\ndistribution, we can directly query the posterior for decision-relevant\nprobabilities:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute promoter and detractor comparisons\nprob_prom_probit <- mean(\n  (pop1_probit[, 4] + pop1_probit[, 5]) > (pop0_probit[, 4] + pop0_probit[, 5])\n)\nprob_detr_probit <- mean(pop1_probit[, 1] > pop0_probit[, 1])\nprob_pol_probit  <- mean(\n  ((pop1_probit[, 4] + pop1_probit[, 5]) >\n   (pop0_probit[, 4] + pop0_probit[, 5])) &\n  (pop1_probit[, 1] > pop0_probit[, 1])\n)\n\nprob_prom_phobart <- mean(\n  (pop1_phobart[, 4] + pop1_phobart[, 5]) >\n  (pop0_phobart[, 4] + pop0_phobart[, 5])\n)\nprob_detr_phobart <- mean(pop1_phobart[, 1] > pop0_phobart[, 1])\nprob_pol_phobart  <- mean(\n  ((pop1_phobart[, 4] + pop1_phobart[, 5]) >\n   (pop0_phobart[, 4] + pop0_phobart[, 5])) &\n  (pop1_phobart[, 1] > pop0_phobart[, 1])\n)\n\ndecision_summary <- tibble(\n  `Business Question` = c(\n    \"Pr(Share of 4–5 star ratings [Promoters] increased)\",\n    \"Pr(Share of 1-star ratings [Detractors] increased)\",\n    \"Pr(Polarization: Both 1-star and 4–5 star ratings increased)\"\n  ),\n  `Linear Probit` = sprintf(\n    \"%.1f%%\",\n    100 * c(prob_prom_probit, prob_detr_probit, prob_pol_probit)\n  ),\n  `PHOBART` = sprintf(\n    \"%.1f%%\",\n    100 * c(prob_prom_phobart, prob_detr_phobart, prob_pol_phobart)\n  )\n)\n\nkable(\n  decision_summary,\n  col.names = c(\"Decision-Relevant Question\", \"Linear Probit\", \"PHOBART\")\n)\n```\n\n::: {.cell-output-display}\n\n\n|Decision-Relevant Question                                   |Linear Probit |PHOBART |\n|:------------------------------------------------------------|:-------------|:-------|\n|Pr(Share of 4–5 star ratings [Promoters] increased)          |85.2%         |100.0%  |\n|Pr(Share of 1-star ratings [Detractors] increased)           |14.8%         |100.0%  |\n|Pr(Polarization: Both 1-star and 4–5 star ratings increased) |0.0%          |100.0%  |\n\n\n:::\n:::\n\n\nLooking at these results on Monday morning completely alters the executive\ndecision:\n\n- **The Linear Model's Blind Spot:** The linear probit reports an 85.2%\n  posterior probability that promoters increased, but only a 14.8% probability\n  that detractors increased, and **0.0% probability** of customer polarization\n  (both extremes increasing simultaneously). Because standard cumulative-link\n  models impose monotonic global shifts from a single parameter, they are\n  mathematically incapable of detecting simultaneous increases at both\n  extremes. Relying on this model, leadership would greenlight a full 100%\n  rollout, unaware that they are actively alienating newer users.\n- **The Nonparametric Prescription:** PHOBART reveals near certainty that\n  top ratings increased *and* near certainty that 1-star ratings spiked. Rather\n  than a simplistic \"ship or kill\" verdict, this enables targeted action:\n  1. **Cohort-Gated Rollout:** Ship the feature immediately to power users and\n     highly engaged accounts ($x_1 > 0$) who experience clear value.\n  2. **Product Redesign for Onboarding:** Investigate why less-engaged\n     customers ($x_1 \\le 0$) struggle with the update, iterating on UI\n     guidance and onboarding workflows before widening exposure.\n\n## Conclusion\n\nThis example illustrates the practical value of a unified Bayesian\nnonparametric framework: it is easier to implement because it avoids cutpoint\nconstraints, and more accurate because it adapts automatically to complex\nstructure in the data.\n\nThe usual cautions apply. The causal reading rests on the standard\nassumptions, unconfoundedness and adequate overlap between treated and control\nunits, which no model supplies on its own; when treatment is not randomized,\nincluding a propensity score as an additional covariate can mitigate\nregularization-induced confounding (@hahn2020bayesian), though causal\nidentification ultimately depends on unconfoundedness and adequate overlap.\nThe proportional-hazards version assumes the covariate effect does not interact\nwith the rating level; the non-proportional variant (NPHOBART) relaxes this at\nsome computational cost. @alam2025unified develop PHOBART and NPHOBART for\nordinal regression and note that sharing forests, in the spirit of\n@hahn2020bayesian, is a natural route to richer causal estimation.\n\n::: {.callout-tip}\n## Learn more\nFor the theoretical framework, minimax posterior contraction proofs, and\nextensions to non-proportional hazards ordinal regression (NPHOBART), see\n@alam2025unified, *A unified Bayesian nonparametric framework for ordinal,\nsurvival, and density regression using the complementary log-log link*\n([arXiv:2502.00606](https://arxiv.org/abs/2502.00606)).\n:::\n\n## Appendix: Session Information\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.1 (2026-06-24)\nPlatform: x86_64-pc-linux-gnu\nRunning under: Ubuntu 24.04.4 LTS\n\nMatrix products: default\nBLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 \nLAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0\n\nlocale:\n [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              \n [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    \n [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   \n [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 \n [9] LC_ADDRESS=C               LC_TELEPHONE=C            \n[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       \n\ntime zone: Etc/UTC\ntzcode source: system (glibc)\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] knitr_1.51      coda_0.19-4.1   brms_2.23.0     Rcpp_1.1.2     \n[5] stochtree_0.4.5 tidyr_1.3.2     dplyr_1.2.1     ggplot2_4.0.3  \n\nloaded via a namespace (and not attached):\n [1] tensorA_0.36.2.1     bridgesampling_1.2-1 generics_0.1.4      \n [4] stringi_1.8.9        lattice_0.22-9       digest_0.6.39       \n [7] magrittr_2.0.5       evaluate_1.0.5       grid_4.6.1          \n[10] RColorBrewer_1.1-3   mvtnorm_1.4-2        fastmap_1.2.0       \n[13] jsonlite_2.0.0       Matrix_1.7-5         pkgbuild_1.4.8      \n[16] backports_1.5.1      gridExtra_2.3.1      Brobdingnag_1.2-9   \n[19] purrr_1.2.2          QuickJSR_1.10.0      scales_1.4.0        \n[22] codetools_0.2-20     abind_1.4-8          cli_3.6.6           \n[25] rlang_1.3.0          withr_3.0.3          yaml_2.3.12         \n[28] otel_0.2.0           StanHeaders_2.32.10  inline_0.3.21       \n[31] rstan_2.32.7         tools_4.6.1          parallel_4.6.1      \n[34] rstantools_2.7.0     checkmate_2.3.4      vctrs_0.7.3         \n[37] posterior_1.7.0      R6_2.6.1             stats4_4.6.1        \n[40] matrixStats_1.5.0    lifecycle_1.0.5      stringr_1.6.0       \n[43] htmlwidgets_1.6.4    pkgconfig_2.0.3      RcppParallel_6.2.0  \n[46] pillar_1.11.1        gtable_0.3.6         loo_2.10.1          \n[49] glue_1.8.1           xfun_0.60            tibble_3.3.1        \n[52] tidyselect_1.2.1     farver_2.1.2         bayesplot_1.15.0    \n[55] htmltools_0.5.9      nlme_3.1-169         labeling_0.4.3      \n[58] rmarkdown_2.31       compiler_4.6.1       S7_0.2.2            \n[61] distributional_0.8.1\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "phobart_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}