{
  "hash": "107fdccf7a81288fc71db8044e43a1f6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bayesian Adaptive Design\"\nsubtitle: >-\n  Contextual Multi-Armed Bandits with Multivariate Bayesian\n  Causal Forests\ndescription: \"A response-adaptive experiment that routes each customer to their highest net-value retention offer while it is still running, built on multivariate Bayesian Causal Forests, with a replicated simulation of what adaptive allocation does and does not buy.\"\nshare:\n  permalink: \"https://book.martinez.fyi/bad.html\"\n  description: \"Bayesian adaptive design: contextual bandits with multivariate BCF\"\n  linkedin: true\n  email: true\n  mastodon: true\n---\n\n## The Business Dilemma: The Cancellation Desk\n\n<img src=\"img/bad.jpeg\" align=\"right\" height=\"280\" alt=\"Bayesian Adaptive Design: a stream of arriving customers is routed up four branches of a tree, each branch carrying a different share of traffic to a different retention offer\" />\n\nImagine you are the Principal Data Scientist at a subscription-based\nplatform—whether a streaming service, an enterprise SaaS tool, or a\ncloud developer product. Every week, roughly **500 paying\nsubscribers** contact customer support or enter the cancellation\nflow intending to terminate their subscription.\n\nCustomer churn is the silent killer of recurring-revenue business\nmodels. To combat this, your Customer Success and Growth teams have\nbrainstormed **four candidate actions (a control and three active\ntreatments)**:\n\n1. **Arm 0: Control (Standard Exit)**: Standard cancellation survey\n   and polite exit interview. No financial incentive or special\n   intervention. Cost = **$0**.\n2. **Arm 1: Bill Credit / Discount**: A $5 billing credit on their\n   upcoming invoice. Highly effective for price-sensitive,\n   long-tenure subscribers who have lower recent platform usage.\n   Cost = **$5**.\n3. **Arm 2: Premium Feature Upgrade**: A complimentary 2-month\n   upgrade to the advanced feature tier. Highly effective for\n   heavy-usage subscribers early in their customer lifecycle who are\n   bumping against product limits. Cost = **$8**.\n4. **Arm 3: Proactive Onboarding Assist**: A 1-on-1 technical setup\n   and onboarding session. Highly effective for brand-new\n   subscribers with low initial engagement who are struggling to\n   adopt the product. Cost = **$2**.\n\nHere is the central challenge: **The optimal retention offer is\ncompletely different for different customers, but on Week 1, you\nhave zero empirical information about what works for whom.**\n\n---\n\n## What \"Adaptive Design\" Means in This Chapter\n\nAn adaptive design is an experiment whose rules for what to do next\nare fixed in advance but depend on the data collected so far. The\nfamily is broad. Interim analyses can stop a trial early for success\nor futility, drop arms that are clearly losing, re-estimate the\nsample size, or—the branch this chapter is about—shift the\nprobability of assignment toward arms that are doing well, which is\ncalled **response-adaptive randomization**. What makes a design\n*Bayesian* is that those rules are driven by posterior quantities:\nthe posterior probability that an arm is best, or a posterior draw\nof its effect.\n\nThis chapter builds one specific member of that family and follows\nit end to end: a response-adaptive experiment in which the\nallocation probabilities depend not only on the accumulating\noutcomes but on each customer's covariates, so that different\ncustomers are steered toward different arms. In machine-learning\nlanguage this is a **contextual bandit**; in the evaluation\nliterature it is the \"what works for whom\" design of\n@finucane2018works. The trial runs for a fixed ten weeks with no\nearly-stopping rule, and one allocation rule—Thompson sampling with\nan exploration floor—is used throughout. That scope matters. The\nlessons below, about propensities, exploration floors, and what\nadaptive allocation does and does not buy, are about this design,\nnot a verdict on adaptive designs in general.\n\n---\n\n## The Economic Objective: Net Value, Not Just Raw Retention\n\nIt is tempting to define success as the retention rate. But in\nbusiness data science, **interventions have real marginal costs**,\nand an offer that saves a customer for more than that customer is\nworth has not succeeded.\n\nSuppose each successfully retained subscriber represents **$25 in\nNet Customer Lifetime Value (LTV)**. If an expensive $8 feature\nupgrade increases a customer's retention probability by only 10\npercentage points, its expected gross uplift value is:\n\n$$\n\\mathbb{E}[\\text{Uplift Value}] = 0.10 \\times \\$25 = \\$2.50\n$$\n\nBecause the treatment costs $8.00, deploying it to that customer\nproduces a **net loss of $5.50 per customer treated**.\n\nTherefore, the rational business objective is not merely to maximize\nretention probability, but to maximize **Incremental Net Economic\nValue**:\n\n$$\n\\text{Net Value}_k(X) = \\tau_k(X) \\times \\text{LTV} - \\text{Cost}_k\n$$\n\nWhere:\n\n- $\\tau_k(X) = \\mathbb{E}[Y(k) - Y(0) \\mid X]$ is the Conditional\n  Average Treatment Effect (CATE) of arm $k$ relative to Control:\n  the uplift in retention probability, in percentage points.\n- $\\text{LTV}$ is the monetary value of saving a customer ($25).\n- $\\text{Cost}_k$ is the direct operational cost of treatment $k$\n  ($0, $5, $8, and $2, respectively).\n\nNotice that for Arm 0 (Control), $\\tau_0(X) \\equiv 0$ and\n$\\text{Cost}_0 = \\$0$, yielding a baseline net value of $\\$0$. If\nevery active treatment produces a negative net value for a customer,\nthe cost-effective decision is to do nothing (Control).\n\nTwo simplifications are baked into this objective, and both are\nworth stating out loud because the simulation below inherits them.\nEvery saved customer is worth the same $25, regardless of who they\nare, and the cost of an offer is incurred for every customer it is\nmade to, whether or not they stay. Neither is essential to the\nmethod: an LTV that varies with $X$, or a cost that is only paid\nwhen the customer is retained, changes the arithmetic inside the\n$\\arg\\max$ but not the logic of anything that follows.\n\n---\n\n## The Three-Way Strategic Showdown\n\nWhen designing an experimentation strategy for this problem, data\nscience teams typically choose between three approaches:\n\n| | **1. Static RCT** | **2. Global MAB** | **3. BCF Thompson Sampling** |\n|---|---|---|---|\n| **Allocation** | Fixed 25% per arm, for the whole run | Adapts, but pools every customer together | Adapts per customer, on their covariates |\n| **What it learns** | Data on every arm for every kind of customer, free of assignment bias | A single population-average winner | The full CATE surface $\\tau_k(X)$ |\n| **In-trial cost** | High regret throughout | Converges fast, then exploits | Pays to explore first, profits later |\n| **Failure mode** | Burns revenue for the entire trial | Starves the segments it did not crown | Buys its model with in-trial revenue; can trail a simple bandit for weeks |\n| **What you own at the end** | Data, and a model you still have to fit | One winning arm | A deployable personalized policy |\n\n: Three candidate experimentation strategies {tbl-colwidths=\"[16,21,21,21]\"}\n\n### 1. Static RCT Baseline (Uniform 25% Allocation)\nIn a fixed, equal-allocation A/B/C/D test, you divide incoming\ntraffic equally (125 callers per arm each week) for a fixed period\n(e.g., 10 weeks). Every caller has one best arm, and a uniform coin\nflip gives it to them 25% of the time, so for the entire ten weeks\nthree callers in four receive an offer that is not their best one.\nStatistically straightforward; commercially expensive. We put\na precise price on it below.\n\n### 2. Global (Non-Contextual) Multi-Armed Bandit\nProduct teams often ask: *\"Why not just run an off-the-shelf\nmulti-armed bandit?\"* The version we simulate is the textbook one,\nBeta-Bernoulli Thompson sampling on each arm's retention rate, with\ncosts subtracted before arms are compared. When treatment effects\nare heterogeneous, **a global bandit suffers from a winner-takes-all\nfailure mode**. It pools all customers together and converges to\nwhichever single arm has the best *population-average* net value.\nIn the simulation below that turns out to be Arm 3, the cheap\nOnboarding Assist — a perfectly sensible average bet, which is\nexactly what makes the failure mode so hard to spot on a dashboard.\nHaving crowned it, the bandit hands Onboarding to nearly every\ncaller: long-tenure price-sensitive subscribers never see the credit\nthat would have kept them, power users bumping against feature\nlimits never get the upgrade, and the sizeable group who would have\nstayed anyway gets a $2 offer they never needed. It is right for\nroughly a third of the base and wrong for the rest.\n\n### 3. Personalized Contextual Bandit via Bayesian Causal Forests (BCF)\nBy pairing response-adaptive randomization [@finucane2018works]\nwith Bayesian Causal Forests [@hahn2020bayesian], in the\nmultivariate-treatment form implemented by `stochtree`\n[@stochastictree], we model the multi-treatment CATE landscape\n$\\boldsymbol{\\tau}(X) = (\\tau_1(X), \\tau_2(X), \\tau_3(X))^\\top$ over\ncontinuous customer features $X$. For every incoming caller, we take\none draw $s$ from the BCF posterior and route them to the treatment\nwith the highest sampled net economic return:\n\n$$\nA_i = \\arg\\max_{k \\in \\{0, 1, 2, 3\\}} \\left( \\tilde{\\tau}_k^{(s)}(X_i)\n  \\times \\text{LTV} - \\text{Cost}_k \\right)\n$$\n\nwith $\\tilde{\\tau}_0^{(s)} \\equiv 0$ for Control.\n\n---\n\n## Why Multivariate BCF is Built for Adaptive Experimentation\n\nAs introduced by @hahn2020bayesian, Bayesian Causal Forests\ndecompose the outcome into a prognostic term and a treatment-effect\nterm. In the multivariate-treatment form implemented in\n`stochtree`:\n\n$$\nY_i = \\mu\\left(X_i, \\hat{\\boldsymbol{\\pi}}(X_i)\\right) +\n  \\sum_{k=1}^K \\tau_k(X_i) Z_{i, k} + \\epsilon_i\n$$\n\nHere $K = 3$ indexes the *active* arms; Control is the reference\nlevel, encoded as $Z_i = (0, 0, 0)$, so the four candidate actions\nof the business problem become three treatment contrasts plus a\nbaseline. $\\hat{\\boldsymbol{\\pi}}(X_i) =\n(\\hat\\pi_1(X_i), \\hat\\pi_2(X_i), \\hat\\pi_3(X_i))$ is the\nassignment-probability **vector** — one entry per active arm, not a\nsingle scalar. Keeping it a vector matters in the code below.\n\nIn a response-adaptive trial the assignment probabilities\n$\\boldsymbol{\\pi}(X)$ change as the model learns, and they change\ndifferently for different customers: by Week 5, a long-tenure light\nuser and a brand-new power user face very different odds of\nreceiving each offer. Which arm a caller gets is therefore a\nfunction of the same covariates that drive their baseline retention,\nplus a coin flip. Conditioning on $X$ is enough *in principle* to\nremove that confounding, because $X$ is all the assignment rule\never looked at. In practice, a single regularized model of\n$\\mathbb{E}[Y \\mid X, Z]$ — a penalized regression, a pooled random\nforest — has to decide how much of the outcome difference between\ncallers who got an offer and callers who did not is the offer, and\nhow much is their covariates, and regularization settles that\nquestion in whichever direction makes the fit simpler.\n@hahn2020bayesian call the resulting bias\n**Regularization-Induced Confounding (RIC)**, and it is most severe\nprecisely when assignment tracks the covariates that predict the\noutcome — which is what adaptive allocation, by design, makes\nhappen.\n\nBCF is built to address this, and three of its design choices\nmatter here:\n\n1. **The propensity is a covariate of the prognostic forest.**\n   $\\mu(X, \\hat{\\boldsymbol{\\pi}})$ sees the design probability of\n   every active arm. In our trial those probabilities are known by\n   construction (Practical Lesson 3), so the one input BCF normally\n   has to estimate is handed to it exactly. This does not make\n   confounding disappear; it gives the prognostic forest a cheap\n   way to represent whatever outcome variation lines up with the\n   assignment rule, so that variation does not get pushed into the\n   treatment forest. Feeding the design probabilities to a forest as\n   covariates is one of the two ways @dimakopoulou2018estimation\n   propose to *balance* a forest-based contextual bandit against the\n   bias that adaptive data collection induces; the other is to\n   weight each observation by its inverse propensity, which\n   `stochtree` also supports through `observation_weights`.\n2. **Separate forests with separate priors.** The prognostic and\n   treatment forests are regularized differently. By default the\n   treatment forest is smaller and shallower (100 trees of depth at\n   most 5, against 250 trees of depth at most 10) and its split\n   prior is far more conservative, so it shrinks toward simple,\n   nearly homogeneous effects unless the data insist otherwise. On\n   an adaptively collected dataset, where some arms are thinly\n   sampled in some regions, that conservatism is what keeps the\n   model from hallucinating heterogeneity.\n3. **Vector-valued leaves for multiple arms.** With three treatment\n   contrasts, `stochtree` fits a single treatment forest whose\n   leaves each hold a vector of three effects. All arms share the\n   tree's partition of the covariate space, and each leaf stores\n   one coefficient per arm, so the arms borrow strength about\n   *where* effects change while keeping their own magnitudes.\n\nBecause the model is Bayesian, Thompson sampling\n[@thompson1933likelihood; @russo2018tutorial] comes almost for\nfree: draw one posterior sample of $\\boldsymbol{\\tau}(X_i)$ per\ncaller, route them to the arm with the highest sampled net value,\nand exploration is governed by posterior uncertainty rather than by\na hand-tuned exploration rate. An arm keeps receiving traffic in\nproportion to the posterior probability that it is the best one for\nthis caller. The randomization is not only how the design explores;\nit is also what keeps the data usable. @dimakopoulou2018estimation\nfind that Thompson sampling's randomized assignment makes the arms'\noutcome models easier to estimate than the deterministic assignment\nof upper-confidence-bound rules, and that the difference shows up\nas lower regret. We still add a small $\\epsilon$-floor on top of\nit; Practical Lesson 2 explains why.\n\nOne modeling choice deserves a sentence, because the code does not\nannounce it. Retention is binary, and we fit BCF with its default\nGaussian likelihood and identity link rather than a probit model.\nThat makes it a tree-based *linear probability model*:\n$\\mathbb{E}[Y \\mid X, Z]$ is the retention probability itself, so\n$\\tau_k(X)$ is directly the uplift in probability that the\nnet-value rule needs, with no back-transformation. The price is a\nconstant error variance that a Bernoulli outcome does not really\nhave, and fitted probabilities that are not confined to $[0, 1]$.\nFor a routing decision, which only needs the arms *ranked*\ncorrectly, that is a good trade. `stochtree` can also fit BCF with a\nprobit link (`outcome_model = OutcomeModel(\"binary\", \"probit\")`\ninside `general_params`); with it, $\\tau$ lives on the latent probit\nscale and the probability-scale uplift has to be reconstructed from\n$\\mu$ and $\\tau$ together.\n\n---\n\n## Simulating the Continuous Customer Environment in R\n\nLet's simulate a continuous customer feature space:\n\n- $X_1 \\in [0, 10]$: **Customer Tenure** (in months).\n- $X_2 \\in [0, 10]$: **Monthly Platform Usage** (in tens of hours).\n\nWe will run a 10-week simulation with 500 callers per week (5,000\ntotal customers), comparing **BCF Thompson Sampling**, a **Global\nNon-Contextual Bandit**, and a **Static RCT**. Each week, all three\nstrategies face the *same* 500 callers — the same tenure and usage\ndraws, the same true best arms — and differ only in which arm they\nassign and in the independent coin flips that decide whether each\ncaller stays. Differences between strategies are therefore never\ndifferences in who happened to show up.\n\n### Step 1: Defining the Ground Truth Environment\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(stochtree)\nlibrary(patchwork)\nlibrary(furrr)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Economic constants\nSAVED_CUSTOMER_LTV <- 25.0\nARM_COSTS <- c(0.0, 5.0, 8.0, 2.0)\nARM_NAMES <- c(\n  \"Arm 0: Control\", \"Arm 1: $5 Credit\",\n  \"Arm 2: 2-Mo Upgrade\", \"Arm 3: Onboarding Assist\"\n)\nARM_COLORS <- c(\"#70757a\", \"#4285f4\", \"#ea4335\", \"#34a853\")\n\n# Minimum exploration probability enforced on every arm once the\n# BCF model starts routing customers (Practical Lesson #2 below).\nEPSILON_FLOOR <- 0.05\n\n# Customer generator: continuous tenure X1 and usage X2\ngenerate_customers <- function(n, week = 1) {\n  tibble(\n    week = week,\n    customer_id = paste0(\"W\", week, \"_\", seq_len(n)),\n    tenure = runif(n, 0, 10),  # Months (0 to 10)\n    usage = runif(n, 0, 10)    # Active hours / 10 (0 to 10)\n  )\n}\n\n# Baseline retention probability under Control (Arm 0). Rises with\n# tenure and usage, spanning roughly 10%-53%: these are callers who\n# have already entered the cancellation flow, so most of them leave\n# if you do nothing.\n#\n# The coefficients are deliberately chosen so that p_base(X) plus\n# the largest uplift any arm can deliver never exceeds 1. That is\n# not cosmetic: if we had to clip p_base + tau into [0, 1], the\n# *realised* uplift would be smaller than tau wherever the clip\n# bites, and `true_cate_uplift()` below would no longer be the true\n# CATE of the process generating our data. Every \"ground truth\"\n# claim in this chapter would then be measured against a quantity\n# the simulation never actually produced. We assert this explicitly\n# in `draw_outcomes()` rather than trusting the arithmetic.\ntrue_baseline_retention <- function(df) {\n  x1 <- df$tenure\n  x2 <- df$usage\n  logits <- -2.2 + 0.085 * x1 + 0.095 * x2 + 0.005 * (x1 * x2)\n  1 / (1 + exp(-logits))\n}\n\n# True CATE uplift in retention probability for Arms 1, 2, 3\n# (in probability units: 0.36 is a 36 percentage-point uplift).\ntrue_cate_uplift <- function(df) {\n  x1 <- df$tenure\n  x2 <- df$usage\n  n <- nrow(df)\n  tau <- matrix(0, nrow = n, ncol = 4)\n\n  # Arm 1 ($5 Credit): Peak at Tenure=7.5, Usage=2.5 (up to +36 pp)\n  tau[, 2] <- 0.36 * exp(-0.06 * (x1 - 7.5)^2 - 0.08 * (x2 - 2.5)^2)\n\n  # Arm 2 (Feature Upgrade, $8 Cost): Peak at Tenure=2.5, Usage=7.5\n  # (up to +48 pp)\n  tau[, 3] <- 0.48 * exp(-0.08 * (x1 - 2.5)^2 - 0.06 * (x2 - 7.5)^2)\n\n  # Arm 3 (Onboarding Assist, $2 Cost): Peak at Tenure=2.0, Usage=2.0\n  # (up to +32 pp). Its bump is the widest of the three, so it is\n  # also the arm with the best *population-average* net value - which\n  # is exactly the trap the non-contextual bandit walks into below.\n  tau[, 4] <- 0.32 * exp(-0.05 * (x1 - 2.0)^2 - 0.05 * (x2 - 2.0)^2)\n\n  return(tau)\n}\n\n# True net economic values: tau_k(X) * LTV - Cost_k\ncompute_true_net_values <- function(df) {\n  tau <- true_cate_uplift(df)\n  sweep(tau * SAVED_CUSTOMER_LTV, 2, ARM_COSTS, \"-\")\n}\n\n# True optimal arm per user (0-based). Exact ties have probability\n# zero with continuous covariates, so a deterministic tie-break\n# keeps this function free of random-number use.\nget_true_optimal_arms <- function(df) {\n  net_vals <- compute_true_net_values(df)\n  max.col(net_vals, ties.method = \"first\") - 1\n}\n\n# Single outcome generator shared by all three strategies, so no\n# strategy can accidentally be simulated under a different DGP.\n# The stopifnot() is the guard rail described above: if a tuning\n# change ever pushes a retention probability outside [0, 1], the\n# chapter fails loudly instead of silently redefining its own\n# ground truth.\ndraw_outcomes <- function(p_base, tau_mat, arms) {\n  n <- length(arms)\n  p <- p_base + tau_mat[cbind(seq_len(n), arms + 1)]\n  stopifnot(all(p >= 0 & p <= 1))\n  rbinom(n, 1, p)\n}\n```\n:::\n\n\n### Visualizing the Ground Truth Optimal Decision Landscape\n\nLet's visualize the ground truth optimal action across the\ncontinuous 2D customer space:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate a dense 2D evaluation grid\ngrid_df <- expand.grid(\n  tenure = seq(0, 10, length.out = 120),\n  usage = seq(0, 10, length.out = 120)\n)\ngrid_df$optimal_arm <- factor(\n  get_true_optimal_arms(grid_df), levels = 0:3, labels = ARM_NAMES\n)\n\nggplot(grid_df, aes(x = tenure, y = usage, fill = optimal_arm)) +\n  geom_raster(interpolate = TRUE) +\n  scale_fill_manual(values = setNames(ARM_COLORS, ARM_NAMES)) +\n  labs(\n    title = \"Ground Truth Optimal Action Landscape (Net Value)\",\n    subtitle = paste(\n      \"Distinct customer regions require different retention\",\n      \"interventions\"\n    ),\n    x = \"Customer Tenure (Months)\",\n    y = \"Monthly Usage (x10 Hours)\",\n    fill = \"Optimal Action\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](bad_files/figure-html/true_landscape_plot-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nNotice that every single arm—including **Arm 0 (Control)**—has a\ndistinct territory. Because customers are spread uniformly over the\nsquare, the share of the grid each arm owns is also the share of\nthe customer population it is best for:\n\n- **Arm 0 (Control)** — 29% —\n  dominates wherever no treatment produces enough uplift to overcome\n  its cost.\n- **Arm 1 ($5 Credit)** — 20% —\n  dominates for veteran, lower-usage users.\n- **Arm 2 (Feature Upgrade)** — 15% —\n  dominates for newer power users. It has the largest raw uplift of\n  any arm (+48 percentage points at its peak) but also the highest\n  cost ($8), so its profitable territory is the smallest of the\n  four.\n- **Arm 3 (Onboarding Assist)** — 36% —\n  dominates for brand-new, low-usage users.\n\nNo single arm is right for even 40% of the population. That is the\nwhole problem in one sentence. And here is the trap in one more:\naveraged over the *whole* population, giving every caller the same\narm is worth -$2.27 per customer for the Credit,\n-$4.36 for the Upgrade, and $0.67 for\nOnboarding Assist (Control is $0.00 by definition). Onboarding is the\nonly active arm that pays on average, which is exactly why a\nnon-contextual bandit is going to crown it.\n\n---\n\n### Step 2: The Multi-Arm Adaptive Simulation Engine\n\nThe helpers at the top of this chunk are shared by everything that\nfollows: the weekly refits inside the trial, the final policy model\nin Section 6, and the replications in Section 7 all fit and\npredict through the same three functions, so no two parts of the\nchapter can drift onto different model settings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ------------------------------------------------------------------\n# Shared model helpers\n# ------------------------------------------------------------------\n\n# 3D treatment indicator basis Z in {0, 1}^3. Arm 0 is the reference\n# level (0, 0, 0), so the four candidate actions become three\n# treatment contrasts plus a baseline.\nmake_Z <- function(arms) {\n  Z <- matrix(0, nrow = length(arms), ncol = 3)\n  for (k in 1:3) Z[arms == k, k] <- 1.0\n  Z\n}\n\n# Deliberately light sampler settings so the chapter renders in\n# minutes; a production fit should use far more draws and check\n# convergence (see the BCF chapter's traceplot).\nBCF_SETTINGS <- list(num_gfr = 10, num_burnin = 150, num_mcmc = 200)\n\n# Fit the multivariate BCF. `df` must carry the design probability\n# of *every* arm in the matrix column `alloc_prob`.\nfit_bcf <- function(df, seed) {\n  bcf(\n    X_train = as.matrix(df[, c(\"tenure\", \"usage\")]),\n    Z_train = make_Z(df$assigned_arm),\n    y_train = df$retained,\n    # The prognostic forest conditions on the assignment-probability\n    # *vector* pi(X) = (pi_1, pi_2, pi_3), one column per active arm,\n    # matching the columns of Z. Handing BCF a single number - say,\n    # the propensity of whichever arm the customer happened to\n    # receive - would be a post-randomisation quantity, not a\n    # function of X alone, and would leak the realised assignment\n    # into the prognostic term.\n    propensity_train = df$alloc_prob[, 2:4, drop = FALSE],\n    num_gfr = BCF_SETTINGS$num_gfr,\n    num_burnin = BCF_SETTINGS$num_burnin,\n    num_mcmc = BCF_SETTINGS$num_mcmc,\n    general_params = list(num_threads = 2, random_seed = seed)\n  )\n}\n\n# CATE predictions for new customers: an [n, 3, num_mcmc] array of\n# posterior draws, or an [n, 3] matrix of posterior means. The CATE\n# term involves neither Z nor the propensity, but predict() requires\n# both arguments, so we pass placeholders.\npredict_cate <- function(fit, df, type = \"posterior\") {\n  n <- nrow(df)\n  predict(\n    fit,\n    X = as.matrix(df[, c(\"tenure\", \"usage\")]),\n    Z = matrix(0, nrow = n, ncol = 3),\n    propensity = matrix(0.25, nrow = n, ncol = 3),\n    terms = \"cate\",\n    type = type\n  )\n}\n\n# Net-value matrix [n, 4] from an [n, 3] CATE matrix: Arm 0 has zero\n# uplift and zero cost.\nnet_value_from_cate <- function(tau_mat) {\n  sweep(cbind(0, tau_mat) * SAVED_CUSTOMER_LTV, 2, ARM_COSTS, \"-\")\n}\n\n# The deployed policy: route each customer from the posterior *mean*\n# CATE, with no exploration. Returns 0-based arms.\ngreedy_policy <- function(fit, df) {\n  tau_hat <- predict_cate(fit, df, type = \"mean\")\n  max.col(net_value_from_cate(tau_hat), ties.method = \"first\") - 1\n}\n\n# ------------------------------------------------------------------\n# The trial\n# ------------------------------------------------------------------\nsimulate_experiment_suite <- function(n_weeks = 10, n_per_week = 500,\n                                      warm_start_weeks = 1, seed = 42) {\n  set.seed(seed)\n\n  bcf_records <- list()\n  global_records <- list()\n  rct_records <- list()\n\n  # Global bandit state (Beta-Bernoulli priors)\n  global_alpha <- rep(1, 4)\n  global_beta <- rep(1, 4)\n\n  for (w in seq_len(n_weeks)) {\n    cohort <- generate_customers(n_per_week, week = w)\n    cohort$true_opt_arm <- get_true_optimal_arms(cohort)\n\n    p_base <- true_baseline_retention(cohort)\n    tau_mat <- true_cate_uplift(cohort)\n\n    # -----------------------------------------------------------\n    # Strategy 1: Static RCT Baseline (Uniform 25% Allocation)\n    # -----------------------------------------------------------\n    rct_cohort <- cohort\n    # Exactly n/4 callers per arm each week (a permuted block), not\n    # an i.i.d. coin flip - this is what \"125 per arm\" means.\n    rct_cohort$assigned_arm <- sample(rep(0:3, each = n_per_week / 4))\n    # The RCT's design probability is 0.25 for every arm and every\n    # caller. Storing it lets the same fit_bcf() serve both designs.\n    rct_cohort$alloc_prob <- matrix(0.25, nrow = n_per_week, ncol = 4)\n    rct_cohort$retained <- draw_outcomes(\n      p_base, tau_mat, rct_cohort$assigned_arm\n    )\n    rct_cohort$cost <- ARM_COSTS[rct_cohort$assigned_arm + 1]\n    rct_cohort$net_value <-\n      rct_cohort$retained * SAVED_CUSTOMER_LTV - rct_cohort$cost\n    rct_records[[w]] <- rct_cohort\n\n    # -----------------------------------------------------------\n    # Strategy 2: Global Non-Contextual Multi-Armed Bandit\n    # -----------------------------------------------------------\n    glb_cohort <- cohort\n    # Draw retention rates from Beta posterior\n    sampled_rates <- matrix(\n      rbeta(\n        4 * n_per_week,\n        rep(global_alpha, each = n_per_week),\n        rep(global_beta, each = n_per_week)\n      ),\n      nrow = n_per_week, ncol = 4\n    )\n    sampled_net <- sweep(\n      sampled_rates * SAVED_CUSTOMER_LTV, 2, ARM_COSTS, \"-\"\n    )\n    glb_cohort$assigned_arm <-\n      max.col(sampled_net, ties.method = \"random\") - 1\n\n    glb_cohort$retained <- draw_outcomes(\n      p_base, tau_mat, glb_cohort$assigned_arm\n    )\n    glb_cohort$cost <- ARM_COSTS[glb_cohort$assigned_arm + 1]\n    glb_cohort$net_value <-\n      glb_cohort$retained * SAVED_CUSTOMER_LTV - glb_cohort$cost\n\n    # Update global Beta posteriors\n    for (k in 0:3) {\n      wins <- sum(glb_cohort$retained[glb_cohort$assigned_arm == k])\n      trials <- sum(glb_cohort$assigned_arm == k)\n      global_alpha[k + 1] <- global_alpha[k + 1] + wins\n      global_beta[k + 1] <- global_beta[k + 1] + (trials - wins)\n    }\n    global_records[[w]] <- glb_cohort\n\n    # -----------------------------------------------------------\n    # Strategy 3: BCF Thompson Sampling (Personalized Contextual)\n    # -----------------------------------------------------------\n    bcf_cohort <- cohort\n\n    if (w <= warm_start_weeks) {\n      # Initial warm-start exploration phase: uniform blocks.\n      # alloc_prob is stored as a full [n, 4] matrix column - the\n      # design probability of *every* arm, not just the one that\n      # happened to be drawn. That distinction matters below.\n      bcf_cohort$assigned_arm <- sample(rep(0:3, each = n_per_week / 4))\n      bcf_cohort$alloc_prob <- matrix(0.25, nrow = n_per_week, ncol = 4)\n    } else {\n      # Refit on all accumulated data, then predict posterior CATE\n      # draws for the incoming cohort: [n_per_week, 3, num_mcmc]\n      past_bcf <- bind_rows(bcf_records)\n      bcf_fit <- fit_bcf(past_bcf, seed = seed + w)\n      tau_draws <- predict_cate(bcf_fit, bcf_cohort)\n      num_mcmc <- dim(tau_draws)[3]\n\n      # Full 4-arm net-value draws (Arm 0 uplift is fixed at 0)\n      tau_draws_all <- array(0, dim = c(n_per_week, 4, num_mcmc))\n      tau_draws_all[, 2:4, ] <- tau_draws\n      net_draws <- sweep(\n        tau_draws_all * SAVED_CUSTOMER_LTV, 2, ARM_COSTS, \"-\"\n      )\n\n      # Which arm wins the net value in each posterior draw, for\n      # every customer: an [n_per_week, num_mcmc] matrix of arms.\n      winner_by_draw <- apply(net_draws, c(1, 3), which.max) - 1\n\n      # Per-arm Thompson-sampling assignment probability: the share\n      # of the retained posterior draws in which that arm is the\n      # argmax, for each customer. There is no closed form for this\n      # quantity, so we compute it directly from the draws we\n      # already have - and because the routing step below samples\n      # from those same draws, this is the exact assignment\n      # probability of the mechanism we are about to run.\n      ts_win_prob <- t(apply(winner_by_draw, 1, function(draws) {\n        tabulate(draws + 1, nbins = 4)\n      })) / num_mcmc\n\n      # Blend with an exploration floor so every arm keeps a strictly\n      # positive assignment probability for every customer\n      # (Practical Lesson #2).\n      design_prob <-\n        EPSILON_FLOOR / 4 + (1 - EPSILON_FLOOR) * ts_win_prob\n\n      # Thompson sampling: draw one posterior sample per user, with\n      # an epsilon chance of a uniform exploration draw instead.\n      sampled_draw_idx <- sample(\n        seq_len(num_mcmc), n_per_week, replace = TRUE\n      )\n      ts_choice <- winner_by_draw[\n        cbind(seq_len(n_per_week), sampled_draw_idx)\n      ]\n      explore <- runif(n_per_week) < EPSILON_FLOOR\n      random_choice <- sample(0:3, n_per_week, replace = TRUE)\n      bcf_cohort$assigned_arm <-\n        ifelse(explore, random_choice, ts_choice)\n\n      # Keep the entire [n, 4] design matrix. We built the\n      # assignment mechanism, so these are its true probabilities -\n      # the one input to BCF that an observational study would have\n      # to estimate.\n      bcf_cohort$alloc_prob <- design_prob\n    }\n\n    bcf_cohort$retained <- draw_outcomes(\n      p_base, tau_mat, bcf_cohort$assigned_arm\n    )\n    bcf_cohort$cost <- ARM_COSTS[bcf_cohort$assigned_arm + 1]\n    bcf_cohort$net_value <-\n      bcf_cohort$retained * SAVED_CUSTOMER_LTV - bcf_cohort$cost\n\n    bcf_records[[w]] <- bcf_cohort\n  }\n\n  list(\n    bcf = bind_rows(bcf_records),\n    global = bind_rows(global_records),\n    rct = bind_rows(rct_records),\n    # The global bandit's final beliefs, so its deployed policy can\n    # be read off its posterior rather than off its last week's\n    # realised assignments.\n    global_posterior = list(alpha = global_alpha, beta = global_beta)\n  )\n}\n\nsim_results <- simulate_experiment_suite(\n  n_weeks = 10, n_per_week = 500, seed = 42\n)\n```\n:::\n\n\nEvery headline number quoted in the rest of this chapter is computed\nfrom `sim_results` here and then referenced inline, so the prose\ncannot drift away from what the simulation actually produced:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_week_acc <- function(df) {\n  last <- df$week == max(df$week)\n  mean(df$assigned_arm[last] == df$true_opt_arm[last])\n}\npct <- function(x) sprintf(\"%.0f%%\", 100 * unname(x))\nusd <- function(x) scales::dollar(unname(x), accuracy = 1)\n\nacc_bcf <- final_week_acc(sim_results$bcf)\nacc_glb <- final_week_acc(sim_results$global)\nacc_rct <- final_week_acc(sim_results$rct)\n\nval_bcf <- sum(sim_results$bcf$net_value)\nval_glb <- sum(sim_results$global$net_value)\nval_rct <- sum(sim_results$rct$net_value)\n\n# Which single arm did the non-contextual bandit settle on? Read it\n# off its posterior-mean net value, i.e. its actual decision rule.\nglb_post <- sim_results$global_posterior\nglb_post_net <- glb_post$alpha / (glb_post$alpha + glb_post$beta) *\n  SAVED_CUSTOMER_LTV - ARM_COSTS\nglb_winner <- which.max(glb_post_net) - 1\n\n# ...and what share of the final week's callers actually got it.\nglb_final_mix <- table(factor(\n  sim_results$global$assigned_arm[\n    sim_results$global$week == max(sim_results$global$week)\n  ],\n  levels = 0:3\n))\nglb_winner_share <- glb_final_mix[glb_winner + 1] / sum(glb_final_mix)\n\n# Share of the final week's callers each arm is truly best for - the\n# same week acc_* is measured on. All three strategies saw the same\n# customers, so any of them would do.\nlast_week <- sim_results$bcf$week == max(sim_results$bcf$week)\ntruth_share <- prop.table(table(factor(\n  sim_results$bcf$true_opt_arm[last_week], levels = 0:3\n)))\n```\n:::\n\n\n---\n\n## Evaluating the Results\n\n### 1. Learned Decision Boundaries vs. Ground Truth\n\nHow accurately did Multivariate BCF recover the optimal action\nboundaries across the 2D customer space?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the final policy model on everything the adaptive trial\n# collected, and evaluate it on the dense grid.\nset.seed(999)\nfinal_bcf <- fit_bcf(sim_results$bcf, seed = 999)\n\ngrid_pred <- predict_cate(final_bcf, grid_df, type = \"mean\")\ngrid_pred_net <- net_value_from_cate(grid_pred)\ngrid_df$bcf_optimal_arm <- factor(\n  max.col(grid_pred_net, ties.method = \"first\") - 1,\n  levels = 0:3, labels = ARM_NAMES\n)\n\n# drop = FALSE keeps all four arms in the legend even when a panel\n# happens not to use one of them, so the two maps stay comparable.\nlandscape_panel <- function(fill_var, title) {\n  ggplot(grid_df, aes(x = tenure, y = usage, fill = .data[[fill_var]])) +\n    geom_raster(interpolate = TRUE) +\n    scale_fill_manual(\n      values = setNames(ARM_COLORS, ARM_NAMES),\n      limits = ARM_NAMES, drop = FALSE\n    ) +\n    labs(\n      title = title,\n      x = \"Tenure (Months)\", y = \"Usage (x10 Hours)\", fill = \"Arm\"\n    ) +\n    theme_minimal(base_size = 11)\n}\n\nagreement <- mean(grid_df$optimal_arm == grid_df$bcf_optimal_arm)\n\n# Agreement alone does not say whether the disagreements matter.\n# Price them: what net value does BCF's choice forgo against the\n# oracle's, cell by cell?\ngrid_true_net <- compute_true_net_values(grid_df)\noracle_cell <- grid_true_net[\n  cbind(seq_len(nrow(grid_df)), as.integer(grid_df$optimal_arm))\n]\nbcf_cell <- grid_true_net[\n  cbind(seq_len(nrow(grid_df)), as.integer(grid_df$bcf_optimal_arm))\n]\nregret_cell <- oracle_cell - bcf_cell\nregret_where_wrong <- regret_cell[regret_cell > 1e-9]\nmedian_regret_where_wrong <- median(regret_where_wrong)\nmean_regret_where_wrong <- mean(regret_where_wrong)\nmax_regret <- max(regret_cell)\nvalue_captured <- sum(bcf_cell) / sum(oracle_cell)\n\n# Where do the disagreements come from? Cheap boundary calls versus\n# one systematic error: handing out the cheap Onboarding Assist\n# where the Credit or the Upgrade would have won.\nwrong_cells <- grid_df[regret_cell > 1e-9, ]\nshare_cheap_miss <- mean(regret_where_wrong < 1)\nshare_onboarding_over <- mean(\n  wrong_cells$bcf_optimal_arm == ARM_NAMES[4] &\n    wrong_cells$optimal_arm %in% ARM_NAMES[2:3]\n)\ncostly_cells <- grid_df[regret_cell > 2, ]\nshare_costly_onboarding <- mean(\n  costly_cells$bcf_optimal_arm == ARM_NAMES[4] &\n    costly_cells$optimal_arm %in% ARM_NAMES[2:3]\n)\n\nwrap_plots(\n  landscape_panel(\"optimal_arm\", \"Ground Truth Optimal Landscape\"),\n  landscape_panel(\"bcf_optimal_arm\", \"BCF Learned Decision Landscape\"),\n  ncol = 2\n) +\n  plot_layout(guides = \"collect\") +\n  plot_annotation(\n    caption = sprintf(\n      \"The two maps agree on %.0f%% of the customer feature space.\",\n      100 * agreement\n    )\n  ) &\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](bad_files/figure-html/decision_boundary_plot-1.png){width=1152}\n:::\n:::\n\n\nThe two maps agree on **82%** of the feature space,\nwith no prespecified feature engineering and no manual subgroup\nbinning: BCF recovered four curved, cost-dependent regions from\nbinary retention outcomes alone.\n\nThe remaining 18% is worth pricing rather than\napologizing for. Where the two maps disagree, BCF's choice gives up\na median of $1.05 of net value per\ncustomer against the oracle's choice, a mean of\n$1.21, and at worst\n$3.57. About 48% of the\ndisagreeing cells cost under $1: boundary cells where two arms have\nnearly equal net value and picking the runner-up barely matters.\nThe costly disagreements are dominated by one systematic error. In\n63% of all disagreeing cells, and in\n98% of the cells where the loss exceeds\n$2, BCF hands out the cheap Onboarding Assist where the oracle would\nhave used the Credit or the Upgrade — its learned Onboarding region\nis visibly too large — because the posterior mean underestimates\nthose two arms' peaks (Section 3 shows the attenuation directly),\nand a shrunken peak loses the net-value race to a cheaper arm. Summed across the\nwhole feature space — which, again, is the customer population here\n— the learned map still captures **89%** of the\noracle's achievable value. A decision rule does not need the effect\nsurface to be right; it needs the *ranking* to be right where the\nranking matters, and that is an easier target — though, as the\nOnboarding overreach shows, not a free one.\n\n---\n\n### 2. Dynamic Routing Accuracy Over Time\n\nDid the algorithms learn to route customers to their personal\noptimal intervention?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate rolling accuracy to the true optimal arm. Each input\n# data frame already holds one strategy's customers in chronological\n# order, so row_number() gives a valid per-strategy customer index -\n# essential so the three strategies overlay on the same x-axis below\n# instead of being plotted as disjoint, back-to-back segments.\ncalculate_rolling_acc <- function(df, window = 250) {\n  df %>%\n    mutate(\n      is_optimal = as.numeric(assigned_arm == true_opt_arm),\n      customer_idx = row_number(),\n      rolling_acc = zoo::rollmean(\n        is_optimal, k = window, fill = NA, align = \"right\"\n      )\n    )\n}\n\nacc_df <- bind_rows(\n  calculate_rolling_acc(sim_results$bcf) %>%\n    mutate(strategy = \"BCF Thompson Sampling (Personalized)\"),\n  calculate_rolling_acc(sim_results$global) %>%\n    mutate(strategy = \"Global MAB (Non-Contextual)\"),\n  calculate_rolling_acc(sim_results$rct) %>%\n    mutate(strategy = \"Static RCT Baseline (Uniform 25%)\")\n) %>%\n  filter(!is.na(rolling_acc))\n\nggplot(\n  acc_df, aes(x = customer_idx, y = rolling_acc, color = strategy)\n) +\n  geom_line(linewidth = 1.2) +\n  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +\n  # Zoom without dropping data (limits = would silently drop points)\n  coord_cartesian(ylim = c(0.15, 0.95)) +\n  scale_color_manual(values = c(\n    \"BCF Thompson Sampling (Personalized)\" = \"#1a73e8\",\n    \"Global MAB (Non-Contextual)\" = \"#f9ab00\",\n    \"Static RCT Baseline (Uniform 25%)\" = \"#d93025\"\n  )) +\n  labs(\n    title = \"Dynamic Routing Accuracy to Personal Optimal Arm Over Time\",\n    subtitle = sprintf(\n      paste(\n        \"By the final week BCF routes %.0f%% of customers to their\",\n        \"personal best arm, against %.0f%% for the global bandit\"\n      ),\n      100 * acc_bcf, 100 * acc_glb\n    ),\n    x = \"Customer Sequence Within Strategy\",\n    y = \"Proportion Assigned to True Optimal Arm\",\n    color = \"Strategy\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](bad_files/figure-html/routing_accuracy_plot-1.png){width=864}\n:::\n:::\n\n\n**Key Takeaways:**\n\n- **Static RCT (Red)**: hovers around 25% — it is guessing, by\n  design, forever. It ends the trial at 26%. The\n  wobble around that line is just sampling noise in a 250-customer\n  rolling window, not learning.\n- **Global Bandit (Orange)**: converges on\n  **Arm 3: Onboarding Assist**, the arm with the best\n  *population-average* net value, and by the final week hands it to\n  99% of all callers. That is the right answer\n  for the 39% of that week's callers\n  this arm genuinely suits and the wrong one for everybody else,\n  which caps it at 39%. Note *which* arm it crowned: the cheap\n  Onboarding Assist is a perfectly reasonable population-average\n  bet, and that is precisely what makes the failure mode so easy to\n  miss in a dashboard.\n- **BCF Thompson Sampling (Blue)**: starts at 25% during warm-start\n  exploration, then discovers the non-linear boundaries across\n  Tenure and Usage, ending the trial at **71%**.\n\nThat last number deserves a caveat that is easy to gloss over.\n71% is *not* the accuracy of the policy you would\ndeploy — it is the accuracy of a system that is **still\ndeliberately exploring**. Thompson sampling routes from a random\nposterior draw, not from the posterior mean, and the\n$\\epsilon$-floor sends another 5% of traffic to a uniformly random\narm. Both are costs paid on purpose, during the trial, to buy a\nbetter model at the end of it. We measure the deployed policy\nseparately in Section 6.\n\n---\n\n### 3. Posterior Uncertainty & 95% Credible Intervals Along Slices\n\nTo understand how well BCF quantifies treatment effect uncertainty,\nlet's examine posterior credible intervals along characteristic\nslices through the continuous feature space:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN_test <- 30\neval_range <- seq(0.2, 9.8, length.out = N_test)\n\n# Slice 1: Sweep Tenure at Usage = 2.5 (through peak of Arm 1)\nX_slice1 <- data.frame(tenure = eval_range, usage = rep(2.5, N_test))\n# Slice 2: Sweep Usage at Tenure = 2.5 (through peak of Arm 2)\nX_slice2 <- data.frame(tenure = rep(2.5, N_test), usage = eval_range)\n# Slice 3: Diagonal Sweep Tenure = Usage (through peak of Arm 3)\nX_slice3 <- data.frame(tenure = eval_range, usage = eval_range)\n\n# Posterior CATE draws from the final fitted BCF: [N_test, 3, draws]\ndraws_s1 <- predict_cate(final_bcf, X_slice1)\ndraws_s2 <- predict_cate(final_bcf, X_slice2)\ndraws_s3 <- predict_cate(final_bcf, X_slice3)\n\nslice_summary <- bind_rows(\n  tibble(\n    slice = \"Arm 1: $5 Credit (Usage = 2.5)\",\n    x_val = eval_range,\n    true_tau = true_cate_uplift(X_slice1)[, 2],\n    post_mean = apply(draws_s1[, 1, ], 1, mean),\n    ci_lower = apply(draws_s1[, 1, ], 1, quantile, 0.025),\n    ci_upper = apply(draws_s1[, 1, ], 1, quantile, 0.975),\n    arm_color = ARM_COLORS[2]\n  ),\n  tibble(\n    slice = \"Arm 2: 2-Mo Upgrade (Tenure = 2.5)\",\n    x_val = eval_range,\n    true_tau = true_cate_uplift(X_slice2)[, 3],\n    post_mean = apply(draws_s2[, 2, ], 1, mean),\n    ci_lower = apply(draws_s2[, 2, ], 1, quantile, 0.025),\n    ci_upper = apply(draws_s2[, 2, ], 1, quantile, 0.975),\n    arm_color = ARM_COLORS[3]\n  ),\n  tibble(\n    slice = \"Arm 3: Onboarding Assist (Diagonal)\",\n    x_val = eval_range,\n    true_tau = true_cate_uplift(X_slice3)[, 4],\n    post_mean = apply(draws_s3[, 3, ], 1, mean),\n    ci_lower = apply(draws_s3[, 3, ], 1, quantile, 0.025),\n    ci_upper = apply(draws_s3[, 3, ], 1, quantile, 0.975),\n    arm_color = ARM_COLORS[4]\n  )\n)\n\n# Fraction of slice points whose 95% interval contains the truth -\n# stated rather than asserted.\ncontainment <- mean(\n  slice_summary$true_tau >= slice_summary$ci_lower &\n    slice_summary$true_tau <= slice_summary$ci_upper\n)\n\n# How much of each true peak does the posterior mean recover?\npeak_recovery <- slice_summary %>%\n  group_by(slice) %>%\n  summarise(ratio = post_mean[which.max(true_tau)] / max(true_tau)) %>%\n  pull(ratio)\n\n# slice_colors keys the palette to the facet, so each panel is drawn\n# in that arm's colour from ARM_COLORS instead of ggplot's defaults.\nslice_colors <- setNames(\n  unique(slice_summary$arm_color), unique(slice_summary$slice)\n)\n\nggplot(slice_summary, aes(x = x_val)) +\n  geom_line(\n    aes(y = true_tau), linetype = \"dashed\", color = \"grey20\",\n    linewidth = 1\n  ) +\n  geom_point(aes(y = post_mean, color = slice), size = 2) +\n  geom_errorbar(\n    aes(ymin = ci_lower, ymax = ci_upper, color = slice),\n    width = 0.25, alpha = 0.7\n  ) +\n  scale_color_manual(values = slice_colors) +\n  facet_wrap(~ slice, scales = \"free_x\") +\n  labs(\n    title = paste(\n      \"BCF Posterior Credible Intervals vs. Ground Truth CATE\",\n      \"Along Characteristic Slices\"\n    ),\n    subtitle = sprintf(\n      paste(\n        \"Grey dashed line: true uplift. Points and bars: BCF\",\n        \"posterior mean and 95%% credible interval\",\n        \"(truth inside the interval at %.0f%% of points).\"\n      ),\n      100 * containment\n    ),\n    x = \"Feature Value\",\n    y = \"Treatment Uplift in Retention (tau)\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](bad_files/figure-html/slices_plot-1.png){width=1056}\n:::\n:::\n\n\nThe intervals contain the true CATE at **97%** of\nthe 90 evaluated points. Read that for what it\nis: a calibration sanity check on one fitted model, from one\nsimulated dataset, using 200 posterior draws — not a repeated-sampling\ncoverage study. The shape of the residual error is more instructive\nthan the number. BCF's posterior mean is visibly *flatter* than the\ntrue Gaussian bumps: at the three peaks it recovers only\n74%–89% of the true\nheight, and it drifts away from zero out in the tails where the true\neffect has already died off. Two things are going on. One is the\ntreatment forest's regularization prior doing its job: it shrinks\ntoward a simpler surface unless the data insist otherwise, which is\nprecisely why the method is stable enough to route live traffic on.\nThe other is the adaptive design itself: once the posterior has\nruled an arm out in a region, that arm is only sampled there at the\n$\\epsilon$-floor rate, so the data that would pin its effect to zero\nnever arrive, and the intervals in the tails stay wide. For a\ndecision rule this attenuation is largely harmless, because ranking\narms by net value only requires getting the *ordering* right, not\nthe magnitude — which is why policy accuracy (Section 6) holds up\nfar better than the pointwise CATE fit does. If you needed\ncalibrated effect *sizes* rather than a routing decision, you would\nwant more data per region than an adaptive design chooses to\ncollect, and more posterior draws than this chapter uses.\n\n---\n\n### 4. Design Propensities Stay Bounded Away From Zero\n\nPractical Lesson #3 below claims the design propensities are known\nby construction, and Practical Lesson #2 claims an exploration floor\nkeeps every arm's assignment probability strictly positive. Both\nclaims are only as good as the numbers the simulation actually\nproduced, so let's look at them directly: the `alloc_prob` stored\nfor every BCF-routed customer once the model started making\nassignments (Week 2 onward).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadaptive_bcf <- sim_results$bcf %>% filter(week > 1)\n\n# Every customer-arm pair, not only the pair that was realised:\n# this is the quantity that has to stay away from zero for\n# positivity to hold.\npropensity_df <- tibble(\n  arm = rep(0:3, each = nrow(adaptive_bcf)),\n  prob = as.vector(adaptive_bcf$alloc_prob)\n) %>%\n  mutate(arm_name = factor(arm, levels = 0:3, labels = ARM_NAMES))\n\nmin_prop <- min(propensity_df$prob)\n\n# Bins aligned to 0 so the floor (0.0125) lands squarely inside the\n# first bin, and coord_cartesian() rather than scale limits so no\n# edge bin is silently dropped from the plot.\nggplot(propensity_df, aes(x = prob, fill = arm_name)) +\n  geom_histogram(binwidth = 0.025, boundary = 0, alpha = 0.85) +\n  geom_vline(\n    xintercept = EPSILON_FLOOR / 4, linetype = \"dashed\",\n    color = \"grey30\"\n  ) +\n  coord_cartesian(xlim = c(0, 1)) +\n  scale_fill_manual(values = setNames(ARM_COLORS, ARM_NAMES)) +\n  labs(\n    title = \"Design Propensity of Every Customer-Arm Pair\",\n    subtitle = sprintf(\n      paste(\n        \"Dashed line marks the epsilon/4 = %.4f floor.\",\n        \"Observed minimum across all pairs: %.4f\"\n      ),\n      EPSILON_FLOOR / 4, min_prop\n    ),\n    x = \"P(this arm | X, adaptive design)\",\n    y = \"Count\",\n    fill = \"Arm\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](bad_files/figure-html/propensity_plot-1.png){width=768}\n:::\n:::\n\n\nNothing falls below the dashed line. The distribution instead piles\nup *exactly at* the floor $\\epsilon/4 = 0.0125$ —\nthat spike is every customer-arm pair the posterior has already\nruled out, held open by the $\\epsilon$-blend rather than by any\nresidual uncertainty. The observed minimum across all\n18,000 customer-arm pairs is\n0.0125, so no pair ever collapses to zero:\nevery arm remains a live possibility for every customer, which is\nthe positivity condition causal identification needs. The mass\nclimbing toward $1 - 3\\epsilon/4 = 0.9625$,\nthe most any arm can receive, is the design at work: propensities\napproach that ceiling exactly where the posterior is confident an\narm dominates. Keep the spike in mind, though. A 1.25% probability\nis a trickle, not a stream, and Practical Lesson #2 is explicit\nabout what that does and does not guarantee.\n\n---\n\n### 5. Cumulative Net Business Value ($) Generated During the Trial\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# When does BCF's cumulative value overtake the global bandit's?\n# Early on it is behind: it is buying information it has not yet\n# cashed in.\ncum_bcf <- cumsum(sim_results$bcf$net_value)\ncum_glb <- cumsum(sim_results$global$net_value)\nbehind <- which(cum_bcf <= cum_glb)\ncrossover_idx <- if (length(behind) > 0) max(behind) + 1L else 1L\n\nfinancial_summary <- bind_rows(\n  sim_results$bcf %>% mutate(strategy = \"BCF Thompson Sampling\"),\n  sim_results$global %>% mutate(strategy = \"Global Bandit\"),\n  sim_results$rct %>% mutate(strategy = \"Static RCT Baseline\")\n) %>%\n  group_by(strategy) %>%\n  mutate(\n    customer_idx = row_number(),\n    cum_net = cumsum(net_value)\n  )\n\nggplot(\n  financial_summary,\n  aes(x = customer_idx, y = cum_net, color = strategy)\n) +\n  geom_line(linewidth = 1.2) +\n  scale_y_continuous(labels = scales::dollar_format()) +\n  scale_color_manual(values = c(\n    \"BCF Thompson Sampling\" = \"#1a73e8\",\n    \"Global Bandit\" = \"#f9ab00\",\n    \"Static RCT Baseline\" = \"#d93025\"\n  )) +\n  labs(\n    title = paste(\n      \"Cumulative Net Economic Value ($) Generated During\",\n      \"Experiment\"\n    ),\n    subtitle = sprintf(\n      paste(\n        \"Over 5,000 customers: BCF %s, Global Bandit %s,\",\n        \"Static RCT %s\"\n      ),\n      usd(val_bcf), usd(val_glb), usd(val_rct)\n    ),\n    x = \"Customer Timeline\",\n    y = \"Cumulative Net Value ($)\",\n    color = \"Strategy\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](bad_files/figure-html/financial_plot-1.png){width=864}\n:::\n:::\n\n\nRead this chart honestly, because it does not say what an\nadaptive-design pitch deck usually says.\n\nAgainst the static RCT the gap is large:\n**$11,365** over 5,000 customers, or\n$2.27 per caller. That is the price\nof keeping 75% of your traffic on offers the accumulating data would\nalready have steered those callers away from, and the RCT pays it\nfor the full ten weeks whether or not anyone ever acts on its\nresults.\n\nAgainst the *global bandit*, though, the story is more interesting.\nFor the first **1,823 customers\nBCF is actually behind**: the blue line sits below the orange one\nwhile the model spends real money exploring arms it is not yet sure\nabout. It only pulls ahead for good after that, and finishes just\n**$2,964** up — a\n9.4%\nimprovement. Whether a gap that size survives a change of random\nseed is exactly the kind of question a single run cannot answer;\nSection 7 answers it. Either way, this is not a defect in the\nmethod; it is what response-adaptive allocation actually buys you.\nThe global bandit converged fast onto a cheap, broadly-decent arm\nand spent the whole trial exploiting it, while BCF spent the trial\npaying for exploration. In-trial regret is the *wrong* place to look\nfor the value of personalization.\n\nThe right place is the policy you own when the trial ends.\n\n---\n\n### 6. The Number That Actually Matters: Deployed Policy Value\n\nA trial of 5,000 customers is a rounding error next to the customers\nwho come after it. What you are really buying with ten weeks of\nexperimentation is a **decision rule** that runs indefinitely. So\nlet's evaluate the rule, not the trial: freeze each strategy's final\npolicy, apply it to a fresh population of 20,000 callers the models\nhave never seen, and score it against the true net values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2024)\nholdout <- generate_customers(20000, week = 99)\nholdout_net <- compute_true_net_values(holdout)\nholdout_opt <- max.col(holdout_net, ties.method = \"first\") - 1\nn_hold <- nrow(holdout)\n\n# True net value per customer of an arbitrary (0-based) assignment\nscore_policy <- function(arms) {\n  mean(holdout_net[cbind(seq_len(n_hold), arms + 1)])\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The RCT also yields a policy: fit the same model to its balanced\n# data. This is the fair comparison, and the one that shows what\n# adaptive allocation does and does not buy.\nset.seed(4321)\nrct_bcf <- fit_bcf(sim_results$rct, seed = 4321)\n\nchoice_bcf <- greedy_policy(final_bcf, holdout)\nchoice_rct <- greedy_policy(rct_bcf, holdout)\n\npolicy_tbl <- tibble(\n  policy = c(\n    \"Oracle (knows the truth)\",\n    \"BCF policy from adaptive trial\",\n    \"BCF policy from static RCT data\",\n    sprintf(\"Global bandit (always %s)\", ARM_NAMES[glb_winner + 1]),\n    \"Untargeted (random offer)\"\n  ),\n  value = c(\n    score_policy(holdout_opt),\n    score_policy(choice_bcf),\n    score_policy(choice_rct),\n    mean(holdout_net[, glb_winner + 1]),\n    mean(holdout_net)\n  ),\n  accuracy = c(\n    1,\n    mean(choice_bcf == holdout_opt),\n    mean(choice_rct == holdout_opt),\n    mean(holdout_opt == glb_winner),\n    0.25\n  )\n)\n\nANNUAL_CUSTOMERS <- 500 * 52\npolicy_tbl <- policy_tbl %>%\n  mutate(\n    annual = value * ANNUAL_CUSTOMERS,\n    policy = factor(policy, levels = rev(policy))\n  )\n\nggplot(policy_tbl, aes(x = value, y = policy, fill = value > 0)) +\n  geom_col(alpha = 0.9) +\n  geom_vline(xintercept = 0, color = \"grey40\") +\n  geom_text(\n    aes(label = sprintf(\"%s  (%.0f%% correct)\",\n                        scales::dollar(value, accuracy = 0.01),\n                        100 * accuracy),\n        hjust = ifelse(value > 0, -0.08, 1.08)),\n    size = 3.1\n  ) +\n  scale_fill_manual(values = c(`TRUE` = \"#1a73e8\", `FALSE` = \"#d93025\")) +\n  scale_x_continuous(\n    labels = scales::dollar_format(),\n    expand = expansion(mult = c(0.55, 0.55))\n  ) +\n  labs(\n    title = \"Value of the Deployed Policy on 20,000 Unseen Customers\",\n    subtitle = paste(\n      \"Incremental net value per customer versus doing nothing,\",\n      \"after the trial has ended\"\n    ),\n    x = \"Net Value per Future Customer ($)\", y = NULL\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](bad_files/figure-html/policy_value-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nFour things fall out of this chart, and only one of them is the\nthing the pitch deck would have told you.\n\n**The deployed policy is far sharper than the trial made it look.**\nRouting the holdout greedily from the posterior *mean* gets\n**82%** of customers to their true best arm, against\n71% during the trial itself. The gap is the exploration\nyou were paying for: Thompson draws and the $\\epsilon$-floor, both\nswitched off the moment you deploy. Accuracy is the intuitive\nnumber, but value is the one that matters — a near-tie called the\nwrong way and a catastrophic misroute both count as one error — and\nthe learned policy captures **89%** of what a\nperfectly-informed oracle could earn.\n\n**Personalization is worth real money, but annually, not weekly.**\nAt 500 callers a week the deployed BCF policy is worth\n$1.13 per customer more than the global bandit's\nsingle-arm rule — **$29,353 a\nyear** across 26,000 callers.\n*This* is where the \"tens of thousands\" lives. It was never in the\nten-week trial.\n\n**Untargeted treatment destroys value.** Handing every caller a\nrandom one of the four options is worth -$1.47 per\ncustomer — negative. Averaged over the population, these incentives\ncost more than the retention they buy. The entire value of the\nexercise is knowing *whom* to treat, which is exactly the question a\nnon-contextual bandit cannot ask.\n\n**And the honest one: adaptive allocation is not what made the model\ngood.** A policy trained on the static RCT's perfectly balanced data\nscores $1.54 per customer at 72% accuracy,\nagainst the adaptive design's $1.81. Balanced data is\nexcellent for *estimation*. What the adaptive design bought was the\n$11,365 of in-trial revenue the RCT gave away to\nget there. Adaptive design is a regret-minimization technique that\nhappens to leave you with a good model — not an estimation\ntechnique that happens to make money. If you only ever quote one\nsentence from this chapter to a stakeholder, quote that one. Then\ncheck Section 7, because one run is one run.\n\n---\n\n### 7. Is Any of This Seed Luck? Replicating the Whole Trial\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN_REPS <- 40\n```\n:::\n\n\nEverything above comes from a single run: one draw of 5,000\ncustomers, one sequence of coin flips, one short MCMC chain per\nweek. Some of the numbers are robust to that and some are not, and\nthe only way to find out which is to run the whole pipeline again\nwith different random seeds. So let's do it: 40 independent\nreplications of the ten-week trial for all three strategies, each\nfollowed by the same two policy fits as Section 6, all scored on the\nsame 20,000-customer holdout. The adaptive-trial literature calls\nthis checking a design's *operating characteristics*\n[@robertson2023rar], and it belongs in any adaptive design you\nintend to run for real.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# One complete replication: the trial, the two policy fits, and the\n# global bandit's posterior decision rule, scored on the holdout.\nrun_replication <- function(seed) {\n  sim <- simulate_experiment_suite(\n    n_weeks = 10, n_per_week = 500, seed = seed\n  )\n  set.seed(seed + 100)\n  fit_adaptive <- fit_bcf(sim$bcf, seed = seed + 100)\n  set.seed(seed + 200)\n  fit_rct <- fit_bcf(sim$rct, seed = seed + 200)\n  post <- sim$global_posterior\n  glb_arm <- which.max(\n    post$alpha / (post$alpha + post$beta) * SAVED_CUSTOMER_LTV - ARM_COSTS\n  ) - 1\n  tibble(\n    seed = seed,\n    trial_bcf = sum(sim$bcf$net_value),\n    trial_glb = sum(sim$global$net_value),\n    trial_rct = sum(sim$rct$net_value),\n    policy_adaptive = score_policy(greedy_policy(fit_adaptive, holdout)),\n    policy_rct = score_policy(greedy_policy(fit_rct, holdout)),\n    policy_glb = mean(holdout_net[, glb_arm + 1]),\n    glb_arm = glb_arm\n  )\n}\n\nn_workers <- max(1, min(8, parallel::detectCores() %/% 2))\nplan(multisession, workers = n_workers)\nrep_results <- future_map_dfr(\n  1000 + seq_len(N_REPS), run_replication,\n  .options = furrr_options(\n    seed = TRUE, packages = c(\"stochtree\", \"dplyr\", \"tibble\")\n  )\n)\nplan(sequential)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngap_trial_rct <- rep_results$trial_bcf - rep_results$trial_rct\ngap_trial_glb <- rep_results$trial_bcf - rep_results$trial_glb\ngap_policy_glb <- rep_results$policy_adaptive - rep_results$policy_glb\ngap_policy_rct <- rep_results$policy_adaptive - rep_results$policy_rct\n\nsummarise_gap <- function(x, label, money = usd) {\n  tibble(\n    Quantity = label,\n    Mean = money(mean(x)),\n    `5th pct` = money(quantile(x, 0.05)),\n    `95th pct` = money(quantile(x, 0.95)),\n    `Share > 0` = pct(mean(x > 0))\n  )\n}\n\nrep_table <- bind_rows(\n  summarise_gap(\n    gap_trial_rct, \"In-trial value, 10 weeks: BCF minus static RCT\"\n  ),\n  summarise_gap(\n    gap_trial_glb, \"In-trial value, 10 weeks: BCF minus global bandit\"\n  ),\n  summarise_gap(\n    gap_policy_glb,\n    \"Deployed value per customer: BCF policy minus global bandit rule\",\n    usd2\n  ),\n  summarise_gap(\n    gap_policy_rct,\n    \"Deployed value per customer: BCF policy from adaptive data minus BCF policy from RCT data\",\n    usd2\n  )\n)\nknitr::kable(rep_table, align = c(\"l\", \"r\", \"r\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Quantity                                                                                  |    Mean| 5th pct| 95th pct| Share > 0|\n|:-----------------------------------------------------------------------------------------|-------:|-------:|--------:|---------:|\n|In-trial value, 10 weeks: BCF minus static RCT                                            | $11,951| $10,095|  $13,447|      100%|\n|In-trial value, 10 weeks: BCF minus global bandit                                         |  $1,830|   -$420|   $4,062|       88%|\n|Deployed value per customer: BCF policy minus global bandit rule                          |   $1.15|   $0.92|    $1.28|      100%|\n|Deployed value per customer: BCF policy from adaptive data minus BCF policy from RCT data |   $0.05|  -$0.23|    $0.41|       60%|\n\n\n:::\n\n```{.r .cell-code}\nrep_plot_df <- bind_rows(\n  rep_results %>%\n    transmute(\n      seed,\n      panel = \"In-trial net value over 5,000 customers ($)\",\n      `BCF Thompson Sampling` = trial_bcf,\n      `Global Bandit` = trial_glb,\n      `Static RCT Baseline` = trial_rct\n    ) %>%\n    pivot_longer(-c(seed, panel), names_to = \"strategy\"),\n  rep_results %>%\n    transmute(\n      seed,\n      panel = \"Deployed policy value per future customer ($)\",\n      `BCF policy (adaptive trial)` = policy_adaptive,\n      `BCF policy (RCT data)` = policy_rct,\n      `Global bandit rule` = policy_glb\n    ) %>%\n    pivot_longer(-c(seed, panel), names_to = \"strategy\")\n) %>%\n  mutate(\n    panel = factor(panel, levels = c(\n      \"In-trial net value over 5,000 customers ($)\",\n      \"Deployed policy value per future customer ($)\"\n    )),\n    strategy = factor(strategy, levels = rev(c(\n      \"BCF Thompson Sampling\", \"Global Bandit\", \"Static RCT Baseline\",\n      \"BCF policy (adaptive trial)\", \"BCF policy (RCT data)\",\n      \"Global bandit rule\"\n    )))\n  )\n\nggplot(rep_plot_df, aes(x = value, y = strategy, color = strategy)) +\n  geom_jitter(height = 0.18, width = 0, alpha = 0.55, size = 1.8) +\n  stat_summary(\n    fun = mean, geom = \"point\", shape = 18, size = 4.5, color = \"black\",\n    orientation = \"y\"\n  ) +\n  scale_color_manual(values = c(\n    \"BCF Thompson Sampling\" = \"#1a73e8\",\n    \"Global Bandit\" = \"#f9ab00\",\n    \"Static RCT Baseline\" = \"#d93025\",\n    \"BCF policy (adaptive trial)\" = \"#1a73e8\",\n    \"BCF policy (RCT data)\" = \"#d93025\",\n    \"Global bandit rule\" = \"#f9ab00\"\n  )) +\n  scale_x_continuous(labels = scales::dollar_format()) +\n  facet_wrap(~ panel, ncol = 1, scales = \"free\") +\n  labs(\n    title = sprintf(\n      \"%d Replications of the Entire Trial, Different Seeds\", N_REPS\n    ),\n    subtitle = paste(\n      \"Each dot is one replication; the black diamond is the mean.\",\n      \"Holdout is the same 20,000 customers throughout.\"\n    ),\n    x = NULL, y = NULL\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](bad_files/figure-html/replication_summary-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nAcross 40 replications:\n\n- **The in-trial gap over the static RCT is not seed luck.** BCF's\n  ten-week net value exceeds the RCT's in 100%\n  of replications, by $11,951 on average, and\n  even the 5th percentile of the gap is\n  $10,095. This is the\n  regret-minimization benefit, and it is real.\n- **The in-trial gap over the global bandit is real but modest.**\n  BCF finishes the trial ahead of the global bandit in\n  88% of replications, but the average\n  gap is only $1,830 on a base of roughly\n  $32,935, and the 5th–95th percentile\n  range runs from -$420 to\n  $4,062. During the trial,\n  personalization roughly pays for its own exploration and a little\n  more. If your only criterion were revenue during the trial, a\n  global bandit would be a defensible choice — which is the point of\n  Section 5: in-trial revenue is the wrong criterion.\n- **The deployed-policy gap over the global bandit is robust.** The\n  BCF policy beats the single-arm rule on the holdout in\n  100% of replications, by\n  $1.15 per customer on average —\n  $29,866 a year at this\n  call volume. The global bandit crowned Onboarding Assist in\n  98% of replications, so its rule is\n  essentially always the same rule, and always wrong for the same\n  two-thirds of callers.\n- **Adaptive allocation and balanced allocation yield policies of\n  similar value.** Averaged across replications the policy trained on\n  adaptive data is worth $1.81 per customer\n  and the policy trained on RCT data $1.77, a\n  difference of $0.05 in favour of the\n  adaptive data, with the adaptive-trained policy ahead in\n  60% of replications. They capture\n  89% and\n  87% of the oracle's value,\n  respectively. The single run in Section 6 sits inside this spread, and its verdict\n  stands: the adaptive design's edge is what it earned *during* the\n  trial, not a better model at the end of it.\n\n---\n\n## Practical Lessons for the Business Data Scientist\n\n### 1. The Trap of the Non-Contextual Bandit\nProduct teams often ask: *\"Why build a causal forest when an\noff-the-shelf bandit is so simple?\"* As shown above, when treatment\neffects are heterogeneous, **a non-contextual bandit suffers from a\nwinner-takes-all failure mode**. It crowns a single majority arm and\nstarves everyone else.\n\nWhat makes this dangerous in practice is that the bandit does not\nlook broken. It converged quickly, it beat the RCT on revenue, and\nits dashboard shows a clean winner with a tight interval — every\nsignal a reviewer normally checks comes back green. It was simply\nanswering \"which offer is best *on average*?\" when the business\nquestion was \"which offer is best *for this caller*?\" More data\nmakes it more certain about the population-average winner; it\ncannot turn a non-contextual policy into a personalized one, because\nthe model has no place to put the covariates.\n\nBe equally clear about what the comparison does and does not show.\nAny learner that uses the covariates — a bandit run separately\ninside hand-drawn segments, a logistic model with interactions —\nwould close much of the gap to the global bandit when effects are\nthis heterogeneous. Personalization is the big win; BCF's\ncontribution is delivering it without hand-picked segments or\nfunctional forms, while handling the changing propensities and\nreporting posterior uncertainty the allocation rule can act on.\n\n### 2. Always Include an Exploration Floor ($\\epsilon$)\nThompson sampling explores in proportion to posterior uncertainty,\nwhich is elegant right up to the moment the posterior becomes\nconfident and wrong. Two things can starve an arm. The first is\nmechanical: the assignment probability we store is the share of\nretained posterior draws in which the arm wins, and with 200 draws\nan arm that wins none of them gets a probability of exactly zero\nfor that customer. The second is statistical: an unlucky early run\n— a handful of cancellations in Week 1 among the few callers who\nreceived an arm in some corner of the covariate space — can push the\nposterior far enough that the arm is rarely tried there again, and\nthe data that would correct the mistake never arrive. This is the\nfailure @dimakopoulou2018estimation put at the center of contextual\nbandits: a model estimated from non-uniformly assigned data can be\n\"overly optimistic about the extent of the learning so far,\" and\nso under-explore, and the problem is worst when the model is\nmisspecified or when the early cohort is unrepresentative of the\ncustomers who come later.\n\nBlending in an $\\epsilon$-floor (`EPSILON_FLOOR <- 0.05` above, so\nevery arm keeps at least $\\epsilon/4 = 1.25\\%$ of traffic for every\ncaller) rules out the first problem and bounds the damage from the\nsecond. It also guarantees **positivity**: a strictly positive\nassignment probability for every arm and every customer, which is\nwhat causal identification requires, and which the propensity\nhistogram in Section 4 confirms held throughout the trial.\n\nBe precise about what the floor does *not* do. A 1.25% probability\nis a trickle, so an arm the posterior has written off in a region\ngenerates few observations there, and the model's estimates for\nthat arm in that region lean on the prior and on neighbouring\nregions. That is why the tails of the slice plots drift and why\ntheir intervals stay wide. Nor is the floor protection against a\nchange in customer behavior. If the response surface moves, the\nfloor keeps a small stream of evidence flowing from every arm, so\nthe model *can* notice; but learning the new surface takes roughly\nthe data it took to learn the old one, and Lessons 4 and 7 are about\nwhat else you need.\n\n### 3. Propensities Are Known by Design — Store Them\nIn observational studies, propensity scores $\\hat{\\pi}(X)$ must be\nestimated, and the estimation error propagates into everything\ndownstream. In an adaptive trial **you designed the assignment\nmechanism**, so its probabilities are known exactly — for the\nmechanism you actually ran. For Thompson sampling that mechanism\nroutes from a finite set of posterior draws, so the stored\nprobability is the share of those draws in which the arm wins,\nblended with the floor: exact for what the code did, and a Monte\nCarlo approximation to the probability an idealized sampler with\nthe full posterior would have used. There is no closed form for the\nlatter, which is why the simulation computes it directly from the\ndraws it already has — the same Monte Carlo recipe\n@dimakopoulou2018estimation use for Thompson sampling, whose\nassignment probabilities are knowable at all only because the\nalgorithm, not nature, chose them.\n\nTwo details are easy to get wrong here, and both silently degrade\nthe model rather than throwing an error.\n\nFirst, **pass the whole vector**. `propensity_train` takes an\n$n \\times K$ matrix whose columns line up with the columns of `Z`.\nIt is tempting to pass a single column — the propensity of the arm\nthe customer actually received — but that is a *post-randomization*\nquantity: it depends on the coin flip, not on $X$ alone. Feeding it\nto the prognostic forest leaks the realized assignment into\n$\\mu(\\cdot)$, which is the very confounding channel BCF exists to\nclose.\n\nSecond, **store the design probabilities as you go**. They are a\nproperty of the model that was live *at the moment of assignment*,\nand that model no longer exists once you refit next week. In the\nsimulation, `alloc_prob` is carried on each cohort as a full\n$n \\times 4$ matrix for exactly this reason. Reconstructing\npropensities after the fact from a later model is not the same\nquantity and quietly reintroduces the bias.\n\n### 4. Time Is a Confounder in Every Adaptive Design\nThe simulation is stationary: Week 10's callers are drawn from the\nsame population as Week 1's, and the offers work the same way\nthroughout. Real cancellation desks are not. Seasonality, a pricing\nchange, a product release, a new support script, a shift in the\nacquisition mix — any of them moves baseline retention, or the\neffect of an offer, over the course of a trial.\n\nIn a fixed-allocation RCT that is a nuisance: every week's\nrandomization is balanced, so drift cannot masquerade as a\ntreatment effect. In an adaptive trial it is a confounder. The\nallocation probabilities change from week to week *by design*, so\nif the outcome drifts too, calendar time is a common cause of both\ntreatment and outcome, and a model that ignores it will attribute\nthe drift to whichever arms happened to be favoured when it\noccurred. The response-adaptive randomization literature treats this\nas one of the design's central practical risks [@robertson2023rar].\nThe mitigations are the ones this chapter already uses, plus one:\nkeep the stored propensities (they already vary with time), keep the\nexploration floor (so every arm is observed in every period), and\nput calendar time — the week, at minimum — into the covariates of\nthe prognostic forest so that drift has somewhere to go other than\nthe treatment forest.\n\n### 5. Inference From Adaptively Collected Data Is Different\nOne more consequence of adaptive allocation is easy to miss because\nthis chapter is Bayesian. Simple sample averages computed from\nadaptively collected data are biased — an arm whose early results\nlook bad is sampled less, so its bad luck is never averaged out —\nand naive confidence intervals for arm means or policy values do not\nhave their nominal coverage; @hadad2021confidence show how to\nreweight the data to restore it. A fully Bayesian analysis with a\ncorrectly specified model is, in principle, immune: the allocation\nrule depends only on data the model has already conditioned on, so\nit drops out of the posterior. That immunity is only as good as the\nmodel, which is one more reason to take the exploration floor, the\nstored propensities, and the time covariate seriously rather than\ntrusting the posterior to absorb every design choice. And if you\never use the stored propensities as inverse-probability *weights* —\nto evaluate a candidate policy offline on the trial's data, say —\nclip them first. @dimakopoulou2018estimation tune the clipping\nthreshold between 0.01 and 0.2, because otherwise the few\nobservations of rarely assigned arms dominate the variance.\n\n### 6. Handling Delayed Feedback Loops\nIn our case study, retention was observable at the end of the call.\nIf churn takes 30 or 60 days to confirm, the model can only learn\nfrom callers whose outcomes have matured, and there are two honest\nways to run the design:\n\n- **Slow the cadence.** Refit and re-route every 30 days rather than\n  weekly, using only matured outcomes. Callers with pending outcomes\n  are still assigned by the current policy; they simply do not enter\n  the fit until their outcome is known.\n- **Use a validated surrogate.** Short-term signals — product logins\n  in the week after the call, say — can stand in for retention, using\n  the techniques of the [Surrogates](surrogates.qmd) chapter. The\n  word *validated* is doing real work. A surrogate that is merely\n  correlated with retention is not enough: the effect of an offer on\n  the surrogate has to be a reliable guide to its effect on\n  retention, and that relationship has to have been established on\n  data where both were observed. Adapting on an unvalidated\n  surrogate optimizes the surrogate.\n\n### 7. Transitioning to Production — and Never Quite Stopping\nAt the end of the trial, you don't just produce a static slide\ndeclaring a single \"winner.\" You serialize the fitted multivariate\nBCF model (`saveBCFModelToJsonFile()` writes it to disk;\n`createBCFModelFromJsonFile()` reads it back) and deploy the learned\ndecision policy:\n\n$$\nz^*(X) = \\arg\\max_{k \\in \\{0, 1, 2, 3\\}} \\left( \\hat{\\tau}_k(X)\n  \\times \\text{LTV} - \\text{Cost}_k \\right)\n$$\n\ninto your CRM or customer support software, delivering personalized\nretention offers to every future customer in real time.\n\nTwo habits keep that deployment honest. First, keep a slice of\nrandomized traffic — the same $\\epsilon$-floor, now in a production\nrole — so the deployed policy can be evaluated against its\nalternatives on fresh data instead of being trusted because it was\nright in Week 10. Second, refit on a schedule, with calendar time in\nthe covariates, because the surface you learned is a snapshot of a\npopulation and an offer set that will both change. A model that\nstops experimenting can only confirm its own beliefs.\n\n---\n\n## Conclusion\n\nResponse-adaptive randomization with multivariate BCF turns an\nexperiment into a system that earns while it learns and hands you a\n*personalized decision rule* at the end rather than a single winning\narm. Read carefully, though, this chapter's results say something\nmore specific than the pitch, and the replications in Section 7 say\nhow much of it to trust:\n\n1. **Adaptive allocation is a regret-minimization technique.**\n   Against the static RCT it was worth $11,365\n   over a single ten-week trial in the main run, and\n   $11,951 on average across 40\n   replications, ahead in 100% of them.\n   Real, immediate, and not seed luck.\n2. **Personalization is where the money is, and it is annual.** The\n   *learned policy* is worth $1.15 per\n   customer more than the global bandit's single-arm rule across\n   replications — $29,866 a\n   year at 500 callers a week — and it beat that rule in\n   100% of replications. This benefit\n   dwarfs the first, and it only exists because the model can ask\n   *for whom*.\n3. **Adaptive allocation did not buy a better model.** A BCF fit to\n   balanced RCT data yields a policy of very similar value; the\n   adaptive design's edge is what it earned *during* the trial.\n4. **Knowing whom not to treat is most of the prize.** Treating\n   everyone with an untargeted offer is worth -$1.47 per\n   customer — negative.\n\nAll of this was measured in a friendly world: two covariates that\nare exactly the ones the effects depend on, a stationary population,\noutcomes observed immediately, no interference between customers,\nconstant costs and LTV, an effect surface smooth enough for trees\nto find, and a first week of data that is a representative sample\nof the customers who follow. Each of those is an assumption you will\nhave to check, and Practical Lessons 4 through 7 are about what to\ndo when they fail. @dimakopoulou2018estimation show what happens\nwhen the last one fails — a warm-start batch drawn from one corner\nof the covariate space — and how balancing and longer exploration\nrepair it. The methodological point survives all of them: reach for\nresponse-adaptive randomization when in-trial regret is expensive —\nlive customers, real incentives, revenue on the line. If your\npriority is a precisely estimated effect surface, especially in\nregions where the optimal action is already obvious, a balanced\ndesign is still the better instrument. Knowing which of those two\nproblems you have is the actual skill.\n\n::: {.callout-tip}\n## Learn more\n- @finucane2018works: *What works for whom? A Bayesian approach to\n  channeling big data streams for public program evaluation.*\n  American Journal of Evaluation.\n- @hahn2020bayesian: *Bayesian regression tree models for causal\n  inference: Regularization, confounding, and heterogeneous\n  effects.* Bayesian Analysis.\n- @stochastictree: *stochtree: Stochastic tree ensembles (XBART and\n  BART) for supervised learning and causal inference.*\n- @thompson1933likelihood: the 1933 paper that introduced what we\n  now call Thompson sampling, and @russo2018tutorial for a modern\n  tutorial.\n- @robertson2023rar: *Response-adaptive randomization in clinical\n  trials: from myths to practical considerations.* Statistical\n  Science. The definitive account of what can go wrong, including\n  time trends.\n- @hadad2021confidence: *Confidence intervals for policy evaluation\n  in adaptive experiments.* PNAS. How to do valid inference on data\n  a bandit collected.\n- @dimakopoulou2018estimation: *Estimation considerations in\n  contextual bandits.* Why the way a bandit explores today shapes\n  what it can estimate tomorrow, and how balancing on known\n  propensities helps.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}